# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

variables:
  - template: templates/utils/variables.yml

resources:
  repositories:
    - repository: Library
      type: github
      endpoint: github.com_surveyjsdeveloper
      name: surveyjs/survey-library
      ref: $(System.PullRequest.TargetBranch)
    - repository: Creator
      type: github
      endpoint: github.com_surveyjsdeveloper
      name: surveyjs/survey-creator
      ref: $(System.PullRequest.TargetBranch)
    - repository: Analytics
      type: github
      endpoint: github.com_surveyjsdeveloper
      name: surveyjs/survey-analytics
      ref: $(System.PullRequest.TargetBranch)
    - repository: PDF
      type: github
      endpoint: github.com_surveyjsdeveloper
      name: surveyjs/survey-pdf
      ref: $(System.PullRequest.TargetBranch)

trigger: none

pr:
  branches:
    include:
      - master

pool:
  name: main-selfhosted

stages:
  - stage: Lint
    dependsOn: []
    jobs:
      - job:
        steps:
          - checkout: self
          - script: npm install --prefer-offline --no-audit --no-fund --no-update-notifier --no-package-lock --verbose
            workingDirectory: $(Build.SourcesDirectory)
            displayName: "npm install"
          - script: npm run lint

  - stage: Options
    dependsOn: []
    jobs:
      - job: PRTitle
        displayName: "Parse PR title"
        steps:
          - template: templates/utils/pr_title_parser.yml



  - stage: Library
    dependsOn:
      - Options
    variables:
      PR: $[ stageDependencies.Options.PRTitle.outputs['data.LIBRARY'] ]
    jobs:
      - job: Download
        continueOnError: true
        variables:
          LIBRARY_PIPELINE: $[ iif(eq(variables.PR, ''), variables.PipelineLibrary, variables.PipelineLibraryPR) ]
        steps:
          - checkout: none

          - template: templates/utils/artifact.yml
            parameters:
              pr: $(PR)
              pipeline: $(LIBRARY_PIPELINE)
              artifacts:
                - $(ArtifactNameLibraryCore)
                - $(ArtifactNameLibraryReact)
                - $(ArtifactNameLibraryAngular)
                - $(ArtifactNameLibraryVue)
                - $(ArtifactNameLibraryJS)

          - bash: |
              if [ -z "$(PR)" ]; then
                cp -a $(Agent.TempDirectory)/$(ArtifactNameLibraryCore)/packages/survey-core/. $(Build.SourcesDirectory)/survey-core/
                cp -a $(Agent.TempDirectory)/$(ArtifactNameLibraryReact)/packages/survey-react-ui/. $(Build.SourcesDirectory)/survey-react-ui/
                cp -a $(Agent.TempDirectory)/$(ArtifactNameLibraryAngular)/packages/survey-angular-ui/. $(Build.SourcesDirectory)/survey-angular-ui/
                cp -a $(Agent.TempDirectory)/$(ArtifactNameLibraryVue)/packages/survey-vue3-ui/. $(Build.SourcesDirectory)/survey-vue3-ui/
                cp -a $(Agent.TempDirectory)/$(ArtifactNameLibraryJS)/packages/survey-js-ui/. $(Build.SourcesDirectory)/survey-js-ui/
              else
                cp -a $(Agent.TempDirectory)/$(ArtifactNameLibraryCore)/. $(Build.SourcesDirectory)/survey-core/
                cp -a $(Agent.TempDirectory)/$(ArtifactNameLibraryReact)/. $(Build.SourcesDirectory)/survey-react-ui/
                cp -a $(Agent.TempDirectory)/$(ArtifactNameLibraryAngular)/. $(Build.SourcesDirectory)/survey-angular-ui/
                cp -a $(Agent.TempDirectory)/$(ArtifactNameLibraryVue)/. $(Build.SourcesDirectory)/survey-vue3-ui/
                cp -a $(Agent.TempDirectory)/$(ArtifactNameLibraryJS)/. $(Build.SourcesDirectory)/survey-js-ui/
              fi
            displayName: "Copy"

          - task: PublishBuildArtifacts@1
            inputs:
              PathtoPublish: '$(Build.SourcesDirectory)/survey-core'
              ArtifactName: $(ArtifactNameLibraryCore)
              publishLocation: 'Container'
              StoreAsTar: true

          - task: PublishBuildArtifacts@1
            inputs:
              PathtoPublish: '$(Build.SourcesDirectory)/survey-react-ui'
              ArtifactName: $(ArtifactNameLibraryReact)
              publishLocation: 'Container'
              StoreAsTar: true

          - task: PublishBuildArtifacts@1
            inputs:
              PathtoPublish: '$(Build.SourcesDirectory)/survey-angular-ui'
              ArtifactName: $(ArtifactNameLibraryAngular)
              publishLocation: 'Container'
              StoreAsTar: true

          - task: PublishBuildArtifacts@1
            inputs:
              PathtoPublish: '$(Build.SourcesDirectory)/survey-vue3-ui'
              ArtifactName: $(ArtifactNameLibraryVue)
              publishLocation: 'Container'
              StoreAsTar: true

          - task: PublishBuildArtifacts@1
            inputs:
              PathtoPublish: '$(Build.SourcesDirectory)/survey-js-ui'
              ArtifactName: $(ArtifactNameLibraryJS)
              publishLocation: 'Container'
              StoreAsTar: true

      - job: BuildCore
        displayName: "Build Core"
        dependsOn: Download
        condition: in(dependencies.Download.result, 'Failed', 'SucceededWithIssues')
        steps:
          - checkout: Library

          - script: git fetch origin pull/$(PR)/head && git checkout FETCH_HEAD
            workingDirectory: $(Build.SourcesDirectory)
            displayName: "Checkout PR $(PR)"
            condition: ne(variables.PR, '')

          - template: templates/utils/npm.yml
            parameters:
              directories:
                - $(Build.SourcesDirectory)
                - $(Build.SourcesDirectory)/packages/survey-core

          - script: npm run build:all
            workingDirectory: $(Build.SourcesDirectory)/packages/survey-core
            displayName: "Build"

          - task: PublishBuildArtifacts@1
            inputs:
              PathtoPublish: '$(Build.SourcesDirectory)/packages/survey-core/build/'
              ArtifactName: $(ArtifactNameLibraryCore)
              publishLocation: 'Container'
              StoreAsTar: true

      - job: BuildReact
        displayName: "Build React"
        dependsOn: Download
        condition: in(dependencies.Download.result, 'Failed', 'SucceededWithIssues')
        steps:
          - checkout: Library

          - script: git fetch origin pull/$(PR)/head && git checkout FETCH_HEAD
            workingDirectory: $(Build.SourcesDirectory)
            displayName: "Checkout PR $(PR)"
            condition: ne(variables.PR, '')

          - template: templates/utils/npm.yml
            parameters:
              directories:
                - $(Build.SourcesDirectory)
                - $(Build.SourcesDirectory)/packages/survey-core
                - $(Build.SourcesDirectory)/packages/survey-react-ui

          - script: npm run build:all
            workingDirectory: $(Build.SourcesDirectory)/packages/survey-core
            displayName: "Build Core"

          - script: npm run build
            workingDirectory: $(Build.SourcesDirectory)/packages/survey-react-ui
            displayName: "Build"

          - task: PublishBuildArtifacts@1
            inputs:
              PathtoPublish: '$(Build.SourcesDirectory)/packages/survey-react-ui/build/'
              ArtifactName: $(ArtifactNameLibraryReact)
              publishLocation: 'Container'
              StoreAsTar: true

      - job: BuildAngular
        displayName: "Build Angular"
        dependsOn: Download
        condition: in(dependencies.Download.result, 'Failed', 'SucceededWithIssues')
        steps:
          - checkout: Library

          - script: git fetch origin pull/$(PR)/head && git checkout FETCH_HEAD
            workingDirectory: $(Build.SourcesDirectory)
            displayName: "Checkout PR $(PR)"
            condition: ne(variables.PR, '')

          - template: templates/utils/npm.yml
            parameters:
              directories:
                - $(Build.SourcesDirectory)
                - $(Build.SourcesDirectory)/packages/survey-core
                - $(Build.SourcesDirectory)/packages/survey-angular-ui

          - script: npm run build:all
            workingDirectory: $(Build.SourcesDirectory)/packages/survey-core
            displayName: "Build Core"

          - script: npm run build
            workingDirectory: $(Build.SourcesDirectory)/packages/survey-angular-ui
            displayName: "Build"

          - task: PublishBuildArtifacts@1
            inputs:
              PathtoPublish: '$(Build.SourcesDirectory)/packages/survey-angular-ui/build/'
              ArtifactName: $(ArtifactNameLibraryAngular)
              publishLocation: 'Container'
              StoreAsTar: true

      - job: BuildVue
        displayName: "Build Vue"
        dependsOn: Download
        condition: in(dependencies.Download.result, 'Failed', 'SucceededWithIssues')
        steps:
          - checkout: Library

          - script: git fetch origin pull/$(PR)/head && git checkout FETCH_HEAD
            workingDirectory: $(Build.SourcesDirectory)
            displayName: "Checkout PR $(PR)"
            condition: ne(variables.PR, '')

          - template: templates/utils/npm.yml
            parameters:
              directories:
                - $(Build.SourcesDirectory)
                - $(Build.SourcesDirectory)/packages/survey-core
                - $(Build.SourcesDirectory)/packages/survey-vue3-ui

          - script: npm run build:all
            workingDirectory: $(Build.SourcesDirectory)/packages/survey-core
            displayName: "Build Core"

          - script: npm run build
            workingDirectory: $(Build.SourcesDirectory)/packages/survey-vue3-ui
            displayName: "Build"

          - task: PublishBuildArtifacts@1
            inputs:
              PathtoPublish: '$(Build.SourcesDirectory)/packages/survey-vue3-ui/build/'
              ArtifactName: $(ArtifactNameLibraryVue)
              publishLocation: 'Container'
              StoreAsTar: true

      - job: BuildSurveyUI
        displayName: "Build JS UI"
        dependsOn: Download
        condition: in(dependencies.Download.result, 'Failed', 'SucceededWithIssues')
        steps:
          - checkout: Library

          - script: git fetch origin pull/$(PR)/head && git checkout FETCH_HEAD
            workingDirectory: $(Build.SourcesDirectory)
            displayName: "Checkout PR $(PR)"
            condition: ne(variables.PR, '')

          - template: templates/utils/npm.yml
            parameters:
              directories:
                - $(Build.SourcesDirectory)
                - $(Build.SourcesDirectory)/packages/survey-core
                - $(Build.SourcesDirectory)/packages/survey-js-ui

          - script: npm run build:all
            workingDirectory: $(Build.SourcesDirectory)/packages/survey-core
            displayName: "Build Core"

          - script: npm run build
            workingDirectory: $(Build.SourcesDirectory)/packages/survey-js-ui
            displayName: "Build"

          - task: PublishBuildArtifacts@1
            inputs:
              PathtoPublish: '$(Build.SourcesDirectory)/packages/survey-js-ui/build/'
              ArtifactName: $(ArtifactNameLibraryJS)
              publishLocation: 'Container'
              StoreAsTar: true





  - stage: CreatorCore
    displayName: "Creator Core"
    dependsOn:
      - Library
    jobs:
      - job:
        displayName: "Build"
        steps:
          - template: templates/creator/core/build.yml
            parameters:
              store: true
      - template: templates/creator/core/test.yml

  - stage: CreatorReactBuild
    displayName: "Creator React"
    dependsOn:
      - Library
    jobs:
      - job:
        displayName: "Build"
        steps:
          - template: templates/creator/react/build.yml
            parameters:
              store: true
      - template: templates/creator/react/test.yml

  - stage: CreatorAngularBuild
    displayName: "Creator Angular"
    dependsOn:
      - Library
    jobs:
      - job:
        displayName: "Build"
        steps:
          - template: templates/creator/angular/build.yml
            parameters:
              store: true
      - template: templates/creator/angular/test.yml

  - stage: CreatorVueBuild
    displayName: "Creator Vue"
    dependsOn:
      - Library
    jobs:
      - job:
        displayName: "Build"
        steps:
          - template: templates/creator/vue/build.yml
            parameters:
              store: true
      - template: templates/creator/vue/test.yml

  - stage: CreatorJSBuild
    displayName: "Creator JS (Preact ShadowDOM BoxSizing)"
    dependsOn:
      - Library
    jobs:
      - job:
        displayName: "Build"
        steps:
          - template: templates/creator/js/build.yml
            parameters:
              store: true
      - template: templates/creator/js/test.yml