# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- master

pool:
  vmImage: ubuntu-latest

jobs:

- job: BuildCreatorV1

  steps:
  - task: NodeTool@0
    inputs:
      versionSpec: '10.x'
    displayName: 'Install Node.js'

  - task: DownloadBuildArtifacts@0
    inputs:
      buildType: 'specific'
      project: 'af2804d2-859a-4705-9ef5-cdf46d1d5d4f'
      pipeline: '7'
      specificBuildWithTriggering: true
      buildVersionToDownload: 'latest'
      downloadType: 'single'
      artifactName: 'SurveyJSLibraryBuild'
      downloadPath: '$(System.ArtifactsDirectory)'

  - script: |
      cd $(Build.SourcesDirectory)/survey-creator/packages/survey-creator
      npm install
    displayName: 'npm install SurveyJS Creator V1'

  - task: CopyFiles@2
    inputs:
      SourceFolder: '$(System.ArtifactsDirectory)/SurveyJSLibraryBuild/packages/survey-knockout'
      Contents: '**'
      TargetFolder: '$(Build.SourcesDirectory)/survey-creator/packages/survey-creator/node_modules/survey-knockout'
      OverWrite: true

  - script: |
      cd $(Build.SourcesDirectory)/survey-creator/packages/survey-creator
      npm run build_prod
    displayName: 'npm install and build SurveyJS Creator V1'

  - script: |
      cd $(Build.SourcesDirectory)/survey-creator/packages/survey-creator
      npm run test_ci
    displayName: 'Unit tests'

  - script: |
      cd $(Build.SourcesDirectory)/survey-creator/packages/survey-creator
      npm run testcafe_ci
    displayName: 'Functional tests'

- job: BuildCreatorV2React

  steps:
  - task: NodeTool@0
    inputs:
      versionSpec: '10.x'
    displayName: 'Install Node.js'

  - task: DownloadBuildArtifacts@0
    inputs:
      buildType: 'specific'
      project: 'af2804d2-859a-4705-9ef5-cdf46d1d5d4f'
      pipeline: '7'
      specificBuildWithTriggering: true
      buildVersionToDownload: 'latest'
      downloadType: 'single'
      artifactName: 'SurveyJSLibraryBuild'
      downloadPath: '$(System.ArtifactsDirectory)'

  - task: CopyFiles@2
    inputs:
      SourceFolder: '$(System.ArtifactsDirectory)/SurveyJSLibraryBuild/packages'
      Contents: '**'
      TargetFolder: '$(Build.SourcesDirectory)/survey-library/build'
      OverWrite: true

  # - script: |
  #     npm install
  #     npm run remove-package-lock
  #   displayName: 'Npm install'

  - script: |
      cd $(Build.SourcesDirectory)/survey-creator/packages/survey-creator-core
      npm install
      npm run remove-package-lock
    displayName: 'Npm install survey-creator-core'

  - script: |
      cd $(Build.SourcesDirectory)/survey-creator/packages/survey-creator-core
      npm run build
    displayName: 'Build creator v2 core'

  - script: |
      cd $(Build.SourcesDirectory)/survey-creator/packages/survey-creator-core
      npm run test
    displayName: 'Unit tests CreatorV2 Core'

  - script: |
      cd $(Build.SourcesDirectory)/survey-creator/packages/survey-creator-react
      npm install
      npm run remove-package-lock
    displayName: 'Npm install survey-creator-react'

  - script: |
      cd $(Build.SourcesDirectory)/survey-creator/packages/survey-creator-react
      npm run build
    displayName: 'Build CreatorV2 React'

  - script: |
      cd $(Build.SourcesDirectory)/survey-creator/packages/survey-creator-react
      npm run test
    displayName: 'Unit test CreatorV2 React'

  - script: |
      cd $(Build.SourcesDirectory)/survey-creator/packages/survey-creator-react
      npm run testcafe
    displayName: 'Functional test CreatorV2 React'
