# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

resources:
  repositories:
    - repository: Service # The name used to reference this repository in the checkout step
      type: github
      endpoint: dmitrykurmanov:admin
      name: surveyjs/service

trigger:
  batch: true
  branches:
    include:
    - master
  tags:
    exclude:
      - v*.*.*

pool:
  vmImage: 'Ubuntu-18.04'

jobs:

- job: Intro

  steps:
  - checkout: self
  - checkout: Service
    persistCredentials: true
    clean: true

  - task: NodeTool@0
    inputs:
      versionSpec: '14.x'
    displayName: 'Install Node.js'

  - powershell: |
      $env:GIT_REDIRECT_STDERR = '2>&1'
      git config --global user.email "kurmanov.work@gmail.com"
      git config --global user.name "dmitrykurmanov"
    displayName: 'Set up git config'

  - task: DownloadBuildArtifacts@0
    inputs:
      buildType: 'specific'
      project: 'af2804d2-859a-4705-9ef5-cdf46d1d5d4f'
      pipeline: '7'
      specificBuildWithTriggering: true
      buildVersionToDownload: 'latest'
      downloadType: 'single'
      artifactName: 'SurveyJSLibraryBuild'
      downloadPath: '$(System.ArtifactsDirectory)'

  - task: CopyFiles@2
    inputs:
      SourceFolder: '$(System.ArtifactsDirectory)/SurveyJSLibraryBuild/packages'
      Contents: '**'
      TargetFolder: '$(Build.SourcesDirectory)/survey-library/build'
      OverWrite: true


- job: CreatorV1
  dependsOn: Intro

  steps:
  - script: |
      cd $(Build.SourcesDirectory)/survey-creator/packages/survey-creator
      npm install
    displayName: 'Npm install survey-creator'

  - task: CopyFiles@2
    inputs:
      SourceFolder: '$(System.ArtifactsDirectory)/SurveyJSLibraryBuild/packages/survey-knockout'
      Contents: '**'
      TargetFolder: '$(Build.SourcesDirectory)/survey-creator/packages/survey-creator/node_modules/survey-knockout'
      OverWrite: true

  - script: |
      cd $(Build.SourcesDirectory)/survey-creator/packages/survey-creator
      npm run build_prod
    displayName: 'Build prod'

  - script: |
      cd $(Build.SourcesDirectory)/survey-creator/packages/survey-creator
      npm run test_ci
    displayName: 'Unit tests'

  - script: |
      cd $(Build.SourcesDirectory)/survey-creator/packages/survey-creator
      npm run testcafe_ci
    displayName: 'Functional tests'

  - script: |
      mkdir $(Build.SourcesDirectory)/survey-creator/packages/survey-creator/docs
      cd $(Build.SourcesDirectory)/survey-creator/packages/survey-creator
      npm run doc_gen
    displayName: 'Generate docs'

  - task: CopyFiles@2
    inputs:
      SourceFolder: '$(Build.SourcesDirectory)/survey-creator/docs'
      TargetFolder: '$(Build.SourcesDirectory)/service/surveyjs.io/App_Data/DocsEditor'
      CleanTargetFolder: true
    displayName: 'Copy root docs to the local surveyjs/service repo'

  - task: CopyFiles@2
    inputs:
      SourceFolder: '$(Build.SourcesDirectory)/survey-creator/packages/survey-creator/docs'
      TargetFolder: '$(Build.SourcesDirectory)/service/surveyjs.io/App_Data/DocsEditor'
      CleanTargetFolder: false
    displayName: 'Copy generated docs to the local surveyjs/service repo'

  # read about the problem with git output ($env:GIT_REDIRECT_STDERR = '2>&1') :
  # https://github.com/microsoft/azure-pipelines-yaml/issues/248
  # https://stackoverflow.com/questions/58485585/azure-pipeline-powershell-and-git-on-windows-server-2019-gives-error-in-output
  - powershell: |
      cd $(Build.SourcesDirectory)/service
      git checkout master
      git pull origin master
      git fetch --tags --force
      git add surveyjs.io/App_Data/DocsEditor
      git commit -m "updated survey-creator docs"
      git pull origin master
      git push origin master
    displayName: 'Git surveyjs/service push updated docs'

  - task: CopyFiles@2
    inputs:
      SourceFolder: '$(Build.SourcesDirectory)/survey-creator/packages/survey-creator/build'
      targetFolder: $(Build.ArtifactStagingDirectory)/SurveyJSCreatorBuild/build


- job: CreatorV2Core
  dependsOn: Intro

  steps:
  - script: |
      cd $(Build.SourcesDirectory)/survey-creator/packages/survey-creator-core
      npm install
      npm run remove-package-lock
    displayName: 'Npm install survey-creator-core'

  - script: |
      cd $(Build.SourcesDirectory)/survey-creator/packages/survey-creator-core
      npm run build
    displayName: 'Build creator v2 core'

  - script: |
      cd $(Build.SourcesDirectory)/survey-creator/packages/survey-creator-core
      npm run test
    displayName: 'Unit tests CreatorV2 Core'


- job: CreatorV2Knockout
  dependsOn: CreatorV2Core

  steps:
  - script: |
      cd $(Build.SourcesDirectory)/survey-creator/packages/survey-creator-knockout
      npm install
      npm run remove-package-lock
    displayName: 'Npm install survey-creator-knockout'

  - script: |
      cd $(Build.SourcesDirectory)/survey-creator/packages/survey-creator-react
      npm run build
    displayName: 'Build CreatorV2 React'

  - script: |
      cd $(Build.SourcesDirectory)/survey-creator/packages/survey-creator-react
      npm run test
    displayName: 'Unit test CreatorV2 React'

  - script: |
      cd $(Build.SourcesDirectory)/survey-creator/packages/survey-creator-react
      npm run testcafe
    displayName: 'Functional test CreatorV2 React'


- job: CreatorV2React
  dependsOn: CreatorV2Core

  steps:
  - script: |
      cd $(Build.SourcesDirectory)/survey-creator/packages/survey-creator-react
      npm install
      npm run remove-package-lock
    displayName: 'Npm install survey-creator-react'

  - script: |
      cd $(Build.SourcesDirectory)/survey-creator/packages/survey-creator-react
      npm run build
    displayName: 'Build CreatorV2 React'

  - script: |
      cd $(Build.SourcesDirectory)/survey-creator/packages/survey-creator-react
      npm run test
    displayName: 'Unit test CreatorV2 React'

  - script: |
      cd $(Build.SourcesDirectory)/survey-creator/packages/survey-creator-react
      npm run testcafe
    displayName: 'Functional test CreatorV2 React'

