# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

resources:
  repositories:
    - repository: Service
      type: github
      endpoint: dmitrykurmanov:admin
      name: surveyjs/service

trigger:
  batch: true
  branches:
    exclude:
    - master
  tags:
    exclude:
      - v*.*.*

pool:
  vmImage: 'Ubuntu-18.04'

jobs:

- job: CreatorV1

  steps:
  - checkout: self
  - checkout: Service
    persistCredentials: true
    clean: true

  - task: NodeTool@0
    inputs:
      versionSpec: '14.x'
    displayName: 'Install Node.js'

  - powershell: |
      $env:GIT_REDIRECT_STDERR = '2>&1'
      git config --global user.email "kurmanov.work@gmail.com"
      git config --global user.name "dmitrykurmanov"
    displayName: 'Set up git config'

  - task: DownloadBuildArtifacts@0
    inputs:
      buildType: 'specific'
      project: 'af2804d2-859a-4705-9ef5-cdf46d1d5d4f'
      pipeline: '56'
      specificBuildWithTriggering: true
      buildVersionToDownload: 'latest'
      downloadType: 'single'
      artifactName: 'SurveyJSLibraryBuild'
      downloadPath: '$(System.ArtifactsDirectory)'

  - script: |
      cd $(Build.SourcesDirectory)/survey-creator/packages/survey-creator
      npm install
    displayName: 'Npm install survey-creator'

  - task: CopyFiles@2
    inputs:
      SourceFolder: '$(System.ArtifactsDirectory)/SurveyJSLibraryBuild/packages/survey-knockout'
      Contents: '**'
      TargetFolder: '$(Build.SourcesDirectory)/survey-creator/packages/survey-creator/node_modules/survey-knockout'
      OverWrite: true

  - task: CopyFiles@2
    inputs:
      SourceFolder: '$(System.ArtifactsDirectory)/SurveyJSLibraryBuild/'
      Contents: 'version.txt'
      TargetFolder: '$(Build.SourcesDirectory)/'
      OverWrite: true
    displayName: 'Copy build artifact - SurveyJSVersion File'

  - powershell: |
      $version = Get-Content $(Build.SourcesDirectory)/version.txt
      Write-Host "##vso[task.setvariable variable=SurveyJSVersion;]$version"
    displayName: 'Setup SurveyJSVersion variable from SurveyJSVersionFile'

  - powershell: |
      cd $(Build.SourcesDirectory)/survey-creator/packages/survey-creator
      npm run release -- --release-as $(SurveyJSVersion)
    displayName: 'Release specific version survey-creator'

  - task: DownloadBuildArtifacts@0
    inputs:
      buildType: 'specific'
      project: 'af2804d2-859a-4705-9ef5-cdf46d1d5d4f'
      pipeline: '42'
      specificBuildWithTriggering: true
      buildVersionToDownload: 'latest'
      downloadType: 'single'
      artifactName: 'SurveyJSWidgetsBuild'
      downloadPath: '$(System.ArtifactsDirectory)'

  - task: CopyFiles@2
    inputs:
      SourceFolder: '$(System.ArtifactsDirectory)/SurveyJSWidgetsBuild/packages/survey-widgets'
      Contents: '**'
      TargetFolder: '$(Build.SourcesDirectory)/survey-creator/packages/survey-creator/node_modules/surveyjs-widgets'
      OverWrite: true

  - script: |
      cd $(Build.SourcesDirectory)/survey-creator/packages/survey-creator
      npm run build_prod
    displayName: 'Build prod'

  - script: |
      cd $(Build.SourcesDirectory)/survey-creator/packages/survey-creator
      npm run test_ci
    displayName: 'Unit tests'

  - script: |
      cd $(Build.SourcesDirectory)/survey-creator/packages/survey-creator
      npm run testcafe_ci
    displayName: 'Functional tests'
    env:
      TESTCAFE_DASHBOARD_AUTHENTICATION_TOKEN: $(TESTCAFE_DASHBOARD_AUTHENTICATION_TOKEN_V1)
      TESTCAFE_DASHBOARD_URL: $(TESTCAFE_DASHBOARD_URL)


- job: CreatorV2Core
  steps:
  - checkout: self
  - checkout: Service
    persistCredentials: true
    clean: true

  - task: NodeTool@0
    inputs:
      versionSpec: '14.x'
    displayName: 'Install Node.js'

  - powershell: |
      $env:GIT_REDIRECT_STDERR = '2>&1'
      git config --global user.email "kurmanov.work@gmail.com"
      git config --global user.name "dmitrykurmanov"
    displayName: 'Set up git config'

  - task: DownloadBuildArtifacts@0
    inputs:
      buildType: 'specific'
      project: 'af2804d2-859a-4705-9ef5-cdf46d1d5d4f'
      pipeline: '56'
      specificBuildWithTriggering: true
      buildVersionToDownload: 'latest'
      downloadType: 'single'
      artifactName: 'SurveyJSLibraryBuild'
      downloadPath: '$(System.ArtifactsDirectory)'

  - task: CopyFiles@2
    inputs:
      SourceFolder: '$(System.ArtifactsDirectory)/SurveyJSLibraryBuild/packages'
      Contents: '**'
      TargetFolder: '$(Build.SourcesDirectory)/survey-library/build'
      OverWrite: true

  - script: |
      cd $(Build.SourcesDirectory)/survey-creator/packages/survey-creator-core
      npm install
      npm run remove-package-lock
    displayName: 'Npm install survey-creator-core'

  - powershell: |
      cd $(Build.SourcesDirectory)/survey-creator/packages/survey-creator-core
      npm run release
    displayName: 'Release specific version survey-creator-core'

  - script: |
      cd $(Build.SourcesDirectory)/survey-creator/packages/survey-creator-core
      npm run build
    displayName: 'Build Creator V2 Core'

  - script: |
      cd $(Build.SourcesDirectory)/survey-creator/packages/survey-creator-core
      npm run test
    displayName: 'Unit tests CreatorV2 Core'

  - task: CopyFiles@2
    inputs:
      SourceFolder: '$(Build.SourcesDirectory)/survey-creator/packages/survey-creator-core/build'
      targetFolder: $(Build.ArtifactStagingDirectory)/SurveyJSCreatorV2Build/build/survey-creator-core

  - task: PublishBuildArtifacts@1
    inputs:
      PathtoPublish: '$(Build.ArtifactStagingDirectory)/SurveyJSCreatorV2Build/build/survey-creator-core'
      ArtifactName: 'SurveyJSCreatorV2BuildCore'
      publishLocation: 'Container'  


- job: CreatorV2React
  dependsOn: CreatorV2Core
  steps:
  - checkout: self
  - checkout: Service
    persistCredentials: true
    clean: true

  - task: NodeTool@0
    inputs:
      versionSpec: '14.x'
    displayName: 'Install Node.js'

  - powershell: |
      $env:GIT_REDIRECT_STDERR = '2>&1'
      git config --global user.email "kurmanov.work@gmail.com"
      git config --global user.name "dmitrykurmanov"
    displayName: 'Set up git config'

  - task: DownloadBuildArtifacts@0
    inputs:
      buildType: 'specific'
      project: 'af2804d2-859a-4705-9ef5-cdf46d1d5d4f'
      pipeline: '56'
      specificBuildWithTriggering: true
      buildVersionToDownload: 'latest'
      downloadType: 'single'
      artifactName: 'SurveyJSLibraryBuild'
      downloadPath: '$(System.ArtifactsDirectory)'

  - task: DownloadBuildArtifacts@0
    inputs:
      buildType: 'current'
      downloadType: 'single'
      artifactName: 'SurveyJSCreatorV2BuildCore'
      downloadPath: '$(System.ArtifactsDirectory)'

  - task: CopyFiles@2
    inputs:
      SourceFolder: '$(System.ArtifactsDirectory)/SurveyJSLibraryBuild/packages'
      Contents: '**'
      TargetFolder: '$(Build.SourcesDirectory)/survey-library/build'
      OverWrite: true

  - task: CopyFiles@2
    inputs:
      SourceFolder: $(System.ArtifactsDirectory)/SurveyJSCreatorV2BuildCore
      TargetFolder: '$(Build.SourcesDirectory)/survey-creator/packages/survey-creator-core/build'

  - script: |
      cd $(Build.SourcesDirectory)/survey-creator/packages/survey-creator-react
      npm install
      npm run remove-package-lock
    displayName: 'Npm install survey-creator-react'

  - task: CopyFiles@2
    inputs:
      SourceFolder: '$(System.ArtifactsDirectory)/SurveyJSLibraryBuild/build/survey-core'
      Contents: '**'
      TargetFolder: '$(Build.SourcesDirectory)/survey-creator/packages/survey-creator-react/node_modules/survey-core'
      OverWrite: true
    displayName: 'copy build from library for f-f tests'

  - task: CopyFiles@2
    inputs:
      SourceFolder: '$(System.ArtifactsDirectory)/SurveyJSLibraryBuild/build/survey-react-ui'
      Contents: '**'
      TargetFolder: '$(Build.SourcesDirectory)/survey-creator/packages/survey-creator-react/node_modules/survey-react-ui'
      OverWrite: true
    displayName: 'copy build from library for f-f tests'

  - powershell: |
      cd $(Build.SourcesDirectory)/survey-creator/packages/survey-creator-react
      npm run release
    displayName: 'Release specific version survey-creator-react'

  - script: |
      cd $(Build.SourcesDirectory)/survey-creator/packages/survey-creator-react
      npm run build
    displayName: 'Build CreatorV2 React'

  - script: |
      cd $(Build.SourcesDirectory)/survey-creator/packages/survey-creator-react
      npm run test
    displayName: 'Unit test CreatorV2 React'

  - script: |
      cd $(Build.SourcesDirectory)/survey-creator/packages/survey-creator-react
      npm run testcafe:ci
    displayName: 'Functional test CreatorV2 React'
    env:
      TESTCAFE_DASHBOARD_AUTHENTICATION_TOKEN: $(TESTCAFE_DASHBOARD_AUTHENTICATION_TOKEN_V2_REACT)
      TESTCAFE_DASHBOARD_URL: $(TESTCAFE_DASHBOARD_URL)


- job: CreatorV2Knockout
  dependsOn: CreatorV2Core
  steps:
  - checkout: self
  - checkout: Service
    persistCredentials: true
    clean: true

  - task: NodeTool@0
    inputs:
      versionSpec: '14.x'
    displayName: 'Install Node.js'

  - powershell: |
      $env:GIT_REDIRECT_STDERR = '2>&1'
      git config --global user.email "kurmanov.work@gmail.com"
      git config --global user.name "dmitrykurmanov"
    displayName: 'Set up git config'

  - task: DownloadBuildArtifacts@0
    inputs:
      buildType: 'specific'
      project: 'af2804d2-859a-4705-9ef5-cdf46d1d5d4f'
      pipeline: '56'
      specificBuildWithTriggering: true
      buildVersionToDownload: 'latest'
      downloadType: 'single'
      artifactName: 'SurveyJSLibraryBuild'
      downloadPath: '$(System.ArtifactsDirectory)'

  - task: DownloadBuildArtifacts@0
    inputs:
      buildType: 'current'
      downloadType: 'single'
      artifactName: 'SurveyJSCreatorV2BuildCore'
      downloadPath: '$(System.ArtifactsDirectory)'

  - task: CopyFiles@2
    inputs:
      SourceFolder: '$(System.ArtifactsDirectory)/SurveyJSLibraryBuild/packages'
      Contents: '**'
      TargetFolder: '$(Build.SourcesDirectory)/survey-library/build'
      OverWrite: true

  - task: CopyFiles@2
    inputs:
      SourceFolder: $(System.ArtifactsDirectory)/SurveyJSCreatorV2BuildCore
      TargetFolder: '$(Build.SourcesDirectory)/survey-creator/packages/survey-creator-core/build'

  - script: |
      cd $(Build.SourcesDirectory)/survey-creator/packages/survey-creator-knockout
      npm install
      npm run remove-package-lock
    displayName: 'Npm install survey-creator-knockout'

  - task: CopyFiles@2
    inputs:
      SourceFolder: '$(System.ArtifactsDirectory)/SurveyJSLibraryBuild/build/survey-core'
      Contents: '**'
      TargetFolder: '$(Build.SourcesDirectory)/survey-creator/packages/survey-creator-knockout/node_modules/survey-core'
      OverWrite: true
    displayName: 'copy build from library for f-f tests'

  - task: CopyFiles@2
    inputs:
      SourceFolder: '$(System.ArtifactsDirectory)/SurveyJSLibraryBuild/build/survey-knockout-ui'
      Contents: '**'
      TargetFolder: '$(Build.SourcesDirectory)/survey-creator/packages/survey-creator-knockout/node_modules/survey-knockout-ui'
      OverWrite: true
    displayName: 'copy build from library for f-f tests'

  - powershell: |
      cd $(Build.SourcesDirectory)/survey-creator/packages/survey-creator-knockout
      npm run release
    displayName: 'Release specific version survey-creator-knockout'

  - script: |
      cd $(Build.SourcesDirectory)/survey-creator/packages/survey-creator-knockout
      npm run build
    displayName: 'Build CreatorV2 Knockout'

  - script: |
      cd $(Build.SourcesDirectory)/survey-creator/packages/survey-creator-knockout
      npm run test
    displayName: 'Unit test CreatorV2 Knockout'

  - script: |
      cd $(Build.SourcesDirectory)/survey-creator/packages/survey-creator-knockout
      npm run testcafe:ci
    displayName: 'Functional test CreatorV2 Knockout'
    env:
      TESTCAFE_DASHBOARD_AUTHENTICATION_TOKEN: $(TESTCAFE_DASHBOARD_AUTHENTICATION_TOKEN_V2_KNOCKOUT)
      TESTCAFE_DASHBOARD_URL: $(TESTCAFE_DASHBOARD_URL)
