# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

resources:
  repositories:
    - repository: Service # The name used to reference this repository in the checkout step
      type: github
      endpoint: surveyjs
      name: surveyjs/service

trigger:
  batch: true
  branches:
    include:
    - master
  tags:
    exclude:
      - v*.*.*

pool:
  vmImage: 'Ubuntu-16.04'

steps:
- checkout: self
- checkout: Service
  persistCredentials: true
  clean: true

- task: NodeTool@0
  inputs:
    versionSpec: '14.x'
  displayName: 'Install Node.js'

- powershell: |
    $env:GIT_REDIRECT_STDERR = '2>&1'
    git config --global user.email "kurmanov.work@gmail.com"
    git config --global user.name "dmitrykurmanov"
  displayName: 'Set up git config'

- script: |
    cd $(Build.SourcesDirectory)/survey-creator/packages/survey-creator
    npm install
  displayName: 'Install npm'
  
- task: DownloadBuildArtifacts@0
  inputs:
    buildType: 'specific'
    project: 'af2804d2-859a-4705-9ef5-cdf46d1d5d4f'
    pipeline: '7'
    specificBuildWithTriggering: true
    buildVersionToDownload: 'latest'
    downloadType: 'single'
    artifactName: 'SurveyJSLibraryBuild'
    downloadPath: '$(System.ArtifactsDirectory)'

- task: CopyFiles@2
  inputs:
    SourceFolder: '$(System.ArtifactsDirectory)/SurveyJSLibraryBuild/packages'
    Contents: '**'
    TargetFolder: '$(Build.SourcesDirectory)/survey-library/build'
    OverWrite: true

- task: CopyFiles@2
  inputs:
    SourceFolder: '$(System.ArtifactsDirectory)/SurveyJSLibraryBuild/packages/survey-knockout'
    Contents: '**'
    TargetFolder: '$(Build.SourcesDirectory)/survey-creator/packages/survey-creator/node_modules/survey-knockout'
    OverWrite: true

# npm run release with version
- task: CopyFiles@2
  inputs:
    SourceFolder: '$(System.ArtifactsDirectory)/SurveyJSLibraryBuild/'
    Contents: 'version.txt'
    TargetFolder: '$(Build.SourcesDirectory)/'
    OverWrite: true
  displayName: 'Copy build artifact - SurveyJSVersion File'

- powershell: |
    $version = Get-Content $(Build.SourcesDirectory)/version.txt
    Write-Host "##vso[task.setvariable variable=SurveyJSVersion;]$version"
  displayName: 'Setup SurveyJSVersion variable from SurveyJSVersionFile'

- powershell: |
    cd $(Build.SourcesDirectory)/survey-creator/packages/survey-creator
    npm run release -- --release-as $(SurveyJSVersion)
  displayName: 'Release specific version'
#####################################################

- task: DownloadBuildArtifacts@0
  inputs:
    buildType: 'specific'
    project: 'af2804d2-859a-4705-9ef5-cdf46d1d5d4f'
    pipeline: '42'
    specificBuildWithTriggering: true
    buildVersionToDownload: 'latest'
    downloadType: 'single'
    artifactName: 'SurveyJSWidgetsBuild'
    downloadPath: '$(System.ArtifactsDirectory)'

- task: CopyFiles@2
  inputs:
    SourceFolder: '$(System.ArtifactsDirectory)/SurveyJSWidgetsBuild/packages/survey-widgets'
    Contents: '**'
    TargetFolder: '$(Build.SourcesDirectory)/survey-creator/packages/survey-creator/node_modules/surveyjs-widgets'
    OverWrite: true

# Creator CORE
- script: |
    cd $(Build.SourcesDirectory)/survey-creator/packages/survey-creator-core
    npm install
  displayName: 'Install npm'
  
- script: |
    cd $(Build.SourcesDirectory)/survey-creator/packages/survey-creator-core
    npm run build
  displayName: 'Build creator v2 core'

- script: |
    cd $(Build.SourcesDirectory)/survey-creator/packages/survey-creator-core
    npm run test
  displayName: 'Unit tests creator v2 core'
  
- task: CopyFiles@2
  inputs:
    SourceFolder: '$(Build.SourcesDirectory)/survey-creator/packages/survey-creator-core/build'
    targetFolder: $(Build.ArtifactStagingDirectory)/SurveyJSCreatorV2Build/build/survey-creator-core

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)/SurveyJSCreatorV2Build/build/survey-creator-core'
    ArtifactName: 'SurveyJSCreatorV2BuildCore'
    publishLocation: 'Container'  

# Creator REACT
- script: |
    cd $(Build.SourcesDirectory)/survey-creator/packages/survey-creator-react
    npm install
  displayName: 'Install npm'

- script: |
    cd $(Build.SourcesDirectory)/survey-creator/packages/survey-creator-react/node_modules/@types
    echo $(Build.SourcesDirectory)/survey-creator/packages/survey-creator-react/node_modules/@types
    ls
    cd $(Build.SourcesDirectory)/survey-creator/packages/survey-creator-react/node_modules/@types/react
    echo $(Build.SourcesDirectory)/survey-creator/packages/survey-creator-react/node_modules/@types/react
    ls
    cd $(Build.SourcesDirectory)/survey-creator/packages/survey-creator-react/node_modules/@types/react-dom
    echo $(Build.SourcesDirectory)/survey-creator/packages/survey-creator-react/node_modules/@types/react-dom
    ls
    cd $(Build.SourcesDirectory)/survey-library/build
    echo $(Build.SourcesDirectory)/survey-library/build
    ls
    cd $(Build.SourcesDirectory)/survey-library/build/survey-core
    echo $(Build.SourcesDirectory)/survey-library/build/survey-core
    ls
    cd $(Build.SourcesDirectory)/survey-library/build/survey-react-ui
    echo $(Build.SourcesDirectory)/survey-library/build/survey-react-ui
    ls
    cd $(Build.SourcesDirectory)/survey-creator/packages/survey-creator-react/node_modules/survey-core
    echo $(Build.SourcesDirectory)/survey-creator/packages/survey-creator-react/node_modules/survey-core
    ls
    cd $(Build.SourcesDirectory)/survey-creator/packages/survey-creator-react/node_modules/survey-react-ui
    echo $(Build.SourcesDirectory)/survey-creator/packages/survey-creator-react/node_modules/survey-react-ui
    ls
    cd $(Build.SourcesDirectory)/survey-creator/packages/survey-creator-react
    echo $(Build.SourcesDirectory)/survey-creator/packages/survey-creator-react
    ls
  displayName: 'Pre-debug survey-creator-react build'

- script: |
    cd $(Build.SourcesDirectory)/survey-creator/packages/survey-creator-react
    npm run build
  displayName: 'Build creator v2 react'

- script: |
    cd $(Build.SourcesDirectory)/survey-creator/packages/survey-creator-react
    npm run test
  displayName: 'Unit tests creator v2 react'

- script: |
    cd $(Build.SourcesDirectory)/survey-creator/packages/survey-creator-react
    npm run testcafe:ci
  displayName: 'Functional tests creator v2 react'

- task: CopyFiles@2
  inputs:
    SourceFolder: '$(Build.SourcesDirectory)/survey-creator/packages/survey-creator-react/build'
    targetFolder: $(Build.ArtifactStagingDirectory)/SurveyJSCreatorV2Build/build/survey-creator-react

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)/SurveyJSCreatorV2Build/build/survey-creator-react'
    ArtifactName: 'SurveyJSCreatorV2BuildReact'
    publishLocation: 'Container'  
    

# Creator KNOCKOUT
- script: |
    cd $(Build.SourcesDirectory)/survey-creator/packages/survey-creator-knockout
    npm install
  displayName: 'Install npm'

- script: |
    cd $(Build.SourcesDirectory)/survey-creator/packages/survey-creator-knockout
    npm run build
  displayName: 'Build creator v2 knockout'

- script: |
    cd $(Build.SourcesDirectory)/survey-creator/packages/survey-creator-knockout
    npm run test
  displayName: 'Unit tests creator v2 knockout'

- script: |
    cd $(Build.SourcesDirectory)/survey-creator/packages/survey-creator-knockout
    npm run testcafe:ci
  displayName: 'Functional tests creator v2 knockout'

- task: CopyFiles@2
  inputs:
    SourceFolder: '$(Build.SourcesDirectory)/survey-creator/packages/survey-creator-knockout/build'
    targetFolder: $(Build.ArtifactStagingDirectory)/SurveyJSCreatorV2Build/build/survey-creator-knockout

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)/SurveyJSCreatorV2Build/build/survey-creator-knockout'
    ArtifactName: 'SurveyJSCreatorV2BuildKnockout'
    publishLocation: 'Container'  

# Creator V1
- script: |
    cd $(Build.SourcesDirectory)/survey-creator/packages/survey-creator
    npm run build_prod
  displayName: 'Build prod'

- script: |
    cd $(Build.SourcesDirectory)/survey-creator/packages/survey-creator
    npm run test_ci
  displayName: 'Unit tests'

- script: |
    cd $(Build.SourcesDirectory)/survey-creator/packages/survey-creator
    npm run testcafe_ci
  displayName: 'Functional tests'

- script: |
    mkdir $(Build.SourcesDirectory)/survey-creator/packages/survey-creator/docs
    cd $(Build.SourcesDirectory)/survey-creator/packages/survey-creator
    npm run doc_gen
  displayName: 'Generate docs'

- task: CopyFiles@2
  inputs:
    SourceFolder: '$(Build.SourcesDirectory)/survey-creator/docs'
    TargetFolder: '$(Build.SourcesDirectory)/service/surveyjs.io/App_Data/DocsEditor'
    CleanTargetFolder: true
  displayName: 'Copy root docs to the local surveyjs/service repo'

- task: CopyFiles@2
  inputs:
    SourceFolder: '$(Build.SourcesDirectory)/survey-creator/packages/survey-creator/docs'
    TargetFolder: '$(Build.SourcesDirectory)/service/surveyjs.io/App_Data/DocsEditor'
    CleanTargetFolder: false
  displayName: 'Copy generated docs to the local surveyjs/service repo'

# read about the problem with git output ($env:GIT_REDIRECT_STDERR = '2>&1') :
# https://github.com/microsoft/azure-pipelines-yaml/issues/248
# https://stackoverflow.com/questions/58485585/azure-pipeline-powershell-and-git-on-windows-server-2019-gives-error-in-output
- powershell: |
    cd $(Build.SourcesDirectory)/service
    git checkout master
    git pull origin master
    git fetch --tags --force
    git add surveyjs.io/App_Data/DocsEditor
    git reset -- surveyjs.io/App_Data/DocsEditor/images
    git commit -m "[skip ci] Updated survey-creator docs"
    git pull origin master
    git push origin master
  displayName: 'Git surveyjs/service push updated docs'

- task: CopyFiles@2
  inputs:
    SourceFolder: '$(Build.SourcesDirectory)/survey-creator/packages/survey-creator/build'
    targetFolder: $(Build.ArtifactStagingDirectory)/SurveyJSCreatorBuild/build

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)/SurveyJSCreatorBuild/'
    ArtifactName: 'SurveyJSCreatorBuild'
    publishLocation: 'Container'