//There 223 untranslated keys. You can find them in uncommented lines.
import { editorLocalization, defaultStrings } from "survey-creator-core";

export var arStrings = {
  // survey templates
  survey: {
    edit: "تعديل",
    externalHelpLink: "شاهد وتعلم كيف يتم إنشاء إستبيان",
    externalHelpLinkUrl: "https://www.youtube.com/channel/UCH2ru9okIcooNZfpIbyq4qQ?view_as=subscriber",
    dropQuestion: "الرجاء إفلات السؤال هنا من صندوق الأدوات",
    addLogicItem: ".قم بإنشاء قاعدة لتخصيص تدفق الإستبيان",
    copy: "نسخ",
    duplicate: "نسخة طبق الأصل",
    addToToolbox: "إضافة إلى صندوق الأدوات",
    deletePanel: "حذف لوحة",
    deleteQuestion: "حذف سؤال",
    convertTo: "تحويل إلى",
    drag: "إسحب العنصر"
  },
  // Question types
  qt: {
    default: "الإفتراضي",
    checkbox: "إختيار من متعدد",
    comment: "تعليق",
    imagepicker: "إنتقاء الصور",
    ranking: "تصنيف",
    image: "صورة",
    dropdown: "قائمة منسدلة",
    //tagbox: "Tag Box",
    file: "ملف",
    html: "لغة ترميز النصوص HTML",
    matrix: "مصفوفة (إختيار واحد)",
    matrixdropdown: "مصفوفة (إختيار متعدد)",
    matrixdynamic: "مصفوفة (صفوف ديناميكية)",
    multipletext: "مدخل متعدد",
    panel: "لوحة",
    paneldynamic: "لوحة ديناميكية",
    radiogroup: "إختيار فردي",
    rating: "تقييم",
    text: "مٌدخل فردي",
    boolean: "قيمة منطقية",
    expression: "عملية حسابية (للقرائة فقط)",
    signaturepad: "لوحة توقيع",
    buttongroup: "Button group"
  },
  // Strings in SurveyJS Creator
  ed: {
    defaultLocale: "إفتراضي ({0})",
    survey: "Survey1",
    settings: "Survey Settings",
    settingsTooltip: "Open survey settings",
    //surveySettings: "Survey Settings",
    //surveySettingsTooltip: "Open survey settings",
    showPanel: "إظهار اللوحة",
    hidePanel: "إخفاء اللوحة",
    prevSelected: "Select previous",
    nextSelected: "Select next",
    surveyTypeName: "الإستبيان",
    pageTypeName: "الصفحة",
    panelTypeName: "اللوحة",
    questionTypeName: "السؤال",
    columnTypeName: "Column",
    addNewPage: "Add New Page",
    moveRight: "Scroll to the Right",
    moveLeft: "Scroll to the Left",
    deletePage: "Delete Page",
    editPage: "Edit Page",
    edit: "التعديل",
    newPageName: "الصفحة",
    newQuestionName: "السؤال",
    newPanelName: "اللوحة",
    newTextItemName: "text",
    testSurvey: "تجربة الإستبيان",
    //defaultV2Theme: "Default",
    //modernTheme: "Modern",
    //defaultTheme: "Default (legacy)",
    testSurveyAgain: "Test Survey Again",
    testSurveyWidth: "Survey width: ",
    navigateToMsg: "You had to navigate to:",
    logic: "منطق الإستبيان",
    embedSurvey: "Embed Survey",
    translation: "Translation",
    saveSurvey: "Save Survey",
    saveSurveyTooltip: "Save Survey",
    designer: "تصميم الإستبيان",
    jsonEditor: "JSON Editor",
    jsonHideErrors: "Hide errors",
    jsonShowErrors: "Show errors",
    undo: "Undo",
    redo: "Redo",
    undoTooltip: "Undo last change",
    redoTooltip: "Redo the change",
    //showMoreChoices: "Show more",
    //showLessChoices: "Show less",
    copy: "Copy",
    cut: "Cut",
    paste: "Paste",
    copyTooltip: "Copy selection to clipboard",
    cutTooltip: "Cut selection to clipboard",
    pasteTooltip: "Paste from clipboard",
    options: "Options",
    generateValidJSON: "Generate Valid JSON",
    generateReadableJSON: "Generate Readable JSON",
    toolbox: "Toolbox",
    "property-grid": "Properties",
    propertyGridFilteredTextPlaceholder: "Type to search...",
    toolboxGeneralCategory: "قائمة العام",
    //toolboxChoiceCategory: "Choice Questions",
    //toolboxTextCategory: "Text Input Questions",
    //toolboxContainersCategory: "Containers",
    //toolboxMatrixCategory: "Matrix Questions",
    //toolboxMiscCategory: "Misc",
    correctJSON: "Please correct JSON.",
    surveyResults: "Survey Results ",
    surveyResultsTable: "As Table",
    surveyResultsJson: "As JSON",
    resultsTitle: "Question Title",
    resultsName: "Question Name",
    resultsValue: "Answer Value",
    resultsDisplayValue: "Display Value",
    modified: "هناك تعديل جديد",
    saving: "يتم الآن حفظ التغييرات",
    saved: "تم الحفظ",
    propertyEditorError: "خطأ:",
    saveError: "Error! Editor content is not saved.",
    translationPropertyGridTitle: "Language Settings",
    translationLanguages: "Languages",
    translationAddLanguage: "Select language to translate",
    translationShowAllStrings: "Show all strings",
    //translationShowUsedStringsOnly: "Used Strings Only",
    translationShowAllPages: "Show all pages",
    translationNoStrings: "No strings to translate. Please, change the filter.",
    translationExportToSCVButton: "Export to CSV",
    translationImportFromSCVButton: "Import from CSV",
    translationMergeLocaleWithDefault: "Merge {0} with default locale",
    translationPlaceHolder: "Translation...",
    bold: "Bold",
    italic: "Italic",
    underline: "Underline",
    addNewQuestion: "Add Question",
    selectPage: "Select page...",
    htmlPlaceHolder: "محتوى HTML سيكون هنا",
    panelPlaceHolder: "قم بإسقاط السؤال من صندوق الأدوات إلى هنا",
    //surveyPlaceHolder: "The survey is empty. Drag an element from the toolbox or click the button below.",
    addNewTypeQuestion: "Add {0}", //{0} is localizable question type
    chooseLogoPlaceholder: "[الشعار]",
    lg: {
      //addNewItem: "Add New Rule",
      empty_tab: "قم بإنشاء إرتباط لتخصيص تدفق الإستبيان",
      page_visibilityName: "إظهار (إخفاء) صفحة",
      //page_enableName: "Enable (disable) page",
      panel_visibilityName: "إظهار (إخفاء) لوحة",
      panel_enableName: "تفعيل (تعطيل) لوحة",
      question_visibilityName: "إظهار (إخفاء) سؤال",
      question_enableName: "تفعيل (تعطيل) سؤال",
      question_requireName: "جعل السؤال إلزامي",
      //column_visibilityName: "Show (hide) column",
      //column_enableName: "Enable (disable) column",
      //column_requireName: "Make column required",
      trigger_completeName: "أنهي الإستبيان",
      trigger_setvalueName: "تحديد قيمة السؤال",
      trigger_copyvalueName: "نسخ قيمة السؤال",
      trigger_skipName: "التخطي إلى السؤال",
      trigger_runExpressionName: "تشغيل تعبير رياضي مخصص",
      completedHtmlOnConditionName: "نص رسالة شكر مخصصة",
      page_visibilityDescription: "Make the page visible when the logic expression returns true. Otherwise keep it invisible.",
      panel_visibilityDescription: "Make the panel visible when the logic expression returns true. Otherwise keep it invisible.",
      panel_enableDescription: "Make the panel, and all elements inside it, enable when the logic expression returns true. Otherwise keep them disabled.",
      question_visibilityDescription: "Make the question visible when the logic expression returns true. Otherwise keep it invisible.",
      question_enableDescription: "Make the question enable when the logic expression returns true. Otherwise keep it disabled.",
      question_requireDescription: "Question becomes required when the logic expression returns true.",
      trigger_completeDescription: "When the logic expression returns true then the survey becomes completed and an end-user see the 'Thank you page'.",
      trigger_setvalueDescription: "When question values, that are used in the logic expression, are changed and the logic expression returns true, then the value is set to the selected question.",
      trigger_copyvalueDescription: "When question values, that are used in the logic expression, are changed and the logic expression returns true, then the value of one selected question is copied to another selected question.",
      trigger_skipDescription: "When the logic expression returns true then the survey skip to / focus the selected question.",
      trigger_runExpressionDescription: "When the logic expression returns true, then the custom expression is performed. You may optionally set this expression result into the selected question",
      completedHtmlOnConditionDescription: "If the logic expression returns true, then the default text for the 'Thank you page' is changed to the given one.",
      itemExpressionText: "عندما التعبير '{0}' رجع قيمة المنطقية صحيح", //{0} - the expression
      itemEmptyExpressionText: "الإرتباط الجديد لم يحدد",
      page_visibilityText: "جعل الصفحة {0} مرئية", //{0} page name
      panel_visibilityText: "جعل اللوحة {0} مرئية", //{0} panel name
      panel_enableText: "جعل اللوحة {0} مفعلة", //{0} panel name
      question_visibilityText: "جعل السؤال {0} مرئي", //{0} question name
      question_enableText: "جعل السؤال {0} مفعل", //{0} question name
      question_requireText: "جعل السؤال {0} إلزامي", //{0} question name
      //column_visibilityText: "make column {0} of question {1} visible", //{0} column name, {1} question name
      //column_enableText: "make column {0} of question {1} enable", //{0} column name, {1} question name
      //column_requireText: "make column {0} of question {1} required", //{0} column name, {1} question name
      trigger_completeText: "الإستبيان سيصبح مكتمل",
      trigger_setvalueText: "تثبيت إلى السؤال: {0} القيمة {1}", //{0} question name, {1} setValue
      trigger_copyvalueText: "النسخ إلى السؤال: {0} القيمة القادمة من السؤال {1}", //{0} and {1} question names
      trigger_skipText: "التخطي إلى السؤال {0}", //{0} question name
      trigger_runExpressionText1: "شغل التعبير الرياضي '{0}'", //{0} the expression
      trigger_runExpressionText2: " وثبت نتيجتها إلى السؤال {0}", //{0} question name
      completedHtmlOnConditionText: "عرض نص رسال 'صفحة شكر' مخصصة",
      showAllQuestions: "عرض كل الأسئلة",
      showAllActionTypes: "عرض كل أنواع الإجراءات",
      conditions: "Condition(s)",
      actions: "Action(s)",
      expressionEditorTitle: "تعريف شرط(إشتراطات)",
      actionsEditorTitle: "تعريف إجراء (إجراءات)",
      deleteAction: "حذف الإجراء",
      addNewAction: "إضافة إجراء جديد",
      selectedActionCaption: "حدد الإجراء لأضافته",
      expressionInvalid: "التعبير المنطقي الرياضي فارغ أو غير صحيح، يرجى تصحيحه",
      noActionError: "الرجاء، إضافة إجراء واحد على الأقل",
      actionInvalid: "الرجاء، إصلاح الأخطاء في الإجراء التابع لك",
      //expressionSetup: "",
      //actionsSetup: ""
    }
  },
  // Property Editors
  pe: {
    apply: "تطبيق",
    ok: "موافق",
    save: "حفظ",
    clear: "مسح",
    saveTooltip: "حفظ",
    cancel: "إلغاء",
    set: "تثبيت",
    reset: "Reset",
    change: "تغيير",
    refresh: "Refresh",
    close: "إغلاق",
    delete: "حذف",
    add: "إضافة",
    addNew: "إضافة إرتباط جديد",
    addItem: "Click to add an item...",
    removeItem: "Click to remove the item...",
    dragItem: "Drag the item",
    addOther: "Other",
    addSelectAll: "Select All",
    addNone: "None",
    removeAll: "Remove All",
    edit: "التعديل",
    back: "Return without saving",
    backTooltip: "Return without saving",
    saveAndBack: "Save and return",
    saveAndBackTooltip: "Save and return",
    doneEditing: "إضافة",
    editChoices: "Edit Choices",
    showChoices: "Show Choices",
    move: "Move",
    empty: "<empty>",
    emptyValue: "القيمة فارغة",
    fastEntry: "إدخالات سريعة",
    fastEntryNonUniqueError: "Value '{0}' is not unique",
    fastEntryChoicesCountError: "Please limit the number of items from {0} to {1}",
    //fastEntryPlaceholder: "You can set data in the following format:\nvalue1|text\nvalue2",
    formEntry: "Form Entry",
    testService: "Test the service",
    itemSelectorEmpty: "Please select the element",
    conditionActionEmpty: "Please select the action",
    conditionSelectQuestion: "إختر السؤال...",
    conditionSelectPage: "Select page...",
    conditionSelectPanel: "Select panel...",
    conditionValueQuestionTitle: "Please enter/select the value",
    expressionHelp: "You can use curly brackets to get access to the question values: {question1} + {question2}, ({price}*{quantity}) * (100 - {discount}). You can use functions as: iif(), today(), age(), min(), max(), count(), avg() and others.",
    aceEditorHelp: "Press ctrl+space to get expression completion hint",
    aceEditorRowTitle: "Current row",
    aceEditorPanelTitle: "Current panel",
    showMore: "For more details please check the documentation",
    assistantTitle: "Available questions:",
    cellsEmptyRowsColumns: "There is should be at least one column or row",
    //showPreviewBeforeComplete: "Preview answers before submitting the survey",
    propertyIsEmpty: "Please enter a value",
    propertyIsNoUnique: "Please enter a unique value",
    propertyNameIsNotUnique: "Please enter a unique name",
    listIsEmpty: "No items have been added yet",
    //"listIsEmpty@choices": "No choices have been added yet",
    //"addNew@choices": "Add a choice",
    expressionIsEmpty: "Expression is empty",
    value: "القيمة",
    text: "النص",
    rowid: "Row ID",
    imageLink: "رابط الصورة",
    columnEdit: "Edit column: {0}",
    itemEdit: "Edit item: {0}",
    url: "رابط إلكتروني URL",
    path: "المسار",
    valueName: "اسم القيمة",
    choicesbyurl: {
      //valueName: "Get values from the following JSON field"
    },
    titleName: "اسم العنوان",
    imageLinkName: "اسم رابط الصورة",
    allowEmptyResponse: "السماح بجواب فارغ",
    titlePlaceholder: "Input title here",
    surveyTitlePlaceholder: "أدخل عنوان الإستبيان هنا",
    pageTitlePlaceholder: "أدخل عنوان الصفحة هنا",
    descriptionPlaceholder: "Enter a description",
    surveyDescriptionPlaceholder: "أدخل وصف للإستبيان",
    pageDescriptionPlaceholder: "أدخل وصف للصفحة",
    showOtherItem: "هل هناك خيار أخرى",
    otherText: "نص خيار أخرى",
    showNoneItem: "هل هناك خيار بلا",
    noneText: "نص خيار بلا",
    showSelectAllItem: "هل هناك خيار إختيار الكل",
    selectAllText: "نص خيار إختر الكل",
    choicesMin: "Minimum value for auto generated items",
    choicesMax: "Maximum value for auto generated items",
    choicesStep: "The difference between auto generated items",
    name: "الإسم",
    title: "العنوان",
    cellType: "نوع الخلية",
    colCount: "عدد الأعمدة",
    choicesOrder: "إختر ترتيب الإختيارات",
    visible: "مرئي؟",
    isRequired: "مطلوب؟",
    isAllRowRequired: "المطالبة بالأجوبة لكل الصفوف",
    requiredErrorText: "نص خطأ إلزامي السؤال",
    startWithNewLine: "إظهار السؤال في صف جديد",
    rows: "عدد الصفوف",
    cols: "عدد الأعمدة",
    placeholder: "نص حامل خانة الإدخال",
    showPreview: "عرض منطقة المعاينة",
    storeDataAsText: "تخزين محتويات ملف JSON كنص",
    maxSize: "أقصى حجم للملف بالبايت",
    imageHeight: "طول الصورة",
    imageWidth: "عرض الصورة",
    rowCount: "عدد الصفوف",
    columnLayout: "تخطيط الأعمدة",
    addRowLocation: "موقع زر إضافة صف",
    addRowText: "نص زر إضافة صف",
    removeRowText: "نص زر حذف صف",
    rateMin: "أصغر معدل",
    rateMax: "أكبر معدل",
    rateStep: "خطوات المعدل",
    minRateDescription: "وصف أصغر معدل",
    maxRateDescription: "وصف أكبر معدل",
    inputType: "نوع المدخل",
    optionsCaption: "خيارات الشرح",
    defaultValue: "القيمة الإفتراضية",
    cellsDefaultRow: "Default cells texts",
    surveyEditorTitle: "Edit survey settings",
    qEditorTitle: "Edit: {0}",
    maxLength: "أقصى طول",
    buildExpression: "Build",
    editExpression: "التعديل",
    remove: "إزالة",
    addCondition: "أضف الشرط",
    //emptyLogicPopupMessage: "Select a question to start configuring conditions.",
    if: "إذا قيمة",
    setToName: "إلى",
    fromName: "from",
    //gotoName: "Question to skip to",
    ruleIsNotSet: "Rule is incorrect",
    //includeIntoResult: "Include into survey results",
    showTitle: "إظهار/إخفاء العنوان",
    expandCollapseTitle: "Expand/collapse title",
    locale: "اللغة الإفتراضية",
    simulator: "Choose device",
    landscapeOrientation: "Landscape",
    portraitOrientation: "Portrait",
    mode: "النمط (التعديل، القرائة فقط)",
    clearInvisibleValues: "إمسح القيم الغير مرئية",
    cookieName: "أدخل إسم ملف تعريف الإرتباط (لتعطيل المشاركة بالإستبيان أكثر من مرة)",
    sendResultOnPageNext: "إرسال نتائج الإستبيان على الصفحة التالية",
    storeOthersAsComment: "تخزين قيمة 'أخرى' في حقل منفصل",
    showPageTitles: "عرض عنوان الصفحات",
    showPageNumbers: "عرض أرقام الصفحات",
    pagePrevText: "نص زر الإنتقال للصفحة السابقة",
    pageNextText: "نص زر الإنتقال للصفحة التالية",
    completeText: "نص زر إنهاء الإستبيان",
    previewText: "نص زر المعاينة",
    editText: "نص زر التعديل",
    startSurveyText: "نص زر بدء المشاركة بالإستبيان",
    showNavigationButtons: "إظهار أزرار الإنتقال (التنقل الإفتراضي)",
    showPrevButton: "إظهار زر التنقل السابق (السماح للمستخدم من العودة للصفحة السابقة في الإستبيان)",
    firstPageIsStarted: "الصفحة الأولى في الإستبيان هي صفحة البدء",
    showCompletedPage: "إظهار الصفحة المكتملة في النهاية (صفحة ويب مكتملة)",
    goNextPageAutomatic: "عند الإجابة على جميع الأسئلة، إنتقل إلى الصفحة التالية تلقائياً",
    showProgressBar: "إظهار شريط التقدم",
    questionTitleLocation: "موقع عنوان السؤال",
    requiredText: "رمز السؤال مطلوب",
    questionStartIndex: "فهرس بداية الأسئلة (1،2 أو 'أ' ، 'ب')",
    showQuestionNumbers: "إظهار أرقام الأسئلة",
    questionTitleTemplate: "Question title template, default is: '{no}. {require} {title}'",
    questionErrorLocation: "موقع خطأ في السؤال",
    focusFirstQuestionAutomatic: "ركز المؤشر على السؤال الأول عند تغير الصفحة",
    questionsOrder: "ترتيب العناصر على الصفحة",
    maxTimeToFinish: "أقصى وقت لإنهاء الإستبيان",
    maxTimeToFinishPage: "أقصى وقت لإنهاء الصفحة في الإستبيان",
    page: {
      //maxTimeToFinish: "Time limit to finish the page (in seconds)"
    },
    question: {
      //page: "Parent page"
    },
    showTimerPanel: "إظهار لوحة المؤقت",
    showTimerPanelMode: "إظهار نمط لوحة المؤقت",
    renderMode: "نمط العرض",
    allowAddPanel: "السماح بإضافة لوحة",
    allowRemovePanel: "السماح بإزالة لوحة",
    //noEntriesText: "Empty entries text",
    panelAddText: "نص إضافة لوحة",
    panelRemoveText: "نص إزالة لوحة",
    isSinglePage: "Show all elements on one page",
    html: "صفحة ويب HTML",
    expression: "عملية حسابية",
    //setValue: "Answer",
    //dataFormat: "Image format",
    //allowAddRows: "Allow adding rows",
    //allowRemoveRows: "Allow removing rows",
    //allowRowsDragAndDrop: "Allow row drag and drop",
    //responsiveImageSizeHelp: "Does not apply if you specify the exact image width or height.",
    //minImageWidth: "Minimum image width",
    //maxImageWidth: "Maximum image width",
    //minImageHeight: "Minimum image height",
    //maxImageHeight: "Maximum image height",
    minValue: "أقل قيمة",
    maxValue: "أكبر قيمة",
    minLength: "Minimum length",
    allowDigits: "Allow digits",
    minCount: "Minimum count",
    maxCount: "Maximum count",
    regex: "Regular expression",
    surveyvalidator: {
      //text: "Error message",
      //expression: "Validation expression"
    },
    totalText: "Total text",
    totalType: "Total type",
    totalExpression: "Total expression",
    totalDisplayStyle: "Total display style",
    totalCurrency: "Total currency",
    totalFormat: "Total format",
    //logo: "Logo (URL or base64-encoded string)",
    //questionsOnPageMode: "Survey structure",
    //maxTextLength: "Maximum answer length (in characters)",
    //maxOthersLength: "Maximum comment length (in characters)",
    //autoGrowComment: "Auto-expand comment area if necessary",
    //textUpdateMode: "Update text question value",
    //focusOnFirstError: "Set focus on the first invalid answer",
    //checkErrorsMode: "Run validation",
    //navigateToUrl: "Navigate to URL",
    //navigateToUrlOnCondition: "Dynamic URL",
    //completedBeforeHtml: "Markup to show if the user already filled out this survey",
    //completedHtml: "Survey Complete page markup",
    //completedHtmlOnCondition: "Dynamic Survey Complete page markup",
    //loadingHtml: "Markup to show while survey model is loading",
    //commentText: "Comment area text",
    //autocomplete: "Autocomplete type",
    //labelTrue: "\"True\" label",
    //labelFalse: "\"False\" label",
    allowClear: "Show options caption",
    //displayStyle: "Value display style",
    //format: "Formatted string",
    //maximumFractionDigits: "Maximum fractional digits",
    //minimumFractionDigits: "Minimum fractional digits",
    //useGrouping: "Display grouping separators",
    //allowMultiple: "Allow multiple files",
    //allowImagesPreview: "Preview images",
    //acceptedTypes: "Accepted file types",
    //waitForUpload: "Wait for the upload to complete",
    //needConfirmRemoveFile: "Confirm file deletion",
    //detailPanelMode: "Detail panel location",
    //minRowCount: "Minimum row count",
    //maxRowCount: "Maximum row count",
    //confirmDelete: "Confirm row deletion",
    //confirmDeleteText: "Confirmation message",
    paneldynamic: {
      //confirmDelete: "Confirm panel deletion"
    },
    //panelCount: "Initial panel count",
    //minPanelCount: "Minimum panel count",
    //maxPanelCount: "Maximum panel count",
    //panelsState: "Inner panel expand state",
    //templateDescription: "Description template",
    //templateTitle: "Title template",
    //panelPrevText: "Previous Panel button tooltip",
    //panelNextText: "Next Panel button tooltip",
    //showRangeInProgress: "Show progress bar",
    //templateTitleLocation: "Question title location",
    //panelRemoveButtonLocation: "Remove Panel button location",
    //hideIfRowsEmpty: "Hide the question if there are no rows",
    //hideColumnsIfEmpty: "Hide columns if there are no rows",
    //rateValues: "Custom rate values",
    //hideIfChoicesEmpty: "Hide the question if it contains no choices",
    //hideNumber: "Hide question number",
    //minWidth: "Minimum width (in CSS-accepted values)",
    //maxWidth: "Maximum width (in CSS-accepted values)",
    //width: "Width (in CSS-accepted values)",
    //showHeader: "Show column headers",
    //horizontalScroll: "Show horizontal scrollbar",
    //columnMinWidth: "Minimum column width (in CSS-accepted values)",
    //rowTitleWidth: "Row header width (in CSS-accepted values)",
    //valueTrue: "\"True\" value",
    //valueFalse: "\"False\" value",
    //minErrorText: "\"Value is below minimum\" error message",
    //maxErrorText: "\"Value exceeds maximum\" error message",
    //otherErrorText: "\"Empty comment\" error message",
    //keyDuplicationError: "\"Non-unique key value\" error message",
    //maxSelectedChoices: "Maximum selected choices",
    //showClearButton: "Show the Clear button",
    //showNumber: "Show panel number",
    //logoWidth: "Logo width (in CSS-accepted values)",
    //logoHeight: "Logo height (in CSS-accepted values)",
    //readOnly: "Read-only",
    //enableIf: "Editable if",
    //emptyRowsText: "\"No rows\" message",
    //size: "Input size (in characters)",
    //separateSpecialChoices: "Separate special choices (None, Other, Select All)",
    //choicesFromQuestion: "Copy choices from the following question",
    //choicesFromQuestionMode: "Which choices to copy?",
    //showCommentArea: "Show the comment area",
    //commentPlaceholder: "Comment area placeholder",
    //displayRateDescriptionsAsExtremeItems: "Display rate descriptions as extreme values",
    //rowsOrder: "Row order",
    //columnsLayout: "Column layout",
    //columnColCount: "Nested column count",
    //state: "Panel expand state",
    //correctAnswer: "Correct Answer",
    //defaultPanelValue: "Default Values",
    //cells: "Cell Texts",
    //keyName: "Key column",
    itemvalue: {
      //text: "Alt text"
    },
    logoPosition: "Logo position",
    addLogo: "Add logo...",
    changeLogo: "Change logo...",
    logoPositions: {
      none: "حذف الشعار",
      left: "يسار",
      right: "يمين",
      top: "في الأعلى",
      bottom: "في الأسفل"
    },
    tabs: {
      general: "عام",
      fileOptions: "الخيارات",
      html: "Html Editor",
      columns: "الأعمدة",
      rows: "الصفوف",
      choices: "الخيارات",
      items: "العناصر",
      visibleIf: "مرئي عندما",
      enableIf: "مفعل عندما",
      requiredIf: "مطلوب عندما",
      rateValues: "قيم التقييم",
      choicesByUrl: "خيارات من الإنترنت",
      matrixChoices: "Default Choices",
      multipleTextItems: "Text Inputs",
      numbering: "الترقيم",
      validators: "المدققات",
      navigation: "التنقل",
      question: "السؤال",
      pages: "الصفحات",
      timer: "مؤقت/إختبار قصير",
      calculatedValues: "Calculated Values",
      triggers: "Triggers",
      templateTitle: "عنوان القالب",
      totals: "Totals",
      logic: "المنطق",
      layout: "التنسيق",
      data: "البيانات",
      validation: "التحقق",
      cells: "الخلايا",
      showOnCompleted: "عند الإنتهاء من الإستبيان",
      logo: "الشعار في عنوان الإستبيان",
      slider: "Slider",
      //expression: "Expression",
      others: "غير ذلك"
    },
    editProperty: "Edit property '{0}'",
    items: "Items",
    //choicesVisibleIf: "Choices are visible if",
    //choicesEnableIf: "Choices are selectable if",
    //columnsEnableIf: "Columns are visible if",
    //rowsEnableIf: "Rows are visible if",
    //indent: "Add indents",
    panel: {
      //indent: "Add outer indents"
    },
    //innerIndent: "Add inner indents",
    //defaultValueFromLastRow: "Take default values from the last row",
    //defaultValueFromLastPanel: "Take default values from the last panel",
    enterNewValue: "Please, enter the value.",
    noquestions: "There is no any question in the survey.",
    createtrigger: "Please create a trigger",
    titleKeyboardAdornerTip: "Press enter button to edit",
    keyboardAdornerTip: "Press enter button to edit item, press delete button to delete item, press alt plus arrow up or arrow down to move item",
    triggerOn: "On ",
    triggerMakePagesVisible: "Make pages visible:",
    triggerMakeQuestionsVisible: "Make elements visible:",
    triggerCompleteText: "Complete the survey if succeed.",
    triggerNotSet: "The trigger is not set",
    triggerRunIf: "Run if",
    triggerSetToName: "Change value of: ",
    triggerFromName: "Copy value from: ",
    triggerRunExpression: "Run this Expression:",
    triggerSetValue: "to: ",
    triggerGotoName: "Go to the question:",
    triggerIsVariable: "Do not put the variable into the survey result.",
    triggerRunExpressionEmpty: "Please enter a valid expression",
    //emptyExpressionPlaceHolder: "Type expression here...",
    noFile: "No file choosen",
    //clearIfInvisible: "Clear the value if the question becomes hidden",
    //valuePropertyName: "Value property name",
    //searchEnabled: "Enable search",
    //hideSelectedItems: "Hide selected items",
    //signatureWidth: "Signature width",
    //signatureHeight: "Signature height",
    //verticalAlign: "Vertical alignment",
    //alternateRows: "Alternate rows",
    //columnsVisibleIf: "Columns are visible if",
    //rowsVisibleIf: "Rows are visible if",
    //otherPlaceholder: "Comment area placeholder"
  },
  // Property values
  pv: {
    inherit: "يَرث",
    show: "إظهار",
    hide: "إخفاء",
    default: "الإفتراضي",
    initial: "مبدئي",
    random: "عشوائي",
    collapsed: "مقلص",
    expanded: "موسع",
    none: "بلا",
    asc: "تصاعدي",
    desc: "تنازلي",
    indeterminate: "غير محدد",
    firstExpanded: "توسيع أول لوح",
    off: "إيقاف",
    //onpanel: "Start on each panel",
    onPanel: "على اللوحة",
    onSurvey: "على الإستبيان",
    list: "قائمة",
    progressTop: "التقدم بالأعلى",
    progressBottom: "التقدم بالأسف",
    progressTopBottom: "التقدم بالأعلى والأسفل معاً",
    horizontal: "عرضي",
    vertical: "عمودي",
    top: "الأعلى",
    bottom: "الأسفل",
    topBottom: "الاعلى والأسفل",
    both: "الكل",
    left: "يسار",
    right: "يمين",
    hidden: "مخفي",
    on: "تشغيل",
    onPage: "على الصفحة",
    edit: "التعديل",
    display: "العرض",
    onComplete: "عند الإنتهاء",
    onHidden: "عند الإخفال",
    onHiddenContainer: "عند إخفاء الحاوية",
    clearInvisibleValues: {
      //none: "Never"
    },
    all: "الكل",
    page: "الصفحة",
    survey: "الإستبيان",
    onNextPage: "عند الإنتقال للصفحة التالية",
    onValueChanged: "إذا تغيرت القيمة",
    onValueChanging: "عند تغيير القيمة",
    standard: "أساسي",
    singlePage: "صفحة واحدة",
    questionPerPage: "سؤال لكل صفحة",
    noPreview: "بلا عرض",
    showAllQuestions: "المعاينة مع جميع الأسئلة",
    showAnsweredQuestions: "المعاينة مع الأسئلة المجٌابة",
    pages: "الصفحات",
    questions: "الأسئلة",
    requiredQuestions: "الأسئلة المطلوبة",
    correctQuestions: "الإجابات الصحيحة",
    buttons: "الأزرار",
    underInput: "أسفل خانة الإدخال",
    underTitle: "أعلى العنوان",
    onBlur: "عند الطمس",
    onTyping: "عند الكتابة",
    //underRow: "Under the row",
    //underRowSingle: "Under the row, only one panel is visible",
    showNavigationButtons: {
      //none: "Hidden"
    },
    showProgressBar: {
      //off: "Hidden"
    },
    showTimerPanel: {
      //none: "Hidden"
    },
    showTimerPanelMode: {
      //all: "Both"
    },
    detailPanelMode: {
      //none: "Hidden"
    },
    addRowLocation: {
      //default: "Depends on matrix layout"
    },
    panelsState: {
      //default: "Users cannot expand or collapse panels",
      //collapsed: "All panels are collapsed",
      //expanded: "All panels are expanded"
    },
    widthMode: {
      //auto: "Auto",
      //static: "Static",
      //responsive: "Responsive"
    },
    imageFit: {
      //none: "None",
      //contain: "Contain",
      //cover: "Cover",
      //fill: "Fill"
    },
    contentMode: {
      //auto: "Auto",
      //image: "Image",
      //video: "Video",
      //youtube: "YouTube"
    },
    displayMode: {
      //auto: "Auto",
      //buttons: "Buttons",
      //dropdown: "Dropdown"
    }
  },
  // Operators
  op: {
    empty: "فارغة",
    notempty: "ليست فارغة",
    equal: "تساوي",
    notequal: "لا تساوي",
    contains: "تحتوي",
    notcontains: "لا تحتوي",
    anyof: "أي من",
    allof: "كلاً من",
    greater: "أكبر",
    less: "أقل",
    greaterorequal: "أكبر أو يساوي",
    lessorequal: "أقل أو يساوي"
  },
  // Embed window
  ew: {
    angular: "Use Angular version",
    jquery: "Use jQuery version",
    knockout: "Use Knockout version",
    react: "Use React version",
    vue: "Use Vue version",
    bootstrap: "For bootstrap framework",
    modern: "Modern theme",
    default: "Default theme",
    orange: "Orange theme",
    darkblue: "Darkblue theme",
    darkrose: "Darkrose theme",
    stone: "Stone theme",
    winter: "Winter theme",
    winterstone: "Winter-Stone theme",
    showOnPage: "Show survey on a page",
    showInWindow: "Show survey in a window",
    loadFromServer: "Load Survey JSON from server",
    titleScript: "Scripts and styles",
    titleHtml: "HTML",
    titleJavaScript: "JavaScript"
  },
  // Preview (Survey)
  ts: {
    selectPage: "Select the page to test it:",
    showInvisibleElements: "إظهار العناصر المخفية",
    //hideInvisibleElements: "Hide invisible elements"
  },
  validators: {
    answercountvalidator: "answer count",
    emailvalidator: "بريد إلكتروني",
    expressionvalidator: "عملية حسابية",
    numericvalidator: "رقمية",
    regexvalidator: "تعبير رياضي",
    textvalidator: "النص"
  },
  triggers: {
    completetrigger: "إنهاء الإستبيان",
    setvaluetrigger: "تحديد قيمة",
    copyvaluetrigger: "نسخ قيمة",
    skiptrigger: "الإنتقال إلى سؤال",
    runexpressiontrigger: "تشغيل العملية الحسابية",
    visibletrigger: "تغيير الرؤية (مهمل)"
  },
  pehelp: {
    //cookieName: "Cookies prevent users from filling out the same survey twice.",
    //format: "Use {0} as a placeholder for the actual value.",
    //totalText: "Visible only when at least one column has Total type or Total expression.",
    //acceptedTypes: "Refer to the [accept](https://www.w3schools.com/tags/att_input_accept.asp) attribute description for more information.",
    //columnColCount: "Applicable only to Radiogroup and Checkbox cell types.",
    //autocomplete: "Refer to the [autocomplete](https://developer.mozilla.org/en-US/docs/Web/HTML/Attributes/autocomplete) attribute description for more information.",
    //valueName: "If you do not set this property, the answer will be stored in a field specified by the Name property.",
    choicesbyurl: {
      //valueName: " "
    },
    //keyName: "If the specified column contains identical values, the survey throws the \"Non-unique key value\" error."
  },
  // Properties
  p: {
    title: {
      name: "title",
      title: "Leave it empty, if it is the same as 'Name'"
    },
    multiSelect: "متعدد الإختيار",
    showLabel: "عرض الملصق",
    value: "القيمة",
    visibleIf: "مرئي عندما",
    //attachOriginalItems: "attachOriginalItems",
    useDisplayValuesInDynamicTexts: "إستخدم عرض القيم في العنوان",
    titleLocation: "موقع عنوان السؤال",
    description: "الوصف",
    descriptionLocation: "موقع وصف السؤال",
    defaultValueExpression: "العملية الحسابية الإفتراضية",
    requiredIf: "مطلوب عندما",
    validators: "المدققات",
    bindings: "الإرتباطات",
    //renderAs: "renderAs",
    currency: "currency",
    //cellHint: "cellHint",
    //isUnique: "isUnique",
    //showInMultipleColumns: "showInMultipleColumns",
    //totalMaximumFractionDigits: "totalMaximumFractionDigits",
    //totalMinimumFractionDigits: "totalMinimumFractionDigits",
    columns: "الأعمدة",
    //detailElements: "detailElements",
    choices: "الإختيارات",
    //allowAdaptiveActions: "allowAdaptiveActions",
    defaultRowValue: "قيمة الصف الإفتراضية",
    detailPanelShowOnAdding: "detailPanelShowOnAdding",
    logoFit: "تناسب الشعار",
    pages: "الصفحات",
    //questions: "questions",
    triggers: "المحفزات",
    calculatedValues: "القيم المحسوبة",
    //surveyId: "surveyId",
    //surveyPostId: "surveyPostId",
    //surveyShowDataSaving: "surveyShowDataSaving",
    questionDescriptionLocation: "موقع وصف السؤال",
    progressBarType: "نوع شريط التقدم",
    questionTitlePattern: "تنسيق عنوان السؤال",
    widthMode: "نمط عٌرض الشاشة",
    //showBrandInfo: "showBrandInfo",
    choicesByUrl: "خيار عن طريق رابط إلكتروني URL",
    //choicesLazyLoadEnabled: "choicesLazyLoadEnabled",
    //choicesLazyLoadPageSize: "choicesLazyLoadPageSize",
    //inputFieldComponent: "inputFieldComponent",
    //itemComponent: "itemComponent",
    min: "أقل",
    max: "أكبر",
    minValueExpression: "minValueExpression",
    maxValueExpression: "maxValueExpression",
    step: "step",
    dataList: "قائمة البيانات",
    itemSize: "itemSize",
    //elements: "elements",
    //content: "content",
    navigationButtonsVisibility: "رؤية أزرار التنقل",
    navigationTitle: "navigationTitle",
    navigationDescription: "navigationDescription",
    //closeOnSelect: "closeOnSelect",
    //longTap: "longTap",
    autoGrow: "تمدد تلقائي",
    //acceptCarriageReturn: "acceptCarriageReturn",
    //displayMode: "displayMode",
    label: "المسمى",
    contentMode: "نمط عرض المحتوى",
    imageFit: "إحتواء الصورة",
    //altText: "altText",
    height: "height",
    penColor: "لون القلم",
    backgroundColor: "لون الخلفية",
    //templateElements: "templateElements",
    //operator: "operator",
    //isVariable: "isVariable",
    //runExpression: "runExpression",
    showCaption: "showCaption",
    iconName: "iconName",
    iconSize: "iconSize"
  }
};

//Uncomment this line on creating a translation file. You should replace "en" and enStrings with your locale ("fr", "de" and so on) and your variable.
editorLocalization.locales["ar"] = arStrings;