import { editorLocalization } from "survey-creator-core";

var frenchTranslation = {
  //Survey templates
  survey: {
    edit: "Éditer",
    externalHelpLink: "Apprendre à créer des questionnaires",
    dropQuestion: "Déposer votre question ici.",
    addLogicItem: "Create a rule to customize the flow of the survey.",
    copy: "Copier",
    duplicate: "Dupliquer",
    settings: "Réglages",
    addToToolbox: "Ajouter à la boîte à outils",
    deletePanel: "Supprimer le panneau",
    deleteQuestion: "Supprimer la question",
    convertTo: "Convertir en",
    drag: "Cliquer-glisser",
    license:
      "Vous devez acheter une licence pour utiliser survey-creator dans vos applications"    
  },
  //questionTypes
  qt: {
    default: "Par défaut",
    checkbox: "Cases à cocher",
    comment: "Commentaire",
    imagepicker: "Choix d'image",
    ranking: "Classement",
    image: "Image",
    dropdown: "Liste déroulante",
    tagbox: "Etiquettes",
    file: "Fichier",
    html: "HTML",
    matrix: "Matrice (choix unique)",
    matrixdropdown: "Matrice (choix multiples)",
    matrixdynamic: "Matrice (lignes dynamiques)",
    multipletext: "Champ multilignes",
    panel: "Panneau",
    paneldynamic: "Panneau (panneaux dynamiques)",
    radiogroup: "Boutons radio",
    rating: "Évaluation",
    text: "Champ texte",
    boolean: "Booléen",
    expression: "Expression",
    signaturepad: "Signature",
    buttongroup: "Groupe de boutons",
    flowpanel: "Panneau de flux"    
  },
  //Strings in Editor
  ed: {
    defaultLocale: "Langue par défaut ({0})",
    survey: "Questionnaire",
    editSurvey: "Éditer le questionnaire",
    settings: "Configuration du questionnaire",
    opjectPropertiesHeader: "Propriétés",
    showObjectProperties: "Afficher les propriétés",
    hideObjectProperties: "Cacher les propriétés",
    showPanel: "Afficher panneau",
    hidePanel: "Cacher panneau",
    prevSelected: "Select previous",
    nextSelected: "Suivant",    
    surveyTypeName: "Questionnaire",
    pageTypeName: "Page",
    panelTypeName: "Panneau",
    questionTypeName: "Question",
    columnTypeName: "Colonne",
    addNewPage: "Ajouter une page",
    moveRight: "Défiler à droite",
    moveLeft: "Défiler à gauche",
    deletePage: "Supprimer une page",
    editPage: "Éditer une page",
    edit: "Éditer",  
    newPageName: "page",
    newQuestionName: "question",
    newPanelName: "panneau",
    newTextItemName: "texte",
    testSurvey: "Tester le questionnaire",
    defaultV2Theme: "Defaut",
    modernTheme: "Modern",
    defaultTheme: "Defaut (ancien)",
    testSurveyAgain: "Tester à nouveau le questionnaire",
    testSurveyWidth: "Largeur du questionnaire : ",
    navigateToMsg: "Vous devez aller vers",
    logic: "Logique",
    embedSurvey: "Intégrer le questionnaire",
    translation: "Traduction",
    surveySettings: "Configuration du questionnaire",
    surveySettingsTooltip: "Configuration du questionnaire",
    saveSurvey: "Sauvegarder le questionnaire",
    designer: "Éditeur de questionnaire",
    jsonEditor: "Éditer JSON",
    jsonHideErrors: "Cacher les erreurs",
    jsonShowErrors: "Afficher les erreurs",
    undo: "Annuler",
    redo: "Rétablir",    
    undoTooltip: "Annuler le changement",
    redoTooltip: "Refaire",
    showMoreChoices: "Afficher plus",
    showLessChoices: "Afficher moins",
    copy: "Copier",
    cut: "Couper",
    paste: "Coller",
    copyTooltip: "Copier la selection dans le presse-papier",
    cutTooltip: "Couper la selection dans le presse-papier",
    pasteTooltip: "Coller depuis le presse-papier",
    options: "Options",
    generateValidJSON: "Générer un JSON valide",
    generateReadableJSON: "Générer un JSON lisible",
    toolbox: "Boîte à outils",
    "property-grid": "Propriétés",
    propertyGridFilteredTextPlaceholder: "Type to search...",
    toolboxGeneralCategory: "Général",
    toolboxGeneralCategory: "General",
    toolboxChoiceCategory: "Questions à choix multiple",
    toolboxTextCategory: "Questions textes",
    toolboxContainersCategory: "Conteneurs",
    toolboxMatrixCategory: "Matrice de Questions",
    toolboxMiscCategory: "Divers",
    delSelObject: "Supprimer l'objet sélectionné",
    editSelObject: "Éditer l'objet sélectionné",
    correctJSON: "SVP corrigez le JSON",
    surveyResults: "Résultat du questionnaire : ",
    surveyResultsTable: "Comme tableau",
    surveyResultsJson: "Comme JSON",
    resultsTitle: "Titre de la question",
    resultsName: "Nom de la question",
    resultsValue: "Valeur de la réponse",
    resultsDisplayValue: "Valeur affichée",
    modified: "Modifié",
    saving: "Sauvegarde en cours",
    saved: "Sauvegardé",
    propertyEditorError: "Error",
    saveError: "Erreur! Le contenu de l'éditeur n'a pas été sauvegardé.",
    translationPropertyGridTitle: "Réglage langue",
    translationAddLanguage: "Choisir langue à traduire",
    translationShowAllStrings: "Afficher tous les termes",
    translationShowAllPages: "Afficher toutes les pages",
    translationNoStrings:
      "Aucun terme à traduire. Veuillez modifier le filtre.",
    translationExportToSCVButton: "Exporter en CSV",
    translationImportFromSCVButton: "Importer d'un CSV",
    translationMergeLocaleWithDefault: "Fusionner {0} avec langue par défaut",
    translationPlaceHolder: "Traduction...",
    bold: "Gras",
    italic: "Italique",
    underline: "Souligné",
    addNewQuestion: "Ajouté une Question",
    selectPage: "Selectionner la page...",
    htmlPlaceHolder: "Le contenu HTML...",
    panelPlaceHolder: "Cliquer-glisser une question ici.",
    surveyPlaceHolder: "L' enquête est vide. Faites glisser un élément de la boîte à outils ou cliquez sur le bouton ci-dessous.",
    addNewTypeQuestion: "Ajouter {0}", //{0} is localizable question type
    addNewQuestion: "Ajouter {0}",
    completedHtmlOnConditionItemText: "Afficher si :",
    chooseLogoPlaceholder: "[LOGO]",
    auto: "auto",
    lg: {
      //Logic tab strings
       ddNewItem: "Add New Rule",
      //Logic tab strings
      empty_tab: "Créer une règle pour customiser le flow.",
      page_visibilityName: "Visibilité de la page",
      panel_visibilityName: "Visibilité du panneau",
      panel_enableName: "Activer/désactiver le panneau",
      question_visibilityName: "Visibilité de la question",
      question_enableName: "Activer/désactiver la question",
      question_requireName: "Question facultative requise",
      column_visibilityName: "Afficher (cacher) colonne",
      column_enableName: "Autoriser (desactiver) colonne",
      column_requireName: "Rendre la colonne obligatoire",
      trigger_completeName: "Compléter le questionnaire",
      trigger_setvalueName: "Définir la valeur de la question",
      trigger_copyvalueName: "Copier la valeur de la question",
      trigger_skipName: "Passer à la question",
      trigger_runExpressionName: "Exécuter une expression personnalisée",
      completedHtmlOnConditionName:
        "Personnaliser le texte de la page de remerciements",

      page_visibilityDescription:
        "Rendre la page visible lorsque l'expression logique renvoie 'vrai'. Sinon, la rendre invisible.",
      panel_visibilityDescription:
        "Rendre le panneau visible lorsque l'expression logique renvoie 'vrai'. Sinon, le rendre invisible.",
      panel_enableDescription:
        "Activez le panneau et tous les éléments qu'il contient lorsque l'expression logique renvoie 'vrai'. Sinon, le laisser désactivé.",
      question_visibilityDescription:
        "Rendez la question visible lorsque l'expression logique renvoie 'vrai'. Sinon, la rendre invisible.",
      question_enableDescription:
        "Activez la question lorsque l'expression logique renvoie 'vrai'. Sinon, la laisser désactivée.",
      question_requireDescription:
        "La question devient requise lorsque l'expression logique renvoie 'vrai'.",
      trigger_completeDescription:
        "Lorsque l'expression logique renvoie 'vrai', l'enquête est alors terminée et un utilisateur voit la page de remerciements.",
      trigger_setvalueDescription:
        "When question values, that are used in the logic expression, are changed and the logic expression returns true, then the value is set to the selected question.",
      trigger_copyvalueDescription:
        "Lorsque les valeurs de question, qui sont utilisées dans l'expression logique, sont modifiées et que l'expression logique renvoie 'vrai', la valeur d'une question sélectionnée est copiée dans une autre question sélectionnée.",
      trigger_skipDescription:
        "Lorsque l'expression logique renvoie 'vrai', l'enquête passe à la question sélectionnée.",
      trigger_runExpressionDescription:
        "Lorsque l'expression logique renvoie 'vrai', alors l'expression personnalisée est exécutée. Vous pouvez éventuellement définir ce résultat d'expression dans la question sélectionnée.",
      completedHtmlOnConditionDescription:
        "Si l'expression logique renvoie 'vrai', le texte par défaut de la page de remerciements est remplacé par celui que vous avez défini.",

      itemExpressionText: "Lorsque l'expression: '{0}' renvoie 'vrai':", //{0} - the expression
      itemEmptyExpressionText: "Nouvelle règle",
      page_visibilityText: "Rendre la page {0} visible", //{0} page name
      panel_visibilityText: "Rendre le panneau {0} visible", //{0} panel name
      panel_enableText: "Activer le panneau {0}", //{0} panel name
      question_visibilityText: "Rendre la question {0} visible", //{0} question name
      question_enableText: "Activer la question {0}", //{0} question name
      question_requireText: "Rendre la question {0} obligatoire", //{0} question name
      column_visibilityText: "make column {0} of question {1} visible", //{0} column name, {1} question name
      column_enableText: "Activer la colonne {0} de la question {1}", //{0} column name, {1} question name
      column_requireText: "Rendre la colonne {0} de la question {1} obligatoire", //{0} column name, {1} question name
      trigger_completeText: "Le questionnaire devient complété.",
      trigger_setvalueText: "Définir dans la question: {0} valeur {1}", //{0} question name, {1} setValue
      trigger_copyvalueText:
        "Copier dans la question: {0} valeur de la question {1}", //{0} and {1} question names
      trigger_skipText: "Dans le questionnaire, passez à la question {0}", //{0} question name
      trigger_runExpressionText1: "Exécuter l'expression: '{0}'", //{0} the expression
      trigger_runExpressionText2:
        " et définissez son résultat dans la question: {0}", //{0} question name
      completedHtmlOnConditionText:
        "Affichez un texte personnalisé pour la page de remerciements.",
      
      showAllQuestions: "Toutes les Questions",
      showAllActionTypes: "Tous les type d'actions",

      conditions: "Condition(s)",
      actions: "Action(s)",
      expressionEditorTitle: "Définissez le(s) condition(s)",
      actionsEditorTitle: "Définissez le(s) action(s)",

      deleteAction: "Détruire l'action",
      addNewAction: "Ajouter une nouvelle action",
      selectedActionCaption: "Sélectionnez une action à ajouter …",

      expressionInvalid:
        "L'expression logique est vide ou non valide. Corrigez s'il-vous-plaît.",
      noActionError: "Veuillez ajouter au moins une action.",
      actionInvalid: "Veuillez corriger les problèmes dans vos actions.",
      expressionSetup: "",
      actionsSetup: "",
    },
  },
  //Property names in table headers
  pel: {
    isRequired: "Obligatoire ?",
  },
  //Property Editors
  pe: {
    apply: "Appliquer",
    ok: "OK",
    save: "Enregistrer",
    clear:"Effacer",
    saveTooltip: "Enregistrer",
    cancel: "Annuler",
    set: "Fixer",
    reset: "Réinitialiser",
    change: "Modifier",
    close: "Fermer",
    delete: "Supprimer",
    add:"Ajouter",
    addNew: "Ajouter un nouvel élément",
    addItem: "Cliquer pour ajouter un item...",
    removeItem: "Cliquer pour supprimer unitem...",
    dragItem: "Cliquer-glisser un item",
    addOther: "Autre",
    addSelectAll: "Tout sélectionner",
    addNone: "Aucun",
    removeAll: "Tout supprimer",
    edit: "Éditer",        
    back: "Retourner sans enregistrer",
    backTooltip: "Retourner sans enregistrer",
    saveAndBack: "Enregistrer et retourner",
    saveAndBackTooltip: "Enregistrer et retourner",
    doneEditing: "Finit",
    move: "Déplacer",
    empty: "<vide>",
    notEmpty: "<éditer la valeur>",
    editChoices: "Editer les choix",
    fastEntry: "Ajout rapide",
    fastEntryNonUniqueError: "Valeur '{0}' non unique",
    fastEntryChoicesCountError:
      "Merci de limiter le nombre d'item entre {0} et {1}",
    fastEntryPlaceholder: "Vous pouvez saisir dans le format suivant:\nvalue1|text\nvalue2",
    formEntry: "Ajout via formulaire",
    testService: "Tester le service",
    conditionActionEmpty: "Sélectionner une Action",
    conditionSelectQuestion: "Sélectionner une question...",
    conditionSelectPage: "Selection page...",
    conditionSelectPanel: "Selection panneau...",
    conditionValueQuestionTitle: "Sélectionner ou saisir la valeur",
    conditionButtonAdd: "Ajouter",
    conditionButtonReplace: "Remplacer",
    conditionHelp:
      'Veuillez entrer une expression booléenne. Elle doit retourner Vrai(true) pour garder la question/page visible. Par exemple: {question1} = "valeur1" or ({question2} = 3 and {question3} < 5)',
    expressionHelp:
      "Veuillez entrer une expression. Vous pouvez utiliser des accolades pour accéder aux valeurs des questions '{question1} + {question2}', '({prix}*{quantite}) * (100 - {remise})'",
    aceEditorHelp:
      "Appuyer sur Ctrl + espace pour obtenir une aide pour la saisie d'expression",
    aceEditorRowTitle: "Ligne courante",
    aceEditorPanelTitle: "Panneau courant",
    showMore:
      "Pour plus d'informations, veuillez vous référer à la documentation",
    assistantTitle: "Questions disponibles :",
    cellsEmptyRowsColumns: "Il faut au minimum une ligne ou une colonne",
    propertyIsEmpty: "Veuillez entrer une valeur pour la propriété",
    propertyIsNoUnique: "Valeur déjà utilisée",
    propertyNameIsNotUnique: "Nom déjà utilisé",
    listIsEmpty: "Ajouter un nouvel élément",
    "listIsEmpty@choices": "Aucun choix effectué pour l'instant",
    "addNew@choices": "Ajouter une choix",
    expressionIsEmpty: "L'expression est vide",
    value: "Valeur",
    text: "Texte",
    rowid: "ID Ligne",
    imageLink: "URL de l'image",
    columnEdit: "Éditer la colonne: {0}",
    itemEdit: "Éditer l'item: {0}",    
    url: "URL",
    path: "Chemin",
    valueName: "Nom de la valeur",
    titleName: "Nom du titre",
    imageLinkName: "Chemin des images depuis le champ JSON suivant",
    allowEmptyResponse: "Autoriser les réponses vides",
    titlePlaceholder: "Titre de la page",
    descriptionPlaceholder: "Entrer une description",
    surveyTitlePlaceholder: "Saisissez le titre de l'enquête",
    pageTitlePlaceholder: "Saisissez le titre de la page",
    surveyDescriptionPlaceholder: "Description",
    pageDescriptionPlaceholder: "Entrer une description pour la page",    
    surveyDescriptionPlaceholder: "Entrer une description pour l'enquête",
    showOtherItem: 'Contient un item "Autre"',
    otherText: 'Texte item "Autre"',
        otherPlaceHolder: "Comment area placeholder",
    showNoneItem: 'Contient un item "Aucun"',
    noneText: 'Texte item "Aucun"',
    showSelectAllItem: 'Contient un item "Tout sélectionner"',
    selectAllText: 'Texte item "Tout sélectionner"',
    choicesMin: "Valeur minimum pour les items générés automatiquement",
    choicesMax: "Valeur maximum pour les items générés automatiquement",
    choicesStep: "Différence entre items générés automatiquement",
    name: "Nom",
    title: "Titre",
    cellType: "Type de cellule",
    colCount: "Nombre de colonnes",
    choicesOrder: "Sélectionner l'ordre des choix",
    visible: "Est visible ?",
    isRequired: "Est obligatoire ?",
    isAllRowRequired: "Réponse obligatoire pour toutes les lignes",
    requiredErrorText: "Message d'erreur lorsque obligatoire",
    startWithNewLine: "Commencer avec une nouvelle ligne ?",
    rows: "Nombre de lignes",
    placeholder: "(indice dans le champ)",
    showPreview: "L'aperçu d'image est-il affiché ?",
    storeDataAsText:
      "Stocker le contenu du fichier dans le résultat JSON sous forme de texte",
    maxSize: "Taille maximum du fichier en octets",
    imageHeight: "Hauteur de l'image",
    imageWidth: "Largeur de l'image",
    rowCount: "Nombre de lignes",
    columnLayout: "Inverser les lignes et les colonnes",
    addRowLocation: 'Emplacement bouton "Ajouter une ligne"',
    addRowText: 'Texte bouton "Ajouter une ligne"',
    removeRowText: 'Texte bouton "Supprimer une ligne"',
    rateMin: "Note minimum",
    rateMax: "Note maximum",
    rateStep: "Intervalle des notes",
    minRateDescription: "Description note minimum",
    maxRateDescription: "Description note maximum",
    inputType: "Type de champ",
    optionsCaption: "Texte par défaut",
    showOptionsCaption: "Afficher l'indice",
    defaultValue: "Valeur par défaut",
    cellsDefaultRow: "Texte de cellule par défaut",
    surveyEditorTitle: "Éditer les préférences du questionnaire",
    qEditorTitle: "Éditer la question: {0}",
    maxLength: "Longueur maximum",
    
    buildExpression: "Construire",
    editExpression: "Editer",
    and: "Et",
    or: "Ou",
    remove: "Enlever",
    addCondition: "Ajouter une condition",    
    emptyLogicPopupMessage: "Selectionner une question pour configurer les options.",
    if: "Si",
    then: "Alors",
    setToName: "Question cible",
    fromName: "Copier le texte depuis la question",
    gotoName: "Aller à la question",
    ruleIsNotSet: "Règle incorrecte",
    includeIntoResult: "Inclure dans les résultats du questionnaire",

    //survey
    showTitle: "Afficher/cacher le titre",
    expandCollapseTitle: "Afficher/masquer le titre",
    locale: "Langue par défaut",
    simulator: "Choisir l'appareil",
    landscapeOrientation: "Paysage",
    portraitOrientation: "Portrait",
    mode: "Mode (édition/lecture seule)",
    clearInvisibleValues: "Effacer les valeurs invisibles",
    cookieName:
      "Nom du cookie (pour empêcher de compléter 2 fois le questionnaire localement)",
    sendResultOnPageNext: "Envoyer les résultats au changement de page",
    storeOthersAsComment: 'Sauvegarder la valeur "Autres" dans un champ séparé',
    showPageTitles: "Afficher les titres de pages",
    showPageNumbers: "Afficher les numéros de pages",
    pagePrevText: "Texte bouton page précédente",
    pageNextText: "Texte bouton page suivante",
    completeText: "Texte bouton terminer",
    previewText: "Text du bouton d'aperçu des réponses",
    editText: "Editer le texte du bouton d'aperçu des réponses",
    startSurveyText: "Texte bouton commencer",
    showNavigationButtons:
      "Afficher les boutons de navigation (navigation par défaut)",
    showPrevButton:
      "Afficher le bouton précédent (l'utilisateur pourra retourner sur la page précédente)",
    firstPageIsStarted:
      "La première page du questionnaire est une page de démarrage.",
    showCompletedPage: 'Afficher la page "terminé" à la fin (completedHtml)',
    goNextPageAutomatic:
      "Aller à la page suivante automatiquement pour toutes les questions",
    showProgressBar: "Afficher la barre de progression",
    questionTitleLocation: "Emplacement du titre de la question",
    requiredText: "La question requiert un/des symbole(s)",
    questionStartIndex: "Index de départ de la question (1, 2 ou 'A', 'a')",
    showQuestionNumbers: "Afficher les numéros de questions",        
    questionTitleTemplate:
      "Gabarit du titre de question, par défaut : '{no}. {require} {title}'",
    questionErrorLocation: "Emplacement de l'erreur",
    focusFirstQuestionAutomatic:
      "Focus sur la première question au changement de page",
    questionsOrder: "Ordre des éléments sur la page",
    maxTimeToFinish: "Temps maximum pour terminer le questionnaire",
    maxTimeToFinishPage: "Temps maximum pour terminer une page",
        page: {
      maxTimeToFinish: "Time limit to finish the page (in seconds)",
    },
    question: {
      page: "Parent page"
    },
    showTimerPanel: "Afficher le panneau chronomètre",
    showTimerPanelMode: "Mode d'affichage du panneau chronomètre",
    renderMode: "Mode de rendu",
    allowAddPanel: "Autoriser l'ajout du panneau",
    allowRemovePanel: "Autoriser la suppression du panneau",
    noEntriesText: "Empty entries text",
    panelAddText: "Ajouter un panneau texte",
    panelRemoveText: "Supprimer le panneau texte",
    html: "HTML markup",
    isSinglePage: "Afficher tous les éléments sur une seule page",
    expression: "Expression",
    setValue: "Réponse",
    dataFormat: "Format de l'image",
    allowAddRows: "Autoriser l'ajout de ligne",
    allowRemoveRows: "Autoriser la suppresion de ligne",
    allowRowsDragAndDrop: "Autorider le cliquer-glisser",
       
    responsiveImageSizeHelp: "Ne s'appliera pas si vous spécifié la largeur ou la hauteur.",
    minImageWidth: "Largeur minimum",
    maxImageWidth: "Largeur maximum",
    minImageHeight: "Hauteur minimum",
    maxImageHeight: "Hauteur maximum",
    
  
    minValue: "Valeur minimum",
    maxValue: "Valeur maximum",
    minLength: "Longueur minimum",
    allowDigits: "Permettre chiffres",
    minCount: "Nombre minimum",
    maxCount: "Nombre maximum",
    regex: "Expression régulière",
        surveyvalidator: {
      text: "Error message",
      expression: "Validation expression"
    },

    totalText: "Texte pour le total",
    totalType: "Type de total",
    totalExpression: "Expression de calcul",
    totalDisplayStyle: "Format d'affichage",
    totalCurrency: "Monnaie",
    totalFormat: "Format du total",
        
    logo: "Logo (URL ou Chaine encodée en base64)",
    questionsOnPageMode: "Structure du questionnaire",
    maxTextLength: "Longueur maximum de la réponse (en caractères)",
    maxOthersLength: "Longueur maximum du commentaire (en caractères)",
    autoGrowComment: "Agrandir la zone commentaire si necessaire",
    textUpdateMode: "Mettre a jour le texte de la quesiton",
    focusOnFirstError: "Mettre le focus sur la première erreur",
    checkErrorsMode: "Lancer validation",
    navigateToUrl: "Aller à URL",
    navigateToUrlOnCondition: "URL Dynamique",
    completedBeforeHtml: "Marque indiquant que l'utilisateur à déjà remplis le questionnaire",
    completedHtml: "Message lorsque le questionnaire terminé",
    completedHtmlOnCondition: "Message lorsque le questionnaire dynamique terminé",
    loadingHtml: "Message de chargement du questionnaire",
    commentText: "Zone de commentaire",
    autocomplete: "Type de complétion",
    labelTrue: "\"Vrai\" label",
    labelFalse: "\"Faux\" label",
    allowClear: "Afficher le bouton Effacer",
    displayStyle: "Style d'affichage",
    format: "Chaine formattée",
    maximumFractionDigits: "Nombre maximum de décimale",
    minimumFractionDigits: "Nombre minimum de décimale",
    useGrouping: "Afficher les séparateurs",
    allowMultiple: "Autoriser plusieurs fichiers",
    allowImagesPreview: "Previsualisé les images",
    acceptedTypes: "Type de fichier acceptés",
    waitForUpload: "Attente du téléversement",
    needConfirmRemoveFile: "Confirmer la suppresion de fichier",
    detailPanelMode: "Position du panneau de détails",
    minRowCount: "Nombre minimum de ligne",
    maxRowCount: "Nombre maximun de ligne",
    confirmDelete: "Confirmer la suppresion de ligne",
    confirmDeleteText: "Message de confirmation",
    paneldynamic: {
      confirmDelete: "Confirmer la suppresion du panneau",
    },
    panelCount: "Nombre de panneau",
    minPanelCount: "Nombre minimum de panneau",
    maxPanelCount: "Nombre maximum de panneau",
    panelsState: "État d'expansion du panneau intérieur",
    templateDescription: "Modèle de description",
    templateTitle: "Titre du modèle",
    panelPrevText: "Aide du bouton Précédent",
    panelNextText: "Aide du bouton suivant",
    showRangeInProgress: "Afficher la barre de progression",
    templateTitleLocation: "Position du titre de la question",
    panelRemoveButtonLocation: "Supprimer le bouton de position du panneau",
    hideIfRowsEmpty: "Cacher la question si il n'y a pas de ligne",
    hideColumnsIfEmpty: "Cacher la colonne si il n'y a pas de ligne",
    rateValues: "Valeurs de taux personnalisées",
    hideIfChoicesEmpty: "Cacher la question si il n'y a aucun choix",
    hideNumber: "Cacher le numéro de question",
    minWidth: "Largeur minimum (au format CSS)",
    maxWidth: "Largeur maximum (au format CSS)",
    width: "Largeur (au format CSS)",
    showHeader: "Afficher les entêtes de colonnes",
    horizontalScroll: "Barre de défilement horizontale",
    columnMinWidth: "Largeur de colonne minimum (au format CSS)",
    rowTitleWidth: "Largeur d'entête de ligne (au format CSS)",
    valueTrue: "\"Vrai\" value",
    valueFalse: "\"Faux\" value",
    minErrorText: "Message d'erreur \"La valeur est inférieure au minimum\" ",
    maxErrorText: "Message d'erreur \"La valeur est supérieure au maximum\" ",
    otherErrorText: "Message d'erreur \"Commentaire vide\" ",
    keyDuplicationError: "Message d'erreur \"Valeur de clef non-unique\" ",
    maxSelectedChoices: "Nombre de choix maximum",
    showClearButton: "Afficher le bouton Effacer",
    showNumber: "Afficher le numéro de panneau",
    logoWidth: "Largeur du Logo (au format CSS)",
    logoHeight: "Hauteur du Logo (au format CSS)",
    readOnly: "Lecture-seule",
    enableIf: "Modifiable si",
    emptyRowsText: "Message \"Aucune ligne\" ",
    size: "Taille (en caractères)",
    separateSpecialChoices: "Separer les choix spéciaux (Aucun, Autres, Tous)",
    choicesFromQuestion: "Copier les choix de la question",
    choicesFromQuestionMode: "Quels choix copier ?",
    showCommentArea: "Afficher la zone commentaire",
    commentPlaceHolder: "indice du commentaire",
    displayRateDescriptionsAsExtremeItems: "Afficher les descriptions de taux sous forme de valeurs extrêmes",
    rowsOrder: "Ordre des lignes",
    columnsLayout: "Disposition des colonnes",
    columnColCount: "Nombre de colonne intégré",
    state: "Etat du panneau d'extension",
    correctAnswer: "Réponse correcte",
    defaultPanelValue: "Valeurs par défauts",
    cells: "Cellules",
    keyName: "Clef de colonne",
    itemvalue: {
      text: "texte alternatif"
    },

    logoPosition: "Position du logo",
    addLogo: "Ajouter un logo...",
    changeLogo: "Changer le logo...",
    logoPositions: {
      none: "Retirer le logo",
      left: "Gauche",
      right: "Droite",
      top: "Au dessus",
      bottom: "En dessous",
    },

    tabs: {
      general: "Général",
      fileOptions: "Options",
      html: "Éditeur HTML",
      columns: "Colonnes",
      rows: "Lignes",
      choices: "Choix",
      visibleIf: "Visible si",
      enableIf: "Actif si",
      requiredIf: "Obligatoire si",
      rateValues: "Barème",
      choicesByUrl: "Choix depuis API web",
      matrixChoices: "Choix par défaut",
      multipleTextItems: "Champs texte multiples",
      numbering: "Numbering",
      validators: "Validateurs",
      navigation: "Navigation",
      question: "Question",
      pages: "Pages",
      completedHtml: "HTML de fin",
      completedHtmlOnCondition: "Html de fin (page 'terminé') sur condition",
      loadingHtml: "HTML de chargement",
      timer: "Chronomètre/Quiz",
      calculatedValues: "Valeurs calculées",
      triggers: "Déclencheurs",
      templateTitle: "Titre de gabarit",
      totals: "Totaux",
      logic: "Conditions",
      layout: "Disposition",
      data: "Données",
      validation: "Validateurs",
      cells: "Cellules",
      showOnCompleted: "Questionnaire Completer",
      logo: "Logo dans le titre de l'enquête",
      slider: "Slider",
      others: "Autres"
    },
    editProperty: 'Éditer la propriété "{0}"',
    choicesVisibleIf: "Choix visibles si",
    choicesEnableIf: "Choix sélectionnables si",
    columnsEnableIf: "Colonnes visibles si",
    rowsEnableIf: "Rows are visible if",
    indent: "Ajouter tirets",
    panel: {
      indent: "Ajouter tirets extérieur"
    },
    innerIndent: "Ajouter tirets intérieurs",
    defaultValueFromLastRow: "Valeur par défaut depuis la dernière ligne",
    defaultValueFromLastPanel: "Valeur par défaut depuis le dernier panneau",
    items: "[ Éléments: {0} ]",
    enterNewValue: "Veuillez saisir la valeur.",
    noquestions: "Il n'y a aucune question dans le questionnaire.",
    createtrigger: "Veuillez créer un déclencheur",
    triggerOn: "Quand ",
    triggerMakePagesVisible: "Rendre les pages visibles :",
    triggerMakeQuestionsVisible: "Rendre les questions visibles :",
    triggerCompleteText: "Terminer le questionnaire en cas de succès.",
    triggerNotSet: "Le déclencheur n'est pas défini",
    triggerRunIf: "Exécuter si",
    triggerSetToName: "Changer la valeur de : ",
    triggerFromName: "Copier la valeur de : ",
    triggerRunExpression: "Exécuter cette expression :",
    triggerSetValue: "à : ",
    triggerGotoName: "Aller à la question :",
    triggerIsVariable:
      "Ne placez pas la variable dans le résultat du questionnaire.",
    triggerRunExpressionEmpty: "Veuillez entrer une expression valide",
  },
  //Property values
  pv: {                          
    
  
    true: "vrai",
    false: "faux",
    inherit: "hérité",
    show: "afficher",
    hide: "masquer",
    default: "par défaut",
    initial: "initial",
    random: "aléatoire",
    collapsed: "replié",
    expanded: "déployé",
    none: "aucun",
    asc: "ascendant",
    desc: "descendant",
    indeterminate: "indeterminé",
    decimal: "décimal",
    currency: "monnaie",
    percent: "pourcentage",
    firstExpanded: "déployé en premier",
    off: "désactivé",
    onPanel: "panneau",
    onSurvey: "questionnaire",
    list: "liste",
    progressTop: "Progression en haut",
    progressBottom: "Progression en bas",
    progressTopBottom: "Progression en haut et en bas",
    horizontal: "Horizontale",
    vertical: "Verticale",
    top: "haut",
    bottom: "bas",
    topBottom: "haut et bas",
    both: "les deux",
    left: "gauche",
    color: "couleur",
    date: "date",
    datetime: "heure",
    "datetime-local": "heure locale",
    email: "email",
    month: "mois",
    number: "nombre",
    password: "mot de passe",
    range: "jauge",
    tel: "tél.",
    text: "texte",
    time: "heure",
    url: "URL",
    week: "semaine",
    hidden: "masqué",
    on: "activé",
    onPage: "page",
    edit: "éditer",
    display: "affichage",
    onComplete: "Quand terminé",
    onHidden: "Quand caché",
    onHiddenContainer: "Quand la question devient cachée",
    clearInvisibleValues: {
      none: "Jamais"
    },
    all: "tous",
    page: "page",
    survey: "questionnaire",   
    onNextPage: "Au changement de page",
    onValueChanged: "Après modification de réponse",
    onValueChanging: "Avant modification de réponse",
    standard: "Structure originale",
    singlePage: "Toutes les question sur une page",
    questionPerPage: "Une question par page",
    noPreview: "Pas de prévisualisation",
    showAllQuestions: "Afficher toutes les questions",
    showAnsweredQuestions: "N'afficher que les questions ayant des réponses",
    pages: "Pages terminées",
    questions: "Questions répondues",
    requiredQuestions: "Questions répondues obligatoires",
    correctQuestions: "Réponses valides",
    buttons: "Pages complétées (bouton UI)",
    underInput: "Sous l'entrée",
    underTitle: "Sous le titre",
    onBlur: "Sur floutage",
    onTyping: "sur appuie",
    underRow: "Sous la ligne",
    underRowSingle: "Sous la ligne, un seul panneau visible",
    showNavigationButtons: {
        none: "Caché"
      },
      showProgressBar: {
        off: "Caché"
      },
      showTimerPanel: {
        none: "Caché"
      },
      showTimerPanelMode: {
        all: "les deux"
      },
      detailPanelMode: {
        none: "Caché"
      },
      addRowLocation: {
        default: "Depend de la disposition"
      },
      panelsState: {
        default: "L'utilisateur ne peux pas replier/déplier",
        collapsed: "Tous repliés",
        expanded: "Tous dépliés"
      }
  },
  //Operators
  op: {
    empty: "est vide",
    notempty: "n'est pas vide",
    equal: "égal",
    notequal: "n'est pas égal",
    contains: "contient",
    notcontains: "ne contient pas",
    anyof: "n'importe quel de",
    allof: "tous parmi",
    greater: "supérieur",
    less: "inférieur",
    greaterorequal: "supérieur ou égal",
    lessorequal: "inférieur ou égal",
    and: "et",
    or: "ou"
  },
  //Embed window
  ew: {
    angular: "Utiliser la version Angular",
    jquery: "Utiliser la version jQuery",
    knockout: "Utiliser la version Knockout",
    react: "Utiliser la version React",
    vue: "Utiliser la version Vue",
    bootstrap: "Pour le framework Bootstrap",
    standard: "Sans Bootstrap",
    modern: "Thème Modern",
    default: "Thème par défaut",
    orange: "Thème Orange",
    darkblue: "Thème Darkblue",
    darkrose: "Thème Darkrose",
    stone: "Thème Stone",
    winter: "Thème Winter",
    winterstone: "Thème Winter-Stone",
    showOnPage: "Afficher le questionnaire dans une page",
    showInWindow: "Afficher le questionnaire dans une fenêtre",
    loadFromServer: "Charger le JSON du questionnaire depuis un serveur",
    titleScript: "Scripts et styles",
    titleHtml: "HTML",
    titleJavaScript: "JavaScript"
  },
  //Preview (Survey)
  ts: {
    selectPage: "Sélectionner une page pour la tester",
    showInvisibleElements: "Afficher les éléments invisibles",
    hideInvisibleElements: "Cacher les éléments invisibles"
  },
  //Validators
  validators: {
    answercountvalidator: "total de réponses",
    emailvalidator: "e-mail",
    expressionvalidator: "Expression",
    numericvalidator: "numérique",
    regexvalidator: "regex",
    textvalidator: "texte",
  },
  //Triggers
  triggers: {
    completetrigger: "terminer le questionnaire",
    setvaluetrigger: "définir la valeur",
    copyvaluetrigger: "copier la valeur",
    skiptrigger: "sauter à la question",
    runexpressiontrigger: "exécuter expression",
    visibletrigger: "modifier la visibilité",
  },
  pehelp: {
    cookieName: "Les cookies empêchent les utilisateurs de répondre deux fois au même questionnaire.",
    format: "Utiliser {0} comme indice pour la valeur actuelle.",
    totalText: "Visible seulement lorsqu'au moins une colonne possède un total.",
    acceptedTypes: "Type accepter (https://www.w3schools.com/tags/att_input_accept.asp).",
    columnColCount: "Applicable seulement sur les boutons radio et les cases à cocher.",
    autocomplete: "Voir [autocomplete](https://developer.mozilla.org/en-US/docs/Web/HTML/Attributes/autocomplete).",
    valueName: "Si vous ne définissez pas cette propriétée, la réponse sera enregistrer dans un champ portant le nom property.",
    keyName: "Si la colonne spécifié contient une valeur identique, le questionnaire affichera une erreur \"Valeur non-unique\".",
  },
  //Properties
  p: {
    name: "Nom",
    title: {
      name: "Titre",
      title: 'Laissez vide, si même texte que le "Nom"',
    },
    navigationButtonsVisibility: "Visibilité des boutons de navigation",
    questionsOrder: "Ordre des questions",
    maxTimeToFinish: "Temps maximum pour terminer",
    visible: "Visible",
    visibleIf: "Visible si ",
    questionTitleLocation: "Emplacement titre question",
    description: "Description",
    state: "État",
    isRequired: "Obligatoire ?",
    requiredErrorText: "Message d'erreur text obligatoire",
    startWithNewLine: "Commencer avec une nouvelle ligne",
    innerIndent: "Indentation",
    page: "page",
    width: "largeur",
    commentText: "Description champ commentaire",
    valueName: "Nom de la valeur",
    enableIf: "Activer si",
    defaultValue: "Valeur par défaut",
    correctAnswer: "Bonne réponse",
    readOnly: "Lecture seule",
    validators: "Validateurs",
    titleLocation: "Emplacement du titre",
    showCommentArea: "Champ commentaire ?",
    showOtherItem: "Choix autre ?",
    choices: "Choix",
    choicesOrder: "Ordre des choix",
    choicesByUrl: "Choix par API",
    otherText: "Autre texte",
    otherErrorText: 'Texte d\'erreur champ "Autre"',
    storeOthersAsComment: "Sauvegarder choix autre comme commentaire",
    label: "Intitulé",
    showTitle: "Afficher le titre",
    valueTrue: "Valeur vrai",
    valueFalse: "Valeur faux",
    cols: "Colonnes",
    rows: "Nombre de lignes",
    placeholder: "Placeholder (indice dans le champ)",
    optionsCaption: "Texte par défaut",
    expression: "Expression",
    format: "Format",
    displayStyle: "Style d'affichage",
    currency: "Monnaie",
    useGrouping: "Utiliser les groupes",
    showPreview: "Voir la prévisualisation",
    allowMultiple: "Autoriser multiples",
    imageHeight: "Hauteur de l'image",
    imageWidth: "Largeur de l'image",
    storeDataAsText: "Stocker les données comme du texte",
    maxSize: "Taille maximum",
    html: "HTML",
    columns: "Colonnes",
    cells: "Cellules",
    horizontalScroll: "Scroll horizontal",
    cellType: "Type de cellule",
    columnColCount: "Nombre de colonnes",
    columnMinWidth: "Largeur minimale des colonnes",
    rowCount: "Nombre de lignes",
    minRowCount: "Nombre de lignes minimum",
    maxRowCount: "Nombre de lignes maximum",
    keyName: "Nom de la clé",
    keyDuplicationError: "Erreur de clés multiples",
    confirmDelete: "Confirmation de suppression",
    confirmDeleteText: "Texte de confirmation de suppression",
    addRowText: "Bouton ajouter une ligne",
    removeRowText: "Bouton supprimer une ligne",
    items: "Items",
    itemSize: "Nombre maximum de caractères",
    colCount: "Nombre de colonnes",
    templateTitle: "Titre de gabarit",
    templateDescription: "Description du gabarit",
    allowAddPanel: "Autoriser l'ajout de panneau",
    allowRemovePanel: "Autoriser la suppression de panneau",
    panelCount: "Nombre de panneaux",
    minPanelCount: "Nombre minimum de panneaux",
    maxPanelCount: "Nombre maximum de panneaux",
    panelsState: "État des panneaux",
    panelAddText: "Texte d'ajout des panneaux",
    panelRemoveText: "Texte de suppression des panneaux",
    panelPrevText: "Texte panneau précédent",
    panelNextText: "Texte panneau suivant",
    showQuestionNumbers: "Numérotation des questions",
    showRangeInProgress: "Afficher la progression",
    renderMode: "Mode de rendu",
    templateTitleLocation: "Emplacement du titre de gabarit",
    rateValues: "Barème",
    rateMin: "Valeur minimum",
    rateMax: "Valeur maximum",
    rateStep: "Pas",
    minRateDescription: "Description note minimum",
    maxRateDescription: "Description note maximum",
    inputType: "Type de champ",
    size: "Nombre maximum de caractères",
    focusFirstQuestionAutomatic: "Focus automatique sur la première question",
    completedHtml: "HTML questionnaire finalisé",
    completedBeforeHtml: "HTML avant complétion du questionnaire",
    loadingHtml: "HTML de chargement",
    triggers: "Déclencheurs",
    cookieName: "Nom du cookie",
    sendResultOnPageNext: "Envoyer les résultats au changement de page",
    showNavigationButtons: "Boutons de navigation",
    showPrevButton: "Afficher le bouton précédent",
    showPageTitles: "Titre des pages",
    showCompletedPage: "Voir la page formulaire complété ?",
    showPageNumbers: "Numérotation des pages",
    questionErrorLocation: "Emplacement des erreurs",
    showProgressBar: "Barre de progression",
    mode: "Mode d'affichage",
    goNextPageAutomatic: "Aller à la page suivante automatiquement",
    clearInvisibleValues: "Cacher les valeurs invisibles",
    startSurveyText: "Texte de démarrage du questionnaire",
    pagePrevText: "Bouton page précédente",
    pageNextText: "Bouton page suivante",
    completeText: "Texte questionnaire finalisé",
    requiredText: "Texte pour les champs obligatoires",
    questionStartIndex: "Index de numérotation des questions",
    questionTitleTemplate: "Template d'affichage des questions",
    firstPageIsStarted: "Commence à la première page",
    isSinglePage: "Affiché sur une page",
    maxTimeToFinishPage: "Temps maximum pour finir la page",
    showTimerPanel: "Afficher le panneau chronomètre",
    showTimerPanelMode: "Mode d'affichage du panneau chronomètre",
    indent: "Indentation",
    isAllRowRequired: "Toutes les lignes sont-elle obligatoires ?",
    locale: "Langue",
    widthMode: "Mode de largeur",
    imageFit: "à la taille de l'image"
  },
};

editorLocalization.locales["fr"] = frenchTranslation;
