//There 492 untranslated keys. You can find them in uncommented lines.
import { editorLocalization } from "survey-creator-core";

export let svStrings = {
  // survey templates
  survey: {
    edit: "Redigera",
    //externalHelpLink: "Watch and learn how to create surveys",
    //externalHelpLinkUrl: "https://www.youtube.com/channel/UCH2ru9okIcooNZfpIbyq4qQ?view_as=subscriber",
    dropQuestion: "Dra och släpp en fråga från Verktygslistan till vänster.",
    //addLogicItem: "Create a rule to customize the flow of the survey.",
    copy: "Kopiera",
    //duplicate: "Duplicate",
    addToToolbox: "Lägg till Verktygslistan",
    deletePanel: "Radera Panel",
    deleteQuestion: "Radera Fråga",
    convertTo: "Konvertera till",
    drag: "Dra element"
  },
  // Question types
  qt: {
    default: "Standard",
    checkbox: "Checkbox",
    comment: "Kommentar",
    imagepicker: "Bild-väljare",
    //ranking: "Ranking",
    //image: "Image",
    dropdown: "Rullgardinsmeny",
    //tagbox: "Tag Box",
    file: "Fil",
    html: "Html",
    matrix: "Matris (enkel val)",
    matrixdropdown: "Matris(flera val)",
    matrixdynamic: "Matris (dynamiska rader)",
    multipletext: "Flera texter",
    panel: "Panel",
    paneldynamic: "Panel (dynamisk panel)",
    radiogroup: "Radiogrupper",
    rating: "Rankning",
    text: "Enkel text",
    boolean: "Boolean",
    expression: "Formel",
    //signaturepad: "Signature Pad",
    //buttongroup: "Button Group"
  },
  // Strings in SurveyJS Creator
  ed: {
    defaultLocale: "Standard ({0})",
    survey: "Enkät",
    settings: "Enkät inställningar",
    //settingsTooltip: "Open settings",
    //surveySettings: "Survey Settings",
    //surveySettingsTooltip: "Open survey settings",
    //showPanel: "Show Panel",
    //hidePanel: "Hide Panel",
    //prevSelected: "Select previous",
    //nextSelected: "Select next",
    //surveyTypeName: "Survey",
    //pageTypeName: "Page",
    //panelTypeName: "Panel",
    //questionTypeName: "Question",
    //columnTypeName: "Column",
    addNewPage: "Lägg till en ny sida",
    moveRight: "Scrolla till höger",
    moveLeft: "Scrolla till vänster",
    deletePage: "Radera sida",
    editPage: "Redigera sida",
    edit: "Redigera",
    newPageName: "sida",
    newQuestionName: "fråga",
    newPanelName: "panel",
    //newTextItemName: "text",
    testSurvey: "Test enkät",
    //defaultV2Theme: "Default",
    //modernTheme: "Modern",
    //defaultTheme: "Default (legacy)",
    testSurveyAgain: "Testa enkät igen",
    testSurveyWidth: "Enkät bredd: ",
    //navigateToMsg: "You had to navigate to",
    //logic: "Logic",
    embedSurvey: "Integrerad Enkät",
    translation: "Översättning",
    saveSurvey: "Spara Enkät",
    //saveSurveyTooltip: "Save Survey",
    designer: "Enkät Designer",
    jsonEditor: "JSON Redigering",
    //jsonHideErrors: "Hide errors",
    //jsonShowErrors: "Show errors",
    undo: "Ångra",
    redo: "Göra om",
    //undoTooltip: "Undo last change",
    //redoTooltip: "Redo the change",
    //showMoreChoices: "Show more",
    //showLessChoices: "Show less",
    //copy: "Copy",
    //cut: "Cut",
    //paste: "Paste",
    //copyTooltip: "Copy selection to clipboard",
    //cutTooltip: "Cut selection to clipboard",
    //pasteTooltip: "Paste from clipboard",
    options: "Alternativ",
    generateValidJSON: "Generera giltig JSON",
    generateReadableJSON: "Generera läsbar JSON",
    toolbox: "Verktygslista",
    //"property-grid": "Properties",
    //propertyGridFilteredTextPlaceholder: "Type to search...",
    toolboxGeneralCategory: "Generellt",
    //toolboxChoiceCategory: "Choice Questions",
    //toolboxTextCategory: "Text Input Questions",
    //toolboxContainersCategory: "Containers",
    //toolboxMatrixCategory: "Matrix Questions",
    //toolboxMiscCategory: "Misc",
    correctJSON: "Var vänligen korrigera JSON.",
    surveyResults: "Enkät resultat: ",
    surveyResultsTable: "Som tabell",
    surveyResultsJson: "Som JSON",
    resultsTitle: "Frågetitel",
    resultsName: "Frågenamn",
    resultsValue: "Resultat värde",
    resultsDisplayValue: "Visnings värde",
    modified: "Ändrat",
    saving: "Sparar",
    saved: "Sparat",
    //propertyEditorError: "Error",
    saveError: "Fel! Innehållet i enkäten är inte sparat.",
    //translationPropertyGridTitle: "Language Settings",
    //translationLanguages: "Languages",
    translationAddLanguage: "Välj språk för oversättning",
    translationShowAllStrings: "Visa alla strängar",
    //translationShowUsedStringsOnly: "Used Strings Only",
    translationShowAllPages: "Visa alla sidor",
    translationNoStrings: "Inga strängar är översatta. Vänligen ändra filtret.",
    translationExportToSCVButton: "Exportera till CSV",
    translationImportFromSCVButton: "Importera från CSV",
    translationMergeLocaleWithDefault: "Mergea {0} med standard språk",
    //translationPlaceHolder: "Translation...",
    //bold: "Bold",
    //italic: "Italic",
    //underline: "Underline",
    //addNewQuestion: "Add Question",
    //selectPage: "Select page...",
    //htmlPlaceHolder: "HTML content will be here.",
    //panelPlaceHolder: "Drop a question from the toolbox here.",
    //surveyPlaceHolder: "The survey is empty. Drag an element from the toolbox or click the button below.",
    //addNewTypeQuestion: "Add {0}", //{0} is localizable question type
    //chooseLogoPlaceholder: "[LOGO]",
    lg: {
      //addNewItem: "Add New Rule",
      //empty_tab: "Create a rule to customize the flow of the survey.",
      //page_visibilityName: "Show (hide) page",
      //page_enableName: "Enable (disable) page",
      //panel_visibilityName: "Show (hide) panel",
      //panel_enableName: "Enable (disable) panel",
      //question_visibilityName: "Show (hide) question",
      //question_enableName: "Enable (disable) question",
      //question_requireName: "Make question required",
      //column_visibilityName: "Show (hide) column",
      //column_enableName: "Enable (disable) column",
      //column_requireName: "Make column required",
      //trigger_completeName: "Complete survey",
      //trigger_setvalueName: "Set answer",
      //trigger_copyvalueName: "Copy answer",
      //trigger_skipName: "Skip to question",
      //trigger_runExpressionName: "Run expression",
      //completedHtmlOnConditionName: "Set \"Survey Complete\" page markup",
      //page_visibilityDescription: "Make the page visible when the logic expression returns true. Otherwise keep it invisible.",
      //panel_visibilityDescription: "Make the panel visible when the logic expression returns true. Otherwise keep it invisible.",
      //panel_enableDescription: "Make the panel, and all elements inside it, enable when the logic expression returns true. Otherwise keep them disabled.",
      //question_visibilityDescription: "Make the question visible when the logic expression returns true. Otherwise keep it invisible.",
      //question_enableDescription: "Make the question enable when the logic expression returns true. Otherwise keep it disabled.",
      //question_requireDescription: "Question becomes required when the logic expression returns true.",
      //trigger_completeDescription: "When the logic expression returns true then the survey becomes completed and an end-user see the 'Thank you page'.",
      //trigger_setvalueDescription: "When question values, that are used in the logic expression, are changed and the logic expression returns true, then the value is set to the selected question.",
      //trigger_copyvalueDescription: "When question values, that are used in the logic expression, are changed and the logic expression returns true, then the value of one selected question is copied to another selected question.",
      //trigger_skipDescription: "When the logic expression returns true then the survey skip to / focus the selected question.",
      //trigger_runExpressionDescription: "When the logic expression returns true, then the custom expression is performed. You may optionally set this expression result into the selected question",
      //completedHtmlOnConditionDescription: "If the logic expression returns true, then the default text for the 'Thank you page' is changed to the given one.",
      //itemExpressionText: "When expression: '{0}' returns true", //{0} - the expression
      //itemEmptyExpressionText: "New rule",
      //page_visibilityText: "make page {0} visible", //{0} page name
      //panel_visibilityText: "make panel {0} visible", //{0} panel name
      //panel_enableText: "make panel {0} enable", //{0} panel name
      //question_visibilityText: "make question {0} visible", //{0} question name
      //question_enableText: "make question {0} enable", //{0} question name
      //question_requireText: "make question {0} required", //{0} question name
      //column_visibilityText: "make column {0} of question {1} visible", //{0} column name, {1} question name
      //column_enableText: "make column {0} of question {1} enable", //{0} column name, {1} question name
      //column_requireText: "make column {0} of question {1} required", //{0} column name, {1} question name
      //trigger_completeText: "survey becomes completed",
      //trigger_setvalueText: "set into question: {0} value {1}", //{0} question name, {1} setValue
      //trigger_copyvalueText: "copy into question: {0} value from question {1}", //{0} and {1} question names
      //trigger_skipText: "survey skip to the question {0}", //{0} question name
      //trigger_runExpressionText1: "run expression: '{0}'", //{0} the expression
      //trigger_runExpressionText2: " and set its result into question: {0}", //{0} question name
      //completedHtmlOnConditionText: "show custom text for the 'Thank you page'.",
      //showAllQuestions: "All Questions",
      //showAllActionTypes: "All Action Types",
      //conditions: "Condition(s)",
      //actions: "Action(s)",
      //expressionEditorTitle: "Define condition(s)",
      //actionsEditorTitle: "Define action(s)",
      //deleteAction: "Delete Action",
      //addNewAction: "Add Action",
      //selectedActionCaption: "Select action...",
      //expressionInvalid: "The logic expression is empty or invalid. Please correct it.",
      //noActionError: "Please, add at least one action.",
      //actionInvalid: "Please, fix problems in your action(s).",
      //expressionSetup: "",
      //actionsSetup: ""
    }
  },
  // Property Editors
  pe: {
    apply: "Faställ",
    ok: "OK",
    //save: "Save",
    //clear: "Clear",
    //saveTooltip: "Save",
    cancel: "Avbryt",
    //set: "Set",
    reset: "Återställ",
    //change: "Change",
    //refresh: "Refresh",
    close: "Stäng",
    delete: "Radera",
    //add: "Add",
    addNew: "Lägg till ny",
    addItem: "Klicka för att lägga till...",
    //removeItem: "Click to remove the item...",
    //dragItem: "Drag the item",
    //addOther: "Other",
    //addSelectAll: "Select All",
    //addNone: "None",
    removeAll: "Ta bort allt",
    edit: "Redigera",
    //back: "Return without saving",
    //backTooltip: "Return without saving",
    //saveAndBack: "Save and return",
    //saveAndBackTooltip: "Save and return",
    //doneEditing: "Done",
    editChoices: "Redigera val",
    //showChoices: "Show Choices",
    move: "Flytta",
    empty: "<tom>",
    //emptyValue: "Value is empty",
    fastEntry: "Snabb ifyllning",
    //fastEntryNonUniqueError: "Value '{0}' is not unique",
    //fastEntryChoicesCountError: "Please limit the number of items from {0} to {1}",
    //fastEntryPlaceholder: "You can set data in the following format:\nvalue1|text\nvalue2",
    formEntry: "Ifyllning i enkäten",
    testService: "Testa tjänsten",
    //itemSelectorEmpty: "Please select the element",
    //conditionActionEmpty: "Please select the action",
    conditionSelectQuestion: "Välj fråga...",
    //conditionSelectPage: "Select page...",
    //conditionSelectPanel: "Select panel...",
    conditionValueQuestionTitle: "Vänligen skriv in/välj värdet",
    expressionHelp: "Var vänligen skriv in ett uttryck.  Du kan använda måsvingar för att få tillgång till det sparade värdet: '{question1} + {question2}', '({price}*{quantity}) * (100 - {discount})'",
    aceEditorHelp: "Tryck ctrl+mellanslag för att få en ledtråd",
    aceEditorRowTitle: "Nuvarande rad",
    aceEditorPanelTitle: "Nuvarande panel",
    showMore: "För mer detaljer - se dokumentationen",
    assistantTitle: "Tillgängliga frågor:",
    cellsEmptyRowsColumns: "Det bör vara minst 1 kolumn eller rad",
    //showPreviewBeforeComplete: "Preview answers before submitting the survey",
    propertyIsEmpty: "Vänligen fyll i ett värde",
    //propertyIsNoUnique: "Please enter a unique value",
    //propertyNameIsNotUnique: "Please enter a unique name",
    //listIsEmpty: "No items have been added yet",
    //"listIsEmpty@choices": "No choices have been added yet",
    //"addNew@choices": "Add a choice",
    //expressionIsEmpty: "Expression is empty",
    value: "Värde",
    text: "Text",
    rowid: "Rad ID",
    imageLink: "Bild länk",
    columnEdit: "Redigera kolumn: {0}",
    itemEdit: "Redigera element: {0}",
    url: "URL",
    path: "Sökväg",
    valueName: "Värde namn",
    choicesbyurl: {
      //valueName: "Get values from the following JSON field"
    },
    titleName: "Titel namn",
    //imageLinkName: "Get image URLs from the following JSON field",
    //allowEmptyResponse: "Allow empty response",
    //titlePlaceholder: "Title",
    //surveyTitlePlaceholder: "Survey Title",
    //pageTitlePlaceholder: "Page {num}",
    //descriptionPlaceholder: "Description",
    //surveyDescriptionPlaceholder: "Description",
    //pageDescriptionPlaceholder: "Description",
    showOtherItem: "Har annat element",
    otherText: "Annat",
    //showNoneItem: "Allow the None option",
    //noneText: "None option text",
    //showSelectAllItem: "Allow the Select All option",
    //selectAllText: "Select All option text",
    //choicesMin: "Minimum value for auto-generated items",
    //choicesMax: "Maximum value for auto-generated items",
    //choicesStep: "Step for auto-generated items",
    name: "Namn",
    title: "Titel",
    cellType: "Cell typ",
    colCount: "Antal kolumner",
    choicesOrder: "Välj ordning på valet",
    visible: "Synlig?",
    isRequired: "Nödvändig?",
    //isAllRowRequired: "Require answer for all rows",
    //requiredErrorText: "\"Required\" error message",
    startWithNewLine: "Starta på en ny rad?",
    rows: "Antal rader",
    //cols: "Columns",
    placeholder: "Mata in i fältet",
    showPreview: "Förhandsvinsning av bild?",
    storeDataAsText: "Lagra filinnehållet i JSON som text",
    maxSize: "Max filstorlek i bytes",
    imageHeight: "Bild höjd",
    imageWidth: "Bild bredd",
    rowCount: "Antal rader",
    columnLayout: "Stil på kolumn",
    addRowLocation: "Lägg till radknapp plats",
    addRowText: "Lägg till knapp text",
    removeRowText: "Ta bort rad knapp text",
    //rateMin: "Minimum rate value",
    //rateMax: "Maximum rate value",
    //rateStep: "Rate step",
    minRateDescription: "Minsta betyg beskrivning",
    maxRateDescription: "Maximala betyg beskrivning",
    inputType: "Indata typ",
    optionsCaption: "Text för alternativ",
    defaultValue: "Standard värde",
    cellsDefaultRow: "Standard cell texter",
    surveyEditorTitle: "Redigera schema inställningar",
    qEditorTitle: "Redigera: {0}",
    maxLength: "Max längd",
    //buildExpression: "Build",
    //editExpression: "Edit",
    //remove: "Remove",
    //addCondition: "Add Condition",
    //emptyLogicPopupMessage: "Select a question to start configuring conditions.",
    //if: "If",
    //setToName: "Target question",
    //fromName: "Question to copy answer from",
    //gotoName: "Question to skip to",
    //ruleIsNotSet: "Rule is incorrect",
    //includeIntoResult: "Include into survey results",
    showTitle: "Visa/dölj titel",
    //expandCollapseTitle: "Expand/collapse title",
    locale: "Standard språk",
    //simulator: "Select device type",
    //landscapeOrientation: "Switch to landscape orientation",
    //portraitOrientation: "Switch to portrait orientation",
    mode: "Läge (redigera/läsa enbart)",
    clearInvisibleValues: "Rensa osynliga värden",
    cookieName: "Kaknamn (för att inaktivera kör enkäten två gånger lokalt)",
    sendResultOnPageNext: "Skicka enkät resultatet till nästa sida",
    storeOthersAsComment: "Lagra 'andra' värden i ett separat fält",
    showPageTitles: "Visa sidtitel",
    showPageNumbers: "Visa sidnummer",
    pagePrevText: "Föregående",
    pageNextText: "Nästa",
    completeText: "Färdig",
    //previewText: "Preview Answers button text",
    //editText: "Edit Answer button text",
    startSurveyText: "Start knapp text",
    showNavigationButtons: "Visa navigationsknappar (standard navigering)",
    showPrevButton: "Visa föregående knapp (användaren kan gå återgå till föregående sida)",
    firstPageIsStarted: "Den första sidan i enkäten är startsidan.",
    showCompletedPage: "Visa den slutförda sidan på slutet (completedHtml)",
    goNextPageAutomatic: "Vid besvarande av alla frågor, gå till nästa sida automatiskt",
    showProgressBar: "Visa händelsförlopp",
    questionTitleLocation: "Fråga titel placering",
    requiredText: "Var vänlig skriv en text",
    questionStartIndex: "Fråga start index (1, 2 eller 'A', 'a')",
    showQuestionNumbers: "Visa frågenummer",
    questionTitleTemplate: "Fråga titel mall, standard är: '{no}. {require} {title}'",
    questionErrorLocation: "Fråga fel placerad",
    focusFirstQuestionAutomatic: "Fokusera på första frågan vid ändring av sidan",
    questionsOrder: "Element ordning på sidan",
    maxTimeToFinish: "Max tid för att slutföra enkäten",
    maxTimeToFinishPage: "Max tid för att göra färdigt en sida i enkäten",
    page: {
      //maxTimeToFinish: "Time limit to finish the page (in seconds)"
    },
    question: {
      //page: "Parent page"
    },
    showTimerPanel: "Visa tidtagning",
    showTimerPanelMode: "Visa tidtagning läge",
    renderMode: "Rendering läge",
    allowAddPanel: "Tillåt att lägga till panel",
    allowRemovePanel: "Tillåt att ta bort panel",
    //noEntriesText: "Empty entries text",
    panelAddText: "Lägg till panel text",
    panelRemoveText: "Ta bort panel text",
    isSinglePage: "Visa alla element på en sida",
    //html: "HTML markup",
    //expression: "Expression",
    //setValue: "Answer",
    //dataFormat: "Image format",
    //allowAddRows: "Allow adding rows",
    //allowRemoveRows: "Allow removing rows",
    //allowRowsDragAndDrop: "Allow row drag and drop",
    //responsiveImageSizeHelp: "Does not apply if you specify the exact image width or height.",
    //minImageWidth: "Minimum image width",
    //maxImageWidth: "Maximum image width",
    //minImageHeight: "Minimum image height",
    //maxImageHeight: "Maximum image height",
    //minValue: "Minimum value",
    //maxValue: "Maximum value",
    //minLength: "Minimum length (in characters)",
    //allowDigits: "Allow digits",
    //minCount: "Minimum count",
    //maxCount: "Maximum count",
    //regex: "Regular expression",
    surveyvalidator: {
      //text: "Error message",
      //expression: "Validation expression"
    },
    //totalText: "Total row text",
    //totalType: "Total type",
    //totalExpression: "Total expression",
    //totalDisplayStyle: "Total value display style",
    //totalCurrency: "Currency",
    //totalFormat: "Formatted string",
    //logo: "Logo (URL or base64-encoded string)",
    //questionsOnPageMode: "Survey structure",
    //maxTextLength: "Maximum answer length (in characters)",
    //maxOthersLength: "Maximum comment length (in characters)",
    //autoGrowComment: "Auto-expand comment area if necessary",
    //textUpdateMode: "Update text question value",
    //focusOnFirstError: "Set focus on the first invalid answer",
    //checkErrorsMode: "Run validation",
    //navigateToUrl: "Navigate to URL",
    //navigateToUrlOnCondition: "Dynamic URL",
    //completedBeforeHtml: "Markup to show if the user already filled out this survey",
    //completedHtml: "Survey Complete page markup",
    //completedHtmlOnCondition: "Dynamic Survey Complete page markup",
    //loadingHtml: "Markup to show while survey model is loading",
    //commentText: "Comment area text",
    //autocomplete: "Autocomplete type",
    //labelTrue: "\"True\" label",
    //labelFalse: "\"False\" label",
    //allowClear: "Show the Clear button",
    //displayStyle: "Value display style",
    //format: "Formatted string",
    //maximumFractionDigits: "Maximum fractional digits",
    //minimumFractionDigits: "Minimum fractional digits",
    //useGrouping: "Display grouping separators",
    //allowMultiple: "Allow multiple files",
    //allowImagesPreview: "Preview images",
    //acceptedTypes: "Accepted file types",
    //waitForUpload: "Wait for the upload to complete",
    //needConfirmRemoveFile: "Confirm file deletion",
    //detailPanelMode: "Detail panel location",
    //minRowCount: "Minimum row count",
    //maxRowCount: "Maximum row count",
    //confirmDelete: "Confirm row deletion",
    //confirmDeleteText: "Confirmation message",
    paneldynamic: {
      //confirmDelete: "Confirm panel deletion"
    },
    //panelCount: "Initial panel count",
    //minPanelCount: "Minimum panel count",
    //maxPanelCount: "Maximum panel count",
    //panelsState: "Inner panel expand state",
    //templateDescription: "Description template",
    //templateTitle: "Title template",
    //panelPrevText: "Previous Panel button tooltip",
    //panelNextText: "Next Panel button tooltip",
    //showRangeInProgress: "Show progress bar",
    //templateTitleLocation: "Question title location",
    //panelRemoveButtonLocation: "Remove Panel button location",
    //hideIfRowsEmpty: "Hide the question if there are no rows",
    //hideColumnsIfEmpty: "Hide columns if there are no rows",
    //rateValues: "Custom rate values",
    //hideIfChoicesEmpty: "Hide the question if it contains no choices",
    //hideNumber: "Hide question number",
    //minWidth: "Minimum width (in CSS-accepted values)",
    //maxWidth: "Maximum width (in CSS-accepted values)",
    //width: "Width (in CSS-accepted values)",
    //showHeader: "Show column headers",
    //horizontalScroll: "Show horizontal scrollbar",
    //columnMinWidth: "Minimum column width (in CSS-accepted values)",
    //rowTitleWidth: "Row header width (in CSS-accepted values)",
    //valueTrue: "\"True\" value",
    //valueFalse: "\"False\" value",
    //minErrorText: "\"Value is below minimum\" error message",
    //maxErrorText: "\"Value exceeds maximum\" error message",
    //otherErrorText: "\"Empty comment\" error message",
    //keyDuplicationError: "\"Non-unique key value\" error message",
    //maxSelectedChoices: "Maximum selected choices",
    //showClearButton: "Show the Clear button",
    //showNumber: "Show panel number",
    //logoWidth: "Logo width (in CSS-accepted values)",
    //logoHeight: "Logo height (in CSS-accepted values)",
    //readOnly: "Read-only",
    //enableIf: "Editable if",
    //emptyRowsText: "\"No rows\" message",
    //size: "Input size (in characters)",
    //separateSpecialChoices: "Separate special choices (None, Other, Select All)",
    //choicesFromQuestion: "Copy choices from the following question",
    //choicesFromQuestionMode: "Which choices to copy?",
    //showCommentArea: "Show the comment area",
    //commentPlaceholder: "Comment area placeholder",
    //displayRateDescriptionsAsExtremeItems: "Display rate descriptions as extreme values",
    //rowsOrder: "Row order",
    //columnsLayout: "Column layout",
    //columnColCount: "Nested column count",
    //state: "Panel expand state",
    //correctAnswer: "Correct Answer",
    //defaultPanelValue: "Default Values",
    //cells: "Cell Texts",
    //keyName: "Key column",
    itemvalue: {
      //text: "Alt text"
    },
    //logoPosition: "Logo position",
    //addLogo: "Add logo...",
    //changeLogo: "Change logo...",
    logoPositions: {
      //none: "Remove logo",
      //left: "Left",
      //right: "Right",
      //top: "On the top",
      //bottom: "In the bottom"
    },
    tabs: {
      general: "Generellt",
      fileOptions: "Alternativ",
      html: "Html-editor",
      columns: "Kolumner",
      rows: "Rader",
      choices: "Välj",
      items: "Element",
      visibleIf: "Synlig",
      enableIf: "Tillgänlig",
      //requiredIf: "Required If",
      rateValues: "Ordna värden",
      choicesByUrl: "Välj från webben",
      matrixChoices: "Standard val",
      multipleTextItems: "Text indata",
      //numbering: "Numbering",
      validators: "Valideringar",
      navigation: "Navigering",
      question: "Fråga",
      //pages: "Pages",
      timer: "Tidtagare/Quiz",
      //calculatedValues: "Calculated Values",
      triggers: "Triggare",
      templateTitle: "Mall titel",
      //totals: "Totals",
      //logic: "Logic",
      //layout: "Layout",
      //data: "Data",
      //validation: "Validation",
      //cells: "Cell Texts",
      //showOnCompleted: "Survey Complete",
      //logo: "Logo in Survey Title",
      //slider: "Slider",
      //expression: "Expression",
      //others: "Others"
    },
    editProperty: "Redigera egenskap '{0}'",
    items: "[ Element: {0} ]",
    //choicesVisibleIf: "Choices are visible if",
    //choicesEnableIf: "Choices are selectable if",
    //columnsEnableIf: "Columns are visible if",
    //rowsEnableIf: "Rows are visible if",
    //indent: "Add indents",
    panel: {
      //indent: "Add outer indents"
    },
    //innerIndent: "Add inner indents",
    //defaultValueFromLastRow: "Take default values from the last row",
    //defaultValueFromLastPanel: "Take default values from the last panel",
    enterNewValue: "Vänligen skriv in ett värde.",
    noquestions: "Det finns ingen fråga i enkäten.",
    createtrigger: "Vänligen skapa en trigger",
    //titleKeyboardAdornerTip: "Press enter button to edit",
    //keyboardAdornerTip: "Press enter button to edit item, press delete button to delete item, press alt plus arrow up or arrow down to move item",
    triggerOn: "På ",
    triggerMakePagesVisible: "Synligör sidor:",
    triggerMakeQuestionsVisible: "Synligör element:",
    triggerCompleteText: "Avsluta enkät vid verkställ.",
    triggerNotSet: "Trigger är inte satt",
    triggerRunIf: "Kör ",
    triggerSetToName: "Ändra värden av: ",
    triggerFromName: "Kopiera värden från: ",
    triggerRunExpression: "Kör detta uttryck:",
    triggerSetValue: "till: ",
    //triggerGotoName: "Go to the question",
    triggerIsVariable: "Var vänligen skriv ett giltigt uttryck.",
    //triggerRunExpressionEmpty: "Please enter a valid expression",
    //emptyExpressionPlaceHolder: "Type expression here...",
    //noFile: "No file choosen",
    //clearIfInvisible: "Clear the value if the question becomes hidden",
    //valuePropertyName: "Value property name",
    //searchEnabled: "Enable search",
    //hideSelectedItems: "Hide selected items",
    //signatureWidth: "Signature width",
    //signatureHeight: "Signature height",
    //verticalAlign: "Vertical alignment",
    //alternateRows: "Alternate rows",
    //columnsVisibleIf: "Columns are visible if",
    //rowsVisibleIf: "Rows are visible if",
    //otherPlaceholder: "Comment area placeholder"
  },
  // Property values
  pv: {
    inherit: "inherit",
    show: "show",
    hide: "hide",
    default: "default",
    initial: "initial",
    random: "random",
    collapsed: "collapsed",
    expanded: "expanded",
    none: "none",
    asc: "ascending",
    desc: "descending",
    indeterminate: "indeterminate",
    firstExpanded: "firstExpanded",
    off: "off",
    //onpanel: "Start on each panel",
    onPanel: "onPanel",
    onSurvey: "onSurvey",
    list: "list",
    progressTop: "progressTop",
    progressBottom: "progressBottom",
    progressTopBottom: "progressTopBottom",
    horizontal: "horizontal",
    vertical: "vertical",
    top: "top",
    bottom: "bottom",
    topBottom: "top and bottom",
    //both: "Both",
    left: "left",
    //right: "Right",
    hidden: "hidden",
    on: "on",
    onPage: "onPage",
    edit: "edit",
    display: "display",
    onComplete: "onComplete",
    onHidden: "onHidden",
    //onHiddenContainer: "When the question or its panel/page becomes hidden",
    clearInvisibleValues: {
      //none: "Never"
    },
    all: "all",
    page: "page",
    survey: "survey",
    onNextPage: "onNextPage",
    onValueChanged: "onValueChanged",
    //onValueChanging: "Before an answer is changed",
    //standard: "Original structure",
    //singlePage: "All questions on a single page",
    //questionPerPage: "Each question on an individual page",
    //noPreview: "No preview",
    //showAllQuestions: "Show all questions",
    //showAnsweredQuestions: "Show answered questions only",
    //pages: "Completed pages",
    //questions: "Answered questions",
    //requiredQuestions: "Answered required questions",
    //correctQuestions: "Valid answers",
    //buttons: "Completed pages (button UI)",
    //underInput: "Under the input",
    //underTitle: "Under the title",
    //onBlur: "On blur",
    //onTyping: "While typing",
    //underRow: "Under the row",
    //underRowSingle: "Under the row, only one panel is visible",
    showNavigationButtons: {
      //none: "Hidden"
    },
    showProgressBar: {
      //off: "Hidden"
    },
    showTimerPanel: {
      //none: "Hidden"
    },
    showTimerPanelMode: {
      //all: "Both"
    },
    detailPanelMode: {
      //none: "Hidden"
    },
    addRowLocation: {
      //default: "Depends on matrix layout"
    },
    panelsState: {
      //default: "Users cannot expand or collapse panels",
      //collapsed: "All panels are collapsed",
      //expanded: "All panels are expanded"
    },
    widthMode: {
      //auto: "Auto",
      //static: "Static",
      //responsive: "Responsive"
    },
    imageFit: {
      //none: "None",
      //contain: "Contain",
      //cover: "Cover",
      //fill: "Fill"
    },
    contentMode: {
      //auto: "Auto",
      //image: "Image",
      //video: "Video",
      //youtube: "YouTube"
    },
    displayMode: {
      //auto: "Auto",
      //buttons: "Buttons",
      //dropdown: "Dropdown"
    }
  },
  // Operators
  op: {
    empty: "is empty",
    notempty: "is not empty",
    equal: "equals",
    notequal: "not equals",
    contains: "contains",
    notcontains: "not contains",
    //anyof: "Any of",
    //allof: "All of",
    greater: "greater",
    less: "less",
    greaterorequal: "greater or equals",
    lessorequal: "less or equals"
  },
  // Embed window
  ew: {
    angular: "Använd Angular version",
    jquery: "Använd jQuery version",
    knockout: "Använd Knockout version",
    react: "Använd React version",
    vue: "Använd Vue version",
    bootstrap: "För bootstrap framework",
    //modern: "Modern theme",
    //default: "Default theme",
    //orange: "Orange theme",
    //darkblue: "Darkblue theme",
    //darkrose: "Darkrose theme",
    //stone: "Stone theme",
    //winter: "Winter theme",
    //winterstone: "Winter-Stone theme",
    showOnPage: "Visa enkät på en sida",
    showInWindow: "Visa enkäten i ett nytt fönster",
    loadFromServer: "Hämta enkäten som JSON från servern",
    titleScript: "Scripts och styles",
    titleHtml: "HTML",
    titleJavaScript: "JavaScript"
  },
  // Preview (Survey)
  ts: {
    selectPage: "Välj sida för att testa den:",
    showInvisibleElements: "Visa osynliga element",
    //hideInvisibleElements: "Hide invisible elements"
  },
  validators: {
    answercountvalidator: "answer count",
    emailvalidator: "e-mail",
    expressionvalidator: "expression",
    numericvalidator: "numeric",
    regexvalidator: "regex",
    textvalidator: "text"
  },
  triggers: {
    completetrigger: "Enkät slutförd",
    setvaluetrigger: "Sätt värde",
    copyvaluetrigger: "Kopiera värde",
    //skiptrigger: "Skip to question",
    runexpressiontrigger: "Kör uttryck",
    visibletrigger: "Ändra synlighet"
  },
  pehelp: {
    //cookieName: "Cookies prevent users from filling out the same survey twice.",
    //format: "Use {0} as a placeholder for the actual value.",
    //totalText: "Visible only when at least one column has Total type or Total expression.",
    //acceptedTypes: "Refer to the [accept](https://www.w3schools.com/tags/att_input_accept.asp) attribute description for more information.",
    //columnColCount: "Applicable only to Radiogroup and Checkbox cell types.",
    //autocomplete: "Refer to the [autocomplete](https://developer.mozilla.org/en-US/docs/Web/HTML/Attributes/autocomplete) attribute description for more information.",
    //valueName: "If you do not set this property, the answer will be stored in a field specified by the Name property.",
    choicesbyurl: {
      //valueName: " "
    },
    //keyName: "If the specified column contains identical values, the survey throws the \"Non-unique key value\" error."
  },
  // Properties
  p: {
    title: {
      name: "title",
      title: "Lämna den tom, ifall det är samma som 'Name'"
    },
    //multiSelect: "Allow multiple selection",
    //showLabel: "Show image captions",
    //value: "Value",
    visibleIf: "visibleIf",
    //attachOriginalItems: "attachOriginalItems",
    //useDisplayValuesInDynamicTexts: "useDisplayValuesInDynamicTexts",
    titleLocation: "titleLocation",
    description: "description",
    //descriptionLocation: "descriptionLocation",
    //defaultValueExpression: "defaultValueExpression",
    //requiredIf: "requiredIf",
    validators: "validators",
    //bindings: "bindings",
    //renderAs: "renderAs",
    currency: "currency",
    //cellHint: "cellHint",
    //isUnique: "isUnique",
    //showInMultipleColumns: "showInMultipleColumns",
    //totalMaximumFractionDigits: "totalMaximumFractionDigits",
    //totalMinimumFractionDigits: "totalMinimumFractionDigits",
    columns: "columns",
    //detailElements: "detailElements",
    choices: "choices",
    //allowAdaptiveActions: "allowAdaptiveActions",
    defaultRowValue: "defaultRowValue",
    //detailPanelShowOnAdding: "detailPanelShowOnAdding",
    //logoFit: "logoFit",
    //pages: "pages",
    //questions: "questions",
    triggers: "triggers",
    //calculatedValues: "calculatedValues",
    //surveyId: "surveyId",
    //surveyPostId: "surveyPostId",
    //surveyShowDataSaving: "surveyShowDataSaving",
    //questionDescriptionLocation: "questionDescriptionLocation",
    //progressBarType: "progressBarType",
    //questionTitlePattern: "questionTitlePattern",
    //widthMode: "widthMode",
    //showBrandInfo: "showBrandInfo",
    choicesByUrl: "choicesByUrl",
    //choicesLazyLoadEnabled: "choicesLazyLoadEnabled",
    //choicesLazyLoadPageSize: "choicesLazyLoadPageSize",
    //inputFieldComponent: "inputFieldComponent",
    //itemComponent: "itemComponent",
    //min: "min",
    //max: "max",
    //minValueExpression: "minValueExpression",
    //maxValueExpression: "maxValueExpression",
    //step: "step",
    //dataList: "dataList",
    itemSize: "itemSize",
    //elements: "elements",
    //content: "content",
    navigationButtonsVisibility: "navigationButtonsVisibility",
    //navigationTitle: "navigationTitle",
    //navigationDescription: "navigationDescription",
    //closeOnSelect: "closeOnSelect",
    //longTap: "longTap",
    //autoGrow: "autoGrow",
    //acceptCarriageReturn: "acceptCarriageReturn",
    //displayMode: "displayMode",
    label: "label",
    //contentMode: "contentMode",
    //imageFit: "imageFit",
    //altText: "altText",
    //height: "height",
    //penColor: "penColor",
    //backgroundColor: "backgroundColor",
    //templateElements: "templateElements",
    //operator: "operator",
    //isVariable: "isVariable",
    //runExpression: "runExpression",
    //showCaption: "showCaption",
    //iconName: "iconName",
    //iconSize: "iconSize"
  }
};
editorLocalization.locales["sv"] = svStrings;
