import { getLocaleStrings } from "survey-creator-core";
export const enStrings = {
  languages: {
    title: "Languages",
    navigationTitle: "Languages",
    description: "Select the language of the Survey Creator UI and target\nlanguages for the survey being configured.",
    creatorUI: "Creator UI language",
    surveyLanguages: "Survey languages",
    searchPlaceholder: "Type to search...",
    translateToEnglish: "Translate Survey language names to English"
  },
  tabs: {
    title: "Configure tabs",
    navigationTitle: "Tabs",
    description: "Select the tabs you want to show, reorder them, change their titles,\nand choose the tab that will be active by default.",
    items: "Visible tabs",
    hiddenItems: "Hidden tabs",
    defaultTab: "Default tab",
    noItemsText: "Drag tabs here to show them",
    noHiddenItemsText: "Drag tabs here to hide them",
    name: "Name",
    titleField: "Title",
    iconName: "Icon name"
  },
  toolbox: {
    title: "Set up the Toolbox",
    navigationTitle: "Toolbox",
    description: "Select the toolbox items you want to show, group them into categories, \nrename them, and change their order if required.",
    toolbox: "Toolbox",
    categories: "Categories",
    noCategoriesText: "No categories",
    noItemsText: "Drag items here to show them",
    noHiddenItemsText: "Drag items here to hide them",
    hiddenItems: "Hidden toolbox items",
    enableGrouping: "Enable grouping",
    showCategoryTitles: "Show category titles",
    categoryName: "Name",
    categoryTitle: "Title",
    tooltip: "Tooltip",
    iconName: "Icon name",
    jsonObject: "JSON object to apply when users select this toolbox item",
    subcategories: "Subcategories",
    convertToSubcategory: "Enable subitems for this question...",
    moveAsSubitem: "Move as a subitem to...",
    addToToolbox: "Add to Toolbox",
    deleteCustomItem: "Delete Custom Item",
    addCustomCategory: "New Category",
    addCustomItem: "New Item",
    addNewItem: "Add a new item",
    addNewSubitem: "Add a new subitem",
    noRowsText: "There are no items",
    newItem: "New item in",
  },
  propertyGrid: {
    title: "Customize the Property Grid",
    navigationTitle: "Property Grid",
    description: "Select an element to customize its settings available in the Property Grid.",
    selectElement: "Select an element to customize its settings available in the Property Grid",
    propertyGrid: "Property Grid",
    noCategoriesText: "No categories",
    noItemsText: "Drag properties here to show them",
    noHiddenItemsText: "Drag properties here to hide them",
    hiddenItems: "Unsorted items",
    categoryName: "Name",
    categoryTitle: "Title",
    iconName: "Icon name",
    name: "Name",
    titleField: "Title",
    descriptionField: "Helper Text",
    addCustomCategory: "Add Custom Category"
  },
  items: {
    addNewItem: "Add a new item",
    addNewSubitem: "Add a new subitem",
    newItem: "New item in",
    addCustomCategory: "New Category",
    newCategory: "New category in",
    moveToCategory: "Move to category...",
    moveToNewCategory: "Move to new category...",
    categoriesLabel: "Categories",
    moveTo: "Move To...",
    removeFrom: "Remove from {0}",
    more: "More",
    restoreToDefault: "Restore",
    edit: "Edit",
    expand: "Expand",
    collapse: "Collapse",
    remove: "Remove",
    add: "Add",
    delete: "Delete"
  },
  editor: {
    title: "Creator Presets",
    presetJson: "Preset JSON:",
    copy: "Copy",
    download: "Download",
    load: "Load",
    saveExit: "Save & Exit",
    back: "Back",
    resetToDefault: "Reset to default",
    resetToDefaults: "All settings restored to default",
    resoredToDefault: "resored to default",
    itemRestoredToDefault: "Item restored to default",
    categoryRestoredToDefault: "Category restored to default",
    edit: "Edit",
    completeText: "Save & Exit",
    pagePrevText: "Back"
  },
  plugin: {
    presetsTab: "Presets",
    creatorPresets: "Creator Presets",
    save: "Save & Exit",
    file: "File",
    import: "Import",
    export: "Export",
    edit: "Edit",
    resetLanguages: "Reset Languages to default",
    resetAll: "Reset all changes",
    resetToDefaults: "Reset {0} to defaults"
  }
};
const locale = getLocaleStrings("en");
locale.presets = enStrings;