import { editorLocalization } from "../editorLocalization";

var frenchTranslation = {
  //Strings in Editor
  ed: {
    addNewPage: "Ajouter une page",
    correctJSON: "SVP corriger le json",
    delSelObject: "Supprimer l'objet sélectionné",
    designer: "Designer de questionnaire",
    embedSurvey: "Intégrer le questionnaire",
    generateReadableJSON: "Générer un JSON lisible",
    generateValidJSON: "Générer un JSON valide",
    jsonEditor: "Editer JSON",
    newPageName: "page",
    newQuestionName: "question",
    options: "Options",
    redo: "Rétablir",
    saveSurvey: "Sauvegarder le questionnaire",
    surveyResults: "Résultat du questionnaire: ",
    testSurvey: "Tester le questionnaire",
    testSurveyAgain: "Tester à nouveau le questionnaire",
    testSurveyWidth: "Largeur du questionnaire: ",
    toolbox: "Boite à outils",
    undo: "Annuler"
  },
  //Embed window
  ew: {
    angular: "Utiliser la version Angular",
    bootstrap: "Pour Bootstrap framework",
    jquery: "Utiliser la version jQuery",
    knockout: "Utiliser la version Knockout",
    loadFromServer: "Charger le JSON du questionnaire depuis un serveur",
    react: "Utiliser la version React",
    showInWindow: "Afficher le questionnaire dans une fenêtre",
    showOnPage: "Afficher le questionnaire dans une page",
    standard: "Pas de bootstrap",
    titleHtml: "HTML",
    titleJavaScript: "JavaScript",
    titleScript: "Scripts et styles",
    vue: "Utiliser la version Vue"
  },
  //Operators
  op: {
    contains: "contient",
    empty: "est vide",
    equal: "égal",
    greater: "supérieur",
    greaterorequal: "supérieur ou égal",
    less: "plus petit",
    lessorequal: "plus petit ou égal",
    notcontains: "ne contient pas",
    notempty: "n'est pas vide",
    notequal: "n'est pas égal"
  },
  //Properties
  p: {
    addRowText: "Bouton ajouter une ligne",
    cellType: "Type de cellule",
    choices: "Choix",
    choicesByUrl: "Choix par API",
    choicesOrder: "Ordre des choix",
    clearInvisibleValues: "Cacher les valeur invisibles",
    colCount: "Nombre de colonnes",
    cols: "Nombre de cols",
    columnColCount: "Nombre de colonnes",
    columnMinWidth: "Largeur minimale des colonnes",
    columns: "Colonnes",
    commentText: "Description champ commentaire",
    completeText: "Texte questionnaire finalisé",
    completedHtml: "Html questionnaire finalisé",
    cookieName: "Nom du cookie",
    edit: "Editer",
    focusFirstQuestionAutomatic:
      "Focus sur la première question automatiquement",
    goNextPageAutomatic: "Aller à la page suivante automatiquement",
    hasComment: "Champs commentaire ?",
    hasOther: "Choix autre ?",
    horizontalScroll: "Scroll horizontal",
    imageHeight: "Hauteur de l 'image",
    imageWidth: "Largeur de l'image",
    indent: "Indentation",
    inputType: "Type de champs",
    isAllRowRequired: "Toutes les lignes sont-elle obligatoires ?",
    isRequired: "Requis ?",
    itemSize: "Nombre maximum de caractères",
    items: "Items",
    locale: "Langue",
    maxRateDescription: "Description note maximum",
    maxSize: "Taille maximum",
    minRateDescription: "Description note minimum",
    minRowCount: "Nombre de ligne minimal",
    mode: "Mode d'affichage",
    name: "Nom",
    optionsCaption: "Texte par défaut",
    otherErrorText: "Texte Erreur champs autre",
    otherText: {
      name: "Text autre",
      title: "Champ commentaire ou choix autre"
    },
    pageNextText: "Bouton page suivante",
    pagePrevText: "Bouton page précédente",
    page_title: { name: "titre", title: "Titre de la page" },
    placeHolder: "PlaceHolder (indice dans le champs)",
    questionStartIndex: "Index de numérotation des question",
    questionTitleLocation: "Emplacement titre question",
    questionTitleTemplate: {
      name: "Template d'affichage des question",
      title: "Exemple: {no}) {title} {require}:"
    },
    rateValues: "Barème",
    removeRowText: "Bouton supprimer une ligne",
    requiredText: "Texte pour les champs requis",
    rowCount: "Nombre de lignes",
    rows: "Nombre de ligne",
    sendResultOnPageNext: "",
    showCompletedPage: "Voir la page formulaire complété ?",
    showNavigationButtons: "Boutons de navigation",
    showPageNumbers: "Numérotation des pages",
    showPageTitles: "Titre des pages",
    showPreview: "Voir la prévisualisation",
    showProgressBar: "Barre de progression",
    showQuestionNumbers: "Numérotation des questions",
    showTitle: "Afficher le titre",
    size: "Nombre maximum de caractères",
    startWithNewLine: "Commencer avec une nouvelle ligne",
    storeDataAsText: "Stocker les données comme du text",
    storeOthersAsComment: "Sauvegarder choix autre comme commentaire",
    surveyId: "Id du questionnaire",
    surveyPostId: "Id POST questionnaire",
    survey_title: { name: "titre", title: "Il sera affiché sur chaque page." },
    title: { name: "Titre", title: 'Laissez vide, si meme texte que le "Nom"' },
    triggers: "Déclencheurs",
    validators: "Validateurs",
    visibleIf: "Visible si ",
    width: "Largeur"
  },
  //Property Editors
  pe: {
    addNew: "Ajouter un nouveau",
    addRowText: "Texte bouton ajouter une ligne",
    apply: "Appliquer",
    cancel: "Annuler",
    cellType: "Type de cellule",
    choicesOrder: "Sélectionner l'ordre des choix",
    close: "Fermer",
    colCount: "Nombre de colonnes",
    columnEdit: "Editer la colonne: {0}",
    createtrigger: "Veuillez créer un déclencheur",
    delete: "Supprimer",
    edit: "Editer",
    editProperty: 'Editer la propriété "{0}"',
    empty: "<vide>",
    enterNewValue: "Veuillez saisir la valeur.",
    expressionHelp:
      'Veuillez entrer une expression booléenne. Elle doit retourner Vrai(true) pour garder la question/page visible. Par exemple: {question1} = "valeur1" or ({question2} = 3 and {question3} < 5)',
    fastEntry: "Ajout rapide",
    formEntry: "Ajout via formulaire",
    hasOther: "Has other item",
    imageHeight: "Hauteur de l'image",
    imageWidth: "Largeur de l'image",
    inputType: "Type de champ",
    isRequired: "Est requis ?",
    items: "[ Elements: {0} ]",
    maxRateDescription: "Description note maximum",
    maxSize: "Taille maximum du fichier en octets",
    minRateDescription: "Description note minimum",
    name: "Nom",
    noquestions: "Il n'y a aucune question dans le questionnaire.",
    ok: "OK",
    optionsCaption: "Texte par défaut",
    placeHolder: "PlaceHolder (indice dans le champs)",
    propertyIsEmpty: "Veuillez entrer une valeur pour la propriété",
    qEditorTitle: "Editer la question: {0}",
    removeAll: "Tout supprimer",
    removeRowText: "Texte bouton supprimer une ligne",
    required: "Requis ?",
    reset: "Réinitialiser",
    rowCount: "Nombre de lignes",
    rows: "Nombre de lignes",
    showPreview: "L'aperçu d'image est-il affiché ?",
    startWithNewLine: "Commencer avec une nouvelle ligne ?",
    storeDataAsText:
      "Stocker le contenu du fichier dans le résultat JSON sous forme de texte",
    tabs: {
      choices: "Choix",
      choicesByUrl: "Choix depuis api web",
      columns: "Colonnes",
      fileOptions: "Options",
      general: "Général",
      html: "Editeur Html",
      matrixChoices: "Choix par defaut",
      multipleTextItems: "Text Inputs",
      rateValues: "Barème",
      rows: "Lignes",
      visibleIf: "Visible Si"
    },
    testService: "Tester le service",
    text: "Texte",
    title: "Titre",
    triggerCompleteText: "Complete the survey if succeed.",
    triggerIsVariable:
      "Ne placez pas la variable dans le résultat du questionnaire.",
    triggerMakePagesVisible: "Rendre les pages visibles:",
    triggerMakeQuestionsVisible: "Rendre les questions visibles:",
    triggerNotSet: "Le déclencheur n'est pas défini",
    triggerOn: "On ",
    triggerRunIf: "Exécuster si",
    triggerSetToName: "Changer la valeur de: ",
    triggerSetValue: "à: ",
    value: "Valeur",
    verbChangePage: "Changer de page ",
    verbChangeType: "Changer le type ",
    visible: "Est visible ?"
  },
  //questionTypes
  qt: {
    checkbox: "Cases à cocher",
    comment: "Commentaire",
    dropdown: "Liste déroulante",
    file: "Fichier",
    html: "Html",
    matrix: "Matice (choix unique)",
    matrixdropdown: "Matrice (choix multiples)",
    matrixdynamic: "Matrice (Lignes dynamiques)",
    multipletext: "champ multilignes",
    radiogroup: "Boutons radio",
    rating: "Evaluation",
    text: "Champ simple"
  },
  survey: {
    addToToolbox: "Ajouter à la boîte à outils",
    copy: "Copier",
    deleteQuestion: "Supprimer la question",
    dropQuestion: "Déposer votre question ici."
  }
};

editorLocalization.locales["fr"] = frenchTranslation;
