//Uncomment this line on creating a translation file
import { editorLocalization, defaultStrings } from "../editorLocalization";

export var ruStrings = {
  // strings for survey templates
  survey: {
    edit: "Редактировать",
    externalHelpLink: "Научиться создавать опросы",
    externalHelpLinkUrl:
      "Https://www.youtube.com/channel/UCH2ru9okIcooNZfpIbyq4qQ?view_as=subscriber",
    dropQuestion: "Пожалуйста, перетяните нужный тип вопроса сюда из панели слева",
    copy: "Копировать",
    addToToolbox: "Добавить к инструментам",
    deletePanel: "Удалить панель",
    deleteQuestion: "Удалить вопрос",
    convertTo: "Преобразовать в",
    drag: "Перетянуть элемент"
  },
  // questionTypes
  qt: {
    default: "По умолчанию",
    checkbox: "Множественный выбор",
    comment: "Комментарий",
    imagepicker: "Выбор изображения",
    dropdown: "Выпадающий список",
    file: "Файл",
    HTML: "Html",
    matrix: "Матрица (единичный выбор)",
    matrixdropdown: "Матрица (множественный выбор)",
    matrixdynamic: "Матрица (динамические ряды)",
    multipletext: "Multiple Text",
    panel: "Группа",
    paneldynamic: "Панель (динамические панели)",
    radiogroup: "Единичный выбор",
    rating: "Рейтинг",
    text: "Текстовый ввод",
    boolean: "Булиевое значение",
    expression: "Выражение (только для чтения)",
    flowPanel: "Панель Flow"
  },
  // Strings in Editor
  ed: {
    defaultLocale: "По умолчанию ({0})",
    survey: "Опрос",
    settings: "Настройки опроса",
    opjectPropertiesHeader: "Дополнительные",
    showObjectProperties: "Показать свойства объекта",
    hideObjectProperties: "Свойства Скрыть объект",
    editSurvey: "Редактировать опрос",
    addNewPage: "Добавить новую страницу",
    moveRight: "Прокрутка вправо",
    moveLeft: "Прокрутка влево",
    deletePage: "Удалить страницу",
    editPage: "Редактировать страницу",
    edit: "Редактировать",
    newPageName: "Страница",
    newQuestionName: "Вопрос",
    newPanelName: "Панель",
    newTextItemName: "Текст",
    testSurvey: "Протестировать опрос",
    testSurveyAgain: "Протестировать опрос снова",
    testSurveyWidth: "Ширина опроса:",
    logic: "Логика опроса",
    embedSurvey: "Вставить опрос",
    translation: "Перевод",
    saveSurvey: "Сохранить Опрос",
    designer: "Обзор конструктора",
    jsonEditor: "JSON редактор",
    undo: "Отменить",
    redo: "Повтор",
    options: "Параметры",
    generateValidJSON: "Сформировать валидный JSON",
    generateReadableJSON: "Сформировать читаемый JSON",
    toolbox: "Панель инструментов",
    toolboxGeneralCategory: "Общие",
    delSelObject: "Удалить выбранный объект",
    editSelObject: "Редактировать выбранный объект",
    correctJSON: "Пожалуйста, исправьте JSON.",
    surveyResults: "Результаты обследования:",
    surveyResultsTable: "Как видно из таблицы",
    surveyResultsJson: "Как JSON",
    resultsTitle: "Вопрос Название",
    resultsName: "Название вопроса",
    resultsValue: "Значение ответа",
    resultsDisplayValue: "Отображаемое значение",
    modified: "Modified",
    saving: "Сохранение",
    saved: "Сохраненный",
    saveError: "Ошибка редактора содержимого не сохраняется.",
    translationAddLanguage: "Выбор языка для перевода",
    translationShowAllStrings: "Показать все строки",
    translationShowAllPages: "Показать все страницы",
    translationNoStrings: "Нет строки, чтобы перевести Пожалуйста, замените фильтр..",
    translationExportToSCVButton: "Экспорт в CSV",
    translationImportFromSCVButton: "Импорт из CSV",
    translationMergeLocaleWithDefault: "Объединение {0} с локалью по умолчанию",
    bold: "Жирный",
    italic: "Курсив",
    underline: "Подчеркивание",
    fpAddQuestion: "Добавить вопрос ...",
    completedHtmlOnConditionItemText: "Показать, если:",
    lg: {
      //Logic tab strings
      page_visibilityName: "видимость страницы",
      panel_visibilityName: "видимость панели",
      panel_enableName: "Панель включения / выключения",
      question_visibilityName: "Вопрос видимость",
      question_enableName: "Вопрос включения / выключения",
      question_requireName: "Вопрос по желанию требуется",
      trigger_completeName: "Полный обзор",
      trigger_setvalueName: "Установить значение вопрос",
      trigger_copyvalueName: "Копировать вопрос значение",
      trigger_skipName: "Перейти к вопросу",
      trigger_runExpressionName: "Выполнить  запрос",
      completedHtmlOnConditionName: "Пользовательский„Спасибо страницы“текст",

      page_visibilityDescription:
        "Сделать страницу видимой, когда логика выражение возвращает истину. В противном случае держать его невидимым.",
      panel_visibilityDescription:
        "Сделать панель видна, когда логика выражение возвращает истину. В противном случае держать его невидимым.",
      panel_enableDescription:
        "Сделать панель, и все элементы, находящиеся внутри него, включите когда логика выражение возвращает истину. В противном случае держать их отключен.",
      question_visibilityDescription:
        "Сделайте вопрос видимым, когда логика выражение возвращает истину. В противном случае держать его невидимым.",
      question_enableDescription:
        "Сделать этот вопрос включить, когда логика выражение истинно. В противном случае держать его выключенным.",
      question_requireDescription:
        "Вопрос становится требуется, когда логика выражение истинно.",
      trigger_completeDescription:
        "Когда логика выражение истинно, то исследование становится законченным и конечный пользователь мог видеть„спасибо страницы“.",
      trigger_setvalueDescription:
        "Когда значение вопроса, которые используются в логическом выражении, изменяется и логика выражение возвращает истину, то значение устанавливаются на выбранный вопрос.",
      trigger_copyvalueDescription:
        "Когда значение вопроса, которые используются в логическом выражении, изменяется и логика выражение возвращает истину, то значение одного выбранного вопроса копируются другой выбранный вопрос.",
      trigger_skipDescription:
        "Когда логика выражение истинно, то опрос пропустить / фокусировать выбранный вопрос.",
      trigger_runExpressionDescription:
        "Когда логика выражение истинно, то пользовательское выражение выполняется. Вы можете дополнительно установить этот результат экспрессии в выбранном вопрос",
      completedHtmlOnConditionDescription:
        "Если логики выражение возвращает истинный, то текст по умолчанию для„Спасибо страницы“изменяются на заданном.",

      itemExpressionText: "Когда выражение: '{0}' возвращает истину:", //{0} - the expression
      page_visibilityText: "Сделать страницу {0} видимую", //{0} page name
      panel_visibilityText: "Сделать панель {0} видимую", //{0} panel name
      panel_enableText: "Сделать панель {0} включить", //{0} panel name
      question_visibilityText: "Сделать вопрос {0} видна", //{0} question name
      question_enableText: "Сделать вопрос {0} включить", //{0} question name
      question_requireText: "Сделать вопрос {0} требуется", //{0} question name
      trigger_completeText: "Исследование становится законченным",
      trigger_setvalueText: "Установить вопрос: {0} значение {1}", //{0} question name, {1} setValue
      trigger_copyvalueText: "Копировать вопрос: {0} значение от вопроса {1}", //{0} and {1} question names
      trigger_skipText: "Обзор перейти к вопросу {0}", //{0} question name
      trigger_runExpressionText1: "Выполнить выражение: '{0}'", //{0} the expression
      trigger_runExpressionText2: "и установить его результат вопрос: {0}", //{0} question name
      completedHtmlOnConditionText:
        "Показать пользовательский текст для 'Страницы спасибо.",

      expressionEditorTitle: "Настройка логики выражение",

      deleteOperation: "Удалить операцию",
      addNewOperation: "Добавить новую операцию(ы)",

      expressionInvalid:
        "Логика выражения недействительна. Пожалуйста, исправьте его.",
      noOperationError: "Пожалуйста, добавьте по крайней мере одну операцию.",
      operationInvalid: "Пожалуйста, исправьте ошибки в вашей работе (ы)."
    }
  },
  // Property names in table headers
  pel: {
    isRequired: "Требуется?"
  },
  // Property Editors
  pe: {
    apply: "Применить",
    ok: "OK",
    save: "Сохранить",
    cancel: "Отменить",
    reset: "Сброс",
    close: "Закрыть",
    delete: "Удалить",
    add: "Добавить",
    Addnew: "Add новый",
    addItem: "Нажмите, чтобы добавить элемент ...",
    addOther: "Другое",
    addSelectAll: "Выбрать все",
    addNone: "Ничего",
    removeAll: "Удалить все",
    edit: "Редактировать",
    back: "Возврат без сохранения",
    saveAndBack: "Сохранить и вернуться",
    itemValueEdit: "Видимый Если",
    editChoices: "Изменить выбор",
    move: "Переместить",
    empty: "<пусто>",
    notEmpty: "<редактировать значение>",
    fastEntry: "Быстрый вход",
    formEntry: "Форма входа",
    testService: "Тест услуги",
    itemSelectorEmpty: "Пожалуйста, выберите элемент",
    conditionSelectQuestion: "Выберите вопрос ...",
    conditionSelectPage: "Выбрать страницу ...",
    conditionSelectPanel: "Выберите панель ...",
    conditionValueQuestionTitle: "Пожалуйста, введите / выберите значение",
    conditionButtonAdd: "Добавить",
    conditionButtonReplace: "Заменить",
    conditionHelp:
      "Пожалуйста, введите логическое выражение. Оно должна возвращать верно держать вопрос / страница видна, например:.. {Question1} =„значение1“или ({question2} * {Вопрос4}> 20 и {Вопрос3} <5)",
    expressionHelp:
      "Пожалуйста, введите выражение Вы можете использовать фигурные скобки, чтобы получить доступ к значениям вопрос: '{Question1} + {question2}', '({цена} * {количество}) * (100 - {скидка}).",
    aceEditorHelp: "Нажмите Ctrl + пробел, чтобы получить подсказки",
    aceEditorRowTitle: "Текущая строка",
    aceEditorPanelTitle: "Текущая панель",
    showMore: "Для получения более подробной информации, пожалуйста, обратитесь к документации",
    conditionShowMoreUrl:
      "Https://surveyjs.io/Documentation/LibraryParameter?id=Question¶meter=visibleIf",
    assistantTitle: "Доступные вопросы:",
    cellsEmptyRowsColumns: "Существует должно быть по крайней мере один столбец или строка",

    propertyIsEmpty: "Пожалуйста, введите значение",
    value: "Value",
    text: "Текст",
    rowid: "ID строки",
    imageLink: "Image Link",
    columnEdit: "Изменить столбец: {0}",
    itemEdit: "Редактировать элемент: {0}",

    url: "URL",
    path: "Путь",
    valueName: "Имя значения",
    titleNam: "Название пункта",
  
    hasOther: "Есть другой пункт",
    otherText: "Другой текстовый элемент",
    hasNone: "ни одного пункта",
    noneText: "Ни один элемент текста",
    hasSelectAll: "Имеет выбрать все пункт",
    selectAllText: "Выбрать весь текст пункта",
    choicesMin: "Минимальное значение генерируется автоматически ",
    choicesMax: "Максимальное значение генерируется автоматически",
    choicesStep: "Разница между автоматическим сгенерироваными элементами",
    name: "Имя",
    title: "Название",
    cellType: "Мобильный тип",
    ColCount: "Колонка кол",
    choicesOrder: "Выбрать порядок выбора",
    visible: "Видимый?",
    isRequired: "Обязательный?",
    isAllRowRequired: "Требовать ответ для всех строк",
    requiredErrorText: "Текст ошибки необходимого поля",
    startWithNewLine: "Является ли начать с новой строки?",
    rows: "Количество строк",
    PlaceHolder: "Место",
    showPreview: "Показать предпросмотр?",
    storeDataAsText: "содержимое файла Хранить в JSON, а результат в виде текста",
    MaxSize: "Максимальный размер файла в байтах",
    ImageHeight: "Высота изображения",
    ImageWidth: "Ширина изображения",
    rowCount: "Количество строк",
    columnLayout: "Макет колонок",
    addRowLocation: "Добавить строку кнопки местоположение",
    addRowText: "Добавить кнопку строки текста",
    removeRowText: "Удалить кнопку строки текста",
    rateMin: "Минимальное отношение",
    rateMax: "Максимальное отношение",
    rateStep: "шаг оценки",
    minRateDescription: "Минимальное описание скорости",
    maxRateDescription: "Максимальное описание скорости",
    inputType: "Тип ввода",
    optionsCaption: "Параметры заголовка",
    DefaultValue: "Значение по умолчанию",
    cellsDefaultRow: "По умолчанию ячейки тексты",
  
    surveyEditorTitle: "Настройки опросного листа",
    qEditorTitle: "Изменить: {0}",
  
    maxLength: "Максимальная длина",
  
    //survey
    showTitle: "Показывать заголовок / скрыть",
    locale: "Язык по умолчанию",
    simulator: "Выберите устройство",
    landscapeOrientation: "Пейзаж",
    mode: "Режим (редактирование / только для чтения)",
    clearInvisibleValues: "Очистить невидимые значения",
    cookieName: "Имя Cookie (отключить повторное прохождение опроса локально)",
    sendResultOnPageNext: "Отправить результаты опроса на странице рядом",
    storeOthersAsComment: "Хранить 'другое' в отдельном поле",
    showPageTitles: "Показать название страницы",
    showPageNumbers: "Показывать номера страниц",
    pagePrevText: "Предыдущая страница кнопка текст",
    pageNextText: "Следующая страница кнопка текст",
    completeText: "Полный текст кнопки",
    startSurveyText: "Текст кнопки запуска",
    showNavigationButtons: "Показывать кнопки навигации (навигация по умолчанию)",
    showPrevButton: "Показать предыдущие кнопки (пользователь может вернуться на предыдущую страницу)",
    firstPageIsStarted: "Первая страница в опросе является началом страницы.",
    showCompletedPage: "Показать заполненную страницу в конце (completedHtml)",
    goNextPageAutomatic: "Переходить на следующую страницу автоматически при заполнении всех вопросов",
    showProgressBar: "Показывать прогресс заполнения",
    questionTitleLocation: "Вопрос название местоположения",
    requiredText: "Требуется символ(ы) в опросе",
    questionStartIndex: "Начальный индекс в опросе (1, 2 или 'A', 'а')",
    showQuestionNumbers: "Показать номера вопросов",
    questionTitleTemplate: "Шаблон названия опроса, по умолчанию: {нет} {требует} {название}.",
    questionErrorLocation: "Размещение ошибки опроса",
    focusFirstQuestionAutomatic: "Фокус на первом вопросе при изменении страницы",
    questionsOrder: "Элементы отсортированы на странице",
    maxTimeToFinish: "Максимальное время, чтобы закончить опрос",
    maxTimeToFinishPage: "Максимальное время, чтобы закончить страницу в опросе",
    showTimerPanel: "Показать панель таймера",
    showTimerPanelMode: "Показать режим панели таймера",
    RenderMode: "Режим визуализации",
    allowAddPanel: "Разрешить добавление панели",
    allowRemovePanel: "Разрешить удаление панели",
    panelAddText: "Добавление текста на панели",
    panelRemoveText: "Удаление текста на панели",
    isSinglePage: "Показать все элементы на одной странице",
    HTML: "Html",
    expression: "Выражение",
  
    minValue: "Минимальное значение",
    maxValue: "Максимальное значение",
    mINLENGTH: "Минимальная длина",
    allowDigits: "Разрешить цифры",
    minCount: "Минимальное количество",
    maxCount: "Максимальное количество",
    regex: "Регулярное выражение",
  
    totalText: "Общий текст",
    totalType: "Общий вид",
    totalExpression: "Общее выражение",
    totalDisplayStyle: "Общий стиль отображения",
    totalCurrency: "Общая валюта",
    totalFormat: "Общий формат",
  
    tabs: {
      general: "Общие",
      fileOptions: "Параметры",
      HTML: "Редактор HTML",
      columns: "Столбцы",
      rows: "Ряды",
      choices: "Выбор",
      items: "Элементы",
      visibleIf: "Видимый при условии",
      enableIf: "Доступен при условии",
      requiredIf: "Обязателен для заполнения если",
      rateValues: "Оценить важность вопроса",
      choicesByUrl: "Выбор из Интернета",
      matrixChoices: "Выбор по умолчанию",
      multipleTextItems: "Ввод нескольких текстовых полей",
      validators: "Валидаторы",
      navigation: "Навигация",
      question: "Вопрос",
      completedHtml: "Завершен Html",
      completedHtmlOnCondition: "Завершен Html при условии",
      loadingHtml: "Загрузка HTML",
      timer: "Таймер / Викторина",
      calculatedValues: "Расчетные значения",
      triggers: "Триггеры",
      templateTitle: "Название шаблона",
      totals: "Итоги"
    },
    editProperty: "Редактировать свойство '{0}'",
    items: "[Предметы: {0}]",
  
    enterNewValue: "Пожалуйста, введите значение.",
    noquestions: "В опросе нет вопросов",
    createtrigger: "Пожалуйста, создайте триггер",
    triggerOn: "О",
    triggerMakePagesVisible: "Сделайте страницы видимым:",
    triggerMakeQuestionsVisible: "Сделать элементы видны:",
    triggerCompleteText: "Завершить опрос, если удастся.",
    triggerNotSet: "Тригер не установлен",
    triggerRunIf: "Запустить, если",
    triggerSetToName: "Изменить значение:",
    triggerFromName: "Скопировать значение из:",
    triggerRunExpression: "Выполнить это выражение:",
    triggerSetValue: "в:",
    triggerGotoName: "Переместится в опрос:",
    triggerIsVariable: "Не помещайте переменную в результат опроса.",
    triggerRunExpressionEmpty: "Пожалуйста, введите корректное выражение"
  },
  // Property values
  pv: {
    true: "правда",
    false: "ложь",
    inherit: "наследовать",
    show: "Показать",
    hide: "Скрыть",
    default: "По умолчанию",
    initial: "Первоначально",
    random: "Случайно",
    collapsed: "Оборвался",
    expanded: "Расширен",
    none: "Нет",
    asc: "По возрастанию",
    desc: "По убыванию",
    indeterminate: "Неопределенный",
    decimal: "Десятичный",
    currency: "Валюта",
    percent: "Проценты",
    firstExpanded: "firstExpanded",
    off: "Выключить",
    onPanel: "onPanel",
    onSurvey: "onSurvey",
    list: "список",
    progressTop: "progressTop",
    progressBottom: "progressBottom",
    progressTopBottom: "progressTopBottom",
    horizontal: "горизонтальный",
    vertical: "вертикальный",
    top: "Сверху",
    bottom: "Внизу",
    topBottom: "Сверху и внизу",
    left:"Слева",
    color: "цвет",
    date: "Дата",
    datetime: "Дата и время",
    "datetime-local": "Локальные дата и время",
    email: "электронная почта",
    month: "месяц",
    number: "номер",
    password: "пароль",
    range: "диапазон",
    tel: "телефон",
    text: "текст",
    time: "время",
    url: "URL",
    week: "неделя",
    hidden: "скрытый",
    on: "Включить",
    onPage: "На странице",
    edit: "редактировать",
    display: "Дисплей",
    onComplete: "По завершению",
    onHidden: "По скрытию",
    all: "Все",
    page: "Страница",
    survey: "Опрос",
    onNextPage: "При переходе на следующую страницу",
    onValueChanged: "При изменении значения"
  },
  // Operators
  op: {
    empty: "не заполнен",
    notempty: "заполнен",
    equal: "равен",
    notequal: "не равен",
    contains: "содержит",
    notcontains: "не содержит",
    anyof: "любой из",
    allof: "все из",
    greater: "больше",
    less: "меньше",
    greaterorequal: "больше или равен",
    lessorequal: "меньше или равен"
  },
  // Embed window
  ew: {
    angular: "Используйте версию Angular",
    jquery: "Используйте версию jQuery",
    knockout: "Используйте версию Knockout",
    react: "Используйте версию React",
    vue: "Используйте версию Vue",
    bootstrap: "Для библиотеки bootstrap",
    standard: "Без библиотеки bootstrap",
    showOnPage: "Показывать опрос на странице",
    showInWindow: "Показывать опрос в модальном окне",
    loadFromServer: "Загрузить Json с сервера",
    titleScript: "Скрипты и стили",
    titleHtml: "HTML",
    titleJavaScript: "JavaScript"
  },
  // Опрос Тест
  ts: {
    selectPage: "Выберите страницу, чтобы проверить это:",
    showInvisibleElements: "Показать невидимые элементы"
  },
  validators: {
    answercountvalidator: "Количество ответов",
    EmailValidator: "Электронная почта",
    expressionvalidator: "Выражение",
    numericvalidator: "Числовой",
    regexvalidator: "Регулярное выражение",
    textvalidator: "Текст"
  },
    triggers: {
    completetrigger: "Полный обзор",
    setvaluetrigger: "Установленное значение",
    copyvaluetrigger: "Скопировать значение",
    skiptrigger: "Переходите к вопросу",
    runexpressiontrigger: "Запустить выражение",
    visibletrigger: "Изменение видимости (не рекомендуется)"
  },
  // Properties
  p: {
    name: "Имя",
    title: {
      name: "Название",
      title: "Оставьте его пустым, если оно такое же, как„Имя“"
    },
    navigationButtonsVisibility: "Видимость навигационных кнопок",
    questionsOrder: "Порядок вопросов",
    maxTimeToFinish: "Максимальное время для завершение",

    visible: "Видимый",
    visibleIf: "Видимый если",
    questionTitleLocation: "Расположение названия вопроса",
    description: "Описание",
    state: "состояние",
    isRequired: "обязателен",
    requiredIf: "обязателен если",
    indent: "отступ",
    requiredErrorText: "Это поле обязательное для заполнения",
    startWithNewLine: "Начинать с новой строки",
    innerIndent: "Внутренний отступ",
    page: "страница",

    width: "ширина",

    commentText: "Комментарий",
    valueName: "Название значения",
    enableIf: "Доступен при условии",
    defaultValue: "Значение при умолчании",
    correctAnswer: "Правильный ответ",
    readOnly: "Только для чтения",
    validators: "валидаторы",
    titleLocation: "Расположение названия",

    hasComment: "Есть комментарий",
    hasOther: "Есть отдел 'Другое'",
    choices: "выбор",
    choicesOrder: "выбрать порядок выбора",
    choicesByUrl: "выбор из интернета",
    otherText: "Другой текстовый элемент",
    otherErrorText: "Текст ошибки поля 'другое'",
    storeOthersAsComment: "Хранить значение поля 'другое', как комментарий",

    label: "ярлык",
    showTitle: "показывать название",
    valueTrue: "значение истинно",
    valueFalse: "значение ложно",

    cols: "колонки",
    rows: "столбцы",
    placeHolder: "плейсхолдер",

    optionsCaption: "Заголовок опций",

    expression: "выражение",
    format: "формат",
    displayStyle: "стиль отображения",
    currency: "валюта",
    useGrouping: "использовать группировку",

    showPreview: "показывать превью",
    allowMultiple: "выбирать несколько",
    imageHeight: "высота изображения",
    imageWidth: "ширина изображения",
    storeDataAsText: "Хранить данные в виде текста",
    maxSize: "максимальный размер",

    html: "html",

    columns: "колонки",
    cells: "столбцы",
    isAllRowRequired: "Все столбцы обязательны для заполнения",

    horizontalScroll: "горизонтальный скролл",
    cellType: "тип клетки",
    columnsLayout: "макет колонок",
    columnColCount: "количество колонок",
    columnMinWidth: "минимальная ширина колорнки",

    rowCount: "количество столбцов",
    minRowCount: "минимальное количество столбцов",
    maxRowCount: "максимальное количество столбцов",
    keyName: "название ключа",
    keyDuplicationError: "Ошибка при дубликате ключей",
    confirmDelete: "подтвердить удаление",
    confirmDeleteText: "текст при подтверждении удаления",
    addRowLocation: "добавить расположение столбцов",
    addRowText: "текст при добавлении столбца",
    removeRowText: "текст при удалении столбца",

    items: "элементы",
    itemSize: "размер элементов",
    colCount: "количество колонок",

    templateTitle: "название макета",
    templateDescription: "описание макета",
    allowAddPanel: "разрешить добавление панели",
    allowRemovePanel: "разрешить удаление панели",
    panelCount: "количество панелей",
    minPanelCount: "минимальное количество панелей",
    maxPanelCount: "максимальное количество панелей",
    panelsState: "состояние панелей",
    panelAddText: "текст при добавлении панели",
    panelRemoveText: "текст при удалении панели",
    panelPrevText: "текст предыдущей панели",
    panelNextText: "текст следующей панели",
    showQuestionNumbers: "показывать номера вопросов",
    showRangeInProgress: "Ппоказывать индикатор прогресса",
    renderMode: "режим отображения",
    templateTitleLocation: "Расположения заголовка шаблона",

    rateValues: "Оценить важность опроса",
    rateMin: "минимальное значение",
    rateMax: "максимальное значение",
    rateStep: "шаг оценки",
    minRateDescription: "описание минимальной оценки",
    maxRateDescription: "описание максимальной оценки",

    inputType: "тип ввода",
    size: "размер",

    locale: "локаль",
    focusFirstQuestionAutomatic: "Фокус на первом вопросе при изменении страницы",
    completedHtml: "Завершен Html",
    completedHtmlOnCondition: "Завершен Html при условии",
    loadingHtml: "Загрузка html",
    triggers: "триггеры",
    cookieName: "имя Cookie",
    sendResultOnPageNext: "Отправить результаты опроса на странице рядом",
    showNavigationButtons: "Показывать кнопки навигации (навигация по умолчанию)",
    showPrevButton: "Показать предыдущие кнопки (пользователь может вернуться на предыдущую страницу)",
    showPageTitles: "Показать название страницы",
    showCompletedPage: "Показать заполненную страницу в конце (completedHtml)",
    showPageNumbers: "Показывать номера страниц",
    questionErrorLocation: "Размещение ошибки опроса",
    showProgressBar: "Показывать прогресс заполнения",
    mode: "Режим",
    goNextPageAutomatic: "Переходить на следующую страницу автоматически при заполнении всех вопросов",
    checkErrorsMode: "Режим проверки ошибок",
    clearInvisibleValues: "Очистить невидимые значения",
    startSurveyText: "Текст кнопки запуска",
    pagePrevText: "Предыдущая страница кнопка текст",
    pageNextText: "Следующая страница кнопка текст",
    completeText: "Полный текст кнопки",
    requiredText: "Требуется символ(ы) в опросе",
    questionStartIndex: "Начальный индекс в опросе (1, 2 или 'A', 'а')",
    questionTitleTemplate: "Шаблон названия опроса, по умолчанию: {нет} {требует} {название}.",
    firstPageIsStarted: "Первая страница в опросе является началом страницы.",
    isSinglePage: "Показать все элементы на одной странице",
    maxTimeToFinishPage: "Максимальное время, чтобы закончить страницу в опросе",
    showTimerPanel: "Показать панель таймера",
    showTimerPanelMode: "Показать режим панели таймера",

    defaultPanelValue: "Значение панели по умолчанию",
    defaultRowValue: "Значение столбца по умолчанию",
    hasNone: "Пустое значение",
    noneText: "Текст пустого значения",

    text: "текст"
  }
};
//Uncomment this line on creating a translation file. You should replace "en" and enStrings with your locale ("fr", "de" and so on) and your variable.
editorLocalization.locales["ru"] = ruStrings;