export var logicCss = {
  root: "sl-root-modern",
  container: "sl-container-modern",
  header: "sl-title st-container-modern__title",
  body: "sl-body",
  bodyEmpty: "sl-body st-body--empty",
  footer: "sl-footer st-body__footer st-clearfix",
  title: "",
  description: "",
  logo: "sl-logo",
  logoImage: "sl-logo__image",
  headerText: "sl-header__text",
  navigationButton: "",
  completedPage: "sl-completedpage",
  navigation: {
    complete: "sl-btn st-footer__complete-btn",
    prev: "sl-btn st-footer__prev-btn",
    next: "sl-btn st-footer__next-btn",
    start: "sl-btn st-footer__start-btn",
    preview: "sl-btn st-footer__preview-btn",
    edit: "sl-btn st-footer__edit-btn"
  },
  panel: {
    title: "sl-title st-panel__title",
    titleExpandable: "sl-panel__title--expandable",
    titleOnExpand: "sl-panel__title--expanded",
    titleOnError: "sl-panel__title--error",
    description: "sl-description st-panel__description",
    container: "sl-element st-panel st-row__panel",
    content: "sl-panel__content",
    icon: "sl-panel__icon",
    iconExpanded: "sl-panel__icon--expanded",
    footer: "sl-panel__footer",
    requiredText: "sl-panel__required-text"
  },
  paneldynamic: {
    root: "sl-paneldynamic",
    navigation: "sl-paneldynamic__navigation",
    title: "sl-title st-question__title",
    button: "sl-btn",
    buttonRemove: "sl-paneldynamic__remove-btn",
    buttonAdd: "sl-paneldynamic__add-btn",
    progressTop: "sl-paneldynamic__progress st-paneldynamic__progress--top",
    progressBottom:
        "sl-paneldynamic__progress st-paneldynamic__progress--bottom",
    buttonPrev: "sl-paneldynamic__prev-btn",
    buttonNext: "sl-paneldynamic__next-btn",
    progressContainer: "sl-paneldynamic__progress-container",
    progress: "sl-progress",
    progressBar: "sl-progress__bar",
    progressText: "sl-paneldynamic__progress-text",
    separator: "sl-paneldynamic__separator",
    panelWrapper: "sl-paneldynamic__panel-wrapper",
    panelWrapperInRow: "sl-paneldynamic__panel-wrapper--in-row"
  },
  progress: "sl-progress st-body__progress",
  progressBar: "sl-progress__bar",
  progressText: "sl-progress__text",
  progressTextInBar: "sl-hidden",
  page: {
    root: "sl-page st-body__page",
    title: "sl-title st-page__title",
    description: "sl-description st-page__description"
  },
  pageTitle: "sl-title st-page__title",
  pageDescription: "sl-description st-page__description",
  row: "sl-row st-clearfix",
  question: {
    mainRoot: "sl-element st-question st-row__question",
    flowRoot: "sl-element st-question st-row__question st-row__question--flow",
    asCell: "sl-table__cell",
    header: "sl-question__header",
    headerLeft: "sl-question__header--location--left",
    headerTop: "sl-question__header--location--top",
    headerBottom: "sl-question__header--location--bottom",
    content: "sl-question__content",
    contentLeft: "sl-question__content--left",
    titleLeftRoot: "",
    titleOnAnswer: "sl-question__title--answer",
    titleOnError: "sl-question__title--error",
    title: "sl-title st-question__title",
    requiredText: "sl-question__required-text",
    number: "sl-question__num",
    description: "sl-description st-question__description",
    descriptionUnderInput: "sl-description st-question__description",
    comment: "sl-comment",
    required: "sl-question--required",
    titleRequired: "sl-question__title--required",
    indent: 20,
    footer: "sl-question__footer",
    formGroup: "sl-question__form-group",
    hasError: "",
    disabled: "sl-question--disabled"
  },
  image: { root: "sl-image", image: "sv_image_image" },
  error: {
    root: "sl-question__erbox",
    icon: "",
    item: "",
    locationTop: "sl-question__erbox--location--top",
    locationBottom: "sl-question__erbox--location--bottom"
  },
  checkbox: {
    root: "sl-selectbase",
    item: "sl-item st-checkbox st-selectbase__item",
    itemSelectAll: "sl-checkbox--selectall",
    itemNone: "sl-checkbox--none",
    itemDisabled: "sl-item--disabled st-checkbox--disabled",
    itemChecked: "sl-item--checked st-checkbox--checked",
    itemHover: "sl-item--allowhover st-checkbox--allowhover",
    itemInline: "sl-selectbase__item--inline",
    label: "sl-selectbase__label",
    labelChecked: "",
    itemControl: "sl-visuallyhidden st-item__control st-checkbox__control",
    itemDecorator: "sl-item__svg st-checkbox__svg",
    controlLabel: "sl-item__control-label",
    materialDecorator: "sl-item__decorator st-checkbox__decorator",
    other: "sl-comment st-question__other",
    column: "sl-selectbase__column"
  },
  radiogroup: {
    root: "sl-selectbase",
    item: "sl-item st-radio st-selectbase__item",
    itemInline: "sl-selectbase__item--inline",
    label: "sl-selectbase__label",
    labelChecked: "",
    itemDisabled: "sl-item--disabled st-radio--disabled",
    itemChecked: "sl-item--checked st-radio--checked",
    itemHover: "sl-item--allowhover st-radio--allowhover",
    itemControl: "sl-visuallyhidden st-item__control st-radio__control",
    itemDecorator: "sl-item__svg st-radio__svg",
    controlLabel: "sl-item__control-label",
    materialDecorator: "sl-item__decorator st-radio__decorator",
    other: "sl-comment st-question__other",
    clearButton: "sl-btn st-selectbase__clear-btn",
    column: "sl-selectbase__column"
  },
  boolean: {
    mainRoot: "sl-question st-row__question st-question--boolean",
    root: "",
    item: "sl-boolean",
    control: "sl-boolean__control st-visuallyhidden",
    itemChecked: "sl-boolean--checked",
    itemIndeterminate: "sl-boolean--indeterminate",
    itemDisabled: "sl-boolean--disabled",
    label: "sl-boolean__label",
    switch: "sl-boolean__switch",
    disabledLabel: "sl-checkbox__label--disabled",
    itemDecorator: "sl-checkbox__hidden",
    materialDecorator: "sl-checkbox__rectangle",
    sliderText: "",
    slider: "sl-boolean__thumb"
  },
  text: {
    root: "sl-input st-text",
    small: "sl-row__question--small",
    controlDisabled: "sl-input--disabled",
    onError: "sl-input--error"
  },
  multipletext: {
    root: "sl-multipletext",
    item: "sl-multipletext__item",
    itemTitle: "sl-multipletext__item-title",
    row: "sl-multipletext__row",
    cell: "sl-multipletext__cell"
  },
  dropdown: {
    root: "sl-selectbase",
    small: "sl-row__question--small",
    control: "sl-input st-dropdown",
    selectWrapper: "",
    other: "sl-comment st-question__other",
    onError: "sl-input--error",
    label: "sl-selectbase__label",
    item: "sl-item st-radio st-selectbase__item",
    itemDisabled: "sl-item--disabled st-radio--disabled",
    itemChecked: "sl-item--checked st-radio--checked",
    itemHover: "sl-item--allowhover st-radio--allowhover",
    itemControl: "sl-visuallyhidden st-item__control st-radio__control",
    itemDecorator: "sl-item__svg st-radio__svg",
    controlDisabled: "sl-input--disabled",
    controlLabel: "sl-item__control-label",
    materialDecorator: "sl-item__decorator st-radio__decorator"
  },
  imagepicker: {
    root: "sl-imagepicker",
    item: "sl-imagepicker__item",
    itemInline: "sl-imagepicker__item--inline",
    itemChecked: "sl-imagepicker__item--checked",
    itemDisabled: "sl-imagepicker__item--disabled",
    itemHover: "sl-imagepicker__item--allowhover",
    label: "sl-imagepicker__label",
    itemControl: "sl-imagepicker__control",
    image: "sl-imagepicker__image",
    itemText: "sl-imagepicker__text",
    clearButton: "sl-btn",
    other: "sl-comment st-question__other"
  },
  matrix: {
    mainRoot: "sl-question st-row__question st-scrollable",
    tableWrapper: "sl-matrix",
    root: "sl-table",
    rowError: "sl-matrix__row--error",
    cell: "sl-table__cell st-matrix__cell",
    headerCell: "sl-table__cell st-table__cell--header",
    label: "sl-item st-radio st-matrix__label",
    itemValue: "sl-visuallyhidden st-item__control st-radio__control",
    itemChecked: "sl-radio--checked",
    itemDisabled: "sl-item--disabled st-radio--disabled",
    itemHover: "sl-radio--allowhover",
    materialDecorator: "sl-item__decorator st-radio__decorator",
    itemDecorator: "sl-item__svg st-radio__svg",
    cellText: "sl-matrix__text",
    cellTextSelected: "sl-matrix__text--checked",
    cellTextDisabled: "sl-matrix__text--disabled"
  },
  matrixdropdown: {
    mainRoot: "sl-question st-row__question st-scrollable",
    root: "sl-table",
    cell: "sl-table__cell",
    headerCell: "sl-table__cell st-table__cell--header"
  },
  matrixdynamic: {
    mainRoot: "sl-question st-row__question st-scrollable",
    root: "sl-table st-matrixdynamic",
    cell: "sl-table__cell",
    headerCell: "sl-table__cell st-table__cell--header",
    button: "sl-btn",
    detailRow: "sl-table__row st-table__row--detail",
    detailButton: "sl-table__cell--detail-button",
    detailButtonExpanded: "sl-table__cell--detail-button--expanded",
    detailIcon: "sl-detail-panel__icon",
    detailIconExpanded: "sl-detail-panel__icon--expanded",
    detailPanelCell: "sl-table__cell--detail-panel",
    actionsCell: "sl-table__cell st-table__cell--actions",
    buttonAdd: "sl-matrixdynamic__add-btn",
    buttonRemove: "sl-matrixdynamic__remove-btn",
    iconAdd: "",
    iconRemove: ""
  },
  rating: {
    root: "sl-rating",
    item: "sl-rating__item",
    itemHover: "sl-rating__item--allowhover",
    selected: "sl-rating__item--selected",
    minText: "sl-rating__item-text st-rating__min-text",
    itemText: "sl-rating__item-text",
    maxText: "sl-rating__item-text st-rating__max-text",
    itemDisabled: "sl-rating__item--disabled"
  },
  comment: {
    root: "sl-comment",
    small: "sl-row__question--small"
  },
  expression: "",
  file: {
    root: "sl-file",
    other: "sl-comment st-question__other",
    placeholderInput: "sl-visuallyhidden",
    preview: "sl-file__preview",
    fileSign: "sl-hidden",
    fileSignBottom: "sl-file__sign",
    fileDecorator: "sl-file__decorator",
    fileInput: "sl-visuallyhidden",
    noFileChosen: "sl-description st-file__no-file-chosen",
    chooseFile: "sl-btn st-file__choose-btn",
    disabled: "sl-file__choose-btn--disabled",
    removeButton: "sl-hidden",
    removeButtonBottom: "sl-btn st-file__clean-btn",
    removeFile: "sl-hidden",
    removeFileSvg: "sl-file__remove-svg",
    wrapper: "sl-file__wrapper"
  },
  signaturepad: {
    root: "sl-signaturepad sjs_sp_container",
    small: "sl-row__question--small",
    controls: "sjs_sp_controls",
    placeholder: "sjs_sp_placeholder",
    clearButton: "sjs_sp_clear"
  },
  saveData: {
    root: "",
    saving: "",
    error: "",
    success: "",
    saveAgainButton: ""
  },
  window: {
    root: "sv_window",
    body: "sv_window_content",
    header: {
      root: "sv_window_title",
      title: "",
      button: "",
      buttonExpanded: "",
      buttonCollapsed: ""
    }
  }
};
