resources:
  repositories:
    - repository: azurepipelines
      type: github
      endpoint: surveyjs
      name: surveyjs/azure-pipelines
      ref: refs/heads/disable-artifact-download

trigger: none
pr: none

extends:
  template: creator.yml@azurepipelines
